### PR TITLE
fix: support RTL usernames in comment header

### LINKED ISSUE #12141: Usernames in RTL languages mess up the layout in comments
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.6

### Steps to reproduce the bug

1.Go to a Video with a username in an RTL language in the comments, example:  https://www.youtube.com/watch?v=wJsFlCQcwrw (in the replies of the pinned comment)
2. See error

### Expected behavior

It should be handled the same way the YouTube website does it, the name can be RTL but the rest stays LTR

### Actual behavior

It writes everything RTL, It is partially fixex in the new (refactored) interface but it does a weird thing with the time, see:

Image

### Screenshots/Screen recordings

Image

Image

### Logs

_No response_

### Affected Android/Custom ROM version

_No response_

### Affected device model

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by VougJo23**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
-  Wrapped  uploader's username using BidiFormatter to fix direction issues when combining RTL usernames with timestamps  in comment headers.

#### Before/After Screenshots/Screen Record
- Before:
image

- After:
image

#### Fixes the following issue(s)

- Fixes #12141 

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
Example Video: https://www.youtube.com/watch?v=_t69RAfpAGY

**Comment by Profpatsch** [comment]
We should make sure the @ stays in front of the username, right now it’s pushed all the way to the right.

**Comment by Profpatsch** [comment]
I removed the formatting changes from the commit, since they obscured the logic too much.

File: app/src/main/java/org/schabi/newpipe/util/Localization.java [hunk 1]
```diff
@@ -78,10 +79,13 @@ public static String concatenateStrings(final String... strings) {
         return concatenateStrings(DOT_SEPARATOR, Arrays.asList(strings));
     }
 
+    // Use of BidiFormater to fix text direction automatically
     @NonNull
     public static String concatenateStrings(final String delimiter, final List<String> strings) {
+        final BidiFormatter bidi = BidiFormatter.getInstance();
         return strings.stream()
                 .filter(string -> !TextUtils.isEmpty(string))
+                .map((s) -> strings.indexOf(s) == 0 ? bidi.unicodeWrap(s) : s) // only wrap username
```
Comment (Profpatsch) [inline app/src/main/java/org/schabi/newpipe/util/Localization.java:88]: Hm, I’m not sure we should add this logic to `concatenateStrings`, if you look at the call graph this function gets used in a lot of places, not just the username logic:
image

**Comment by Profpatsch** [comment]
I switched the code around a little, now it looks reasonable to me:

image

**Review by Profpatsch — APPROVED** [review]

**Comment by Profpatsch** [comment]
Thank you! Great change

**Comment by Profpatsch** [comment]
@VougJo23 Oh, wait, maybe I didn’t understand it then

For me the Youtube browser app displays it like this:
image

Maybe where the @ is put depends on your locale in general??

**Comment by Profpatsch** [comment]
Sorry btw for taking a potentially disturbing video of a current conflict as an example :(
Next time I’ll try to find something more neutral.
