### PR TITLE
Fix download dialog selector layout

### LINKED ISSUE #6677: In Download Dialog UI, margin is not even
### Checklist

- [x] I am using the latest version - v0.21.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Try to download any video
2. When dialog box shows up Click the Radio Buttons
- Video 
- Audio 
- Captions
_I have marked the region I am talking about._

a
b

### Actual behavior

The margin seems like more than needed and is uneven.

### Expected behavior

Even margin for marked region.
Or may be some redesign I purposed in https://github.com/TeamNewPipe/NewPipe/issues/5508

### Device info

 - Android version/Custom ROM version: 9 Pie
 - Device model: Huawei Nova 3i

### PR DESCRIPTION
**Pull request by mauriciocolli**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Some logic was missing in the adapter for making the no-audio icon  `GONE` instead of `INVISIBLE`. I fixed it and added some tests as well.

That reveals another problem: some icons are not themed properly, I will fix that in another pull request.

#### Fixes the following issue(s)
- Fixes #6677

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by litetex — CHANGES_REQUESTED** [review]
Code looks on the first impression good.
👍 for the tests

However I would appreciate some (there is currently zero) documentation like JavaDoc or comments.

**Comment by mauriciocolli** [comment]
Done.

File: app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java [hunk 1]
```diff
@@ -171,6 +180,32 @@ private View getCustomView(final int position, final View view, final ViewGroup
...
+     */
+    private boolean hasSecondaryStream(final int position) {
+        return secondaryStreams != null && secondaryStreams.get(position) != null;
+    }
+
+    /**
+     * @return if there are any video-only streams with no secondary stream associated with them.
+     * @see #hasVideoOnlyWithNoSecondaryStream
+     */
+    private boolean checkHasVideoOnlyWithNoSecondaryStream() {
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java:195]: I would rename that method to ``checkHasAnyVideoOnlyStreamWithNoSecondaryStream``

**Review by litetex — COMMENTED** [review]
LGTM

However I'm unable to get a situation where the icon is visible in the first place.

@mauriciocolli 
Do you know a situation/video where that's the case?

**Comment by litetex** [comment]
* Rebased the PR
* Applied changes
* Fixed tests
* The UI works now as expected:
Modified - for testing purposes (because I couldn't find any stream that has no audio) - ``hasSecondaryStream`` so that it always returns ``false`` :
grafik grafik

**Review by litetex — APPROVED** [review]
