### PR TITLE
Fix ReCaptcha activity and correctly save obtained cookies

### LINKED ISSUE #2484: ui crashes when google serves a captcha page
- [yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
--> I forgot to capture the crash report, error occurs randomly
- [yes] I checked if the issue/feature exists in the latest version. 16.2
- [ ] I did use the [incredible bugreport to markdown converter] (https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports. (next time)

I'm using orbot. Once in a while newpipe crashes when loading a video. By following the share link to external browser I just found out that google asks to solve a captcha because of high site traffic (last tor exit node heavily in use?).
If it happens again I will post the crash report (probably useless) but also the served html (for the extractor to learn to recognize the code).

### LINKED ISSUE #2788: recapcha issue
Hey we seem to have an issue with recapcha. Can it be fixed? 
Screenshot_2019-11-07-02-15-05-77

### LINKED ISSUE #2924: Recaptcha challenge
Screenshot_2020-01-05-16-28-51

When i go to play any video i am getting this issue on latest version, before this was something like extract issue.

### LINKED ISSUE #2979: NPE on reCAPTCHA challenge
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ FR
* __Service:__ none
* __Version:__ 0.18.1
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.find_access_cookies(ReCaptchaActivity.java:128)
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.onPageFinished(ReCaptchaActivity.java:113)
	at t6.b(PG:15)
	at ld.handleMessage(PG:43)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</p></details>
<hr>
I was scrolling what's new in peertube.co.uk instance. It happens everytime I scroll to look at a few videos

### LINKED ISSUE #2986: Rename NewPipe to "NewestPipe".
- [x ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Just a suggestion. Eventually, a competitor may arise, and by the name of "NewerPipe". Might as well beat them to the punch to declare this project as the newest possible pipe.

### LINKED ISSUE #3023: Recaptcha crash on app open
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x ] I checked if the issue/feature exists in the latest version.
- [x ] I did use the [incredible bugreport to markdown converter]

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.18.2
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.find_access_cookies(ReCaptchaActivity.java:128)
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.onPageFinished(ReCaptchaActivity.java:113)
	at e6.b(PG:2)
	at on.handleMessage(PG:63)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```
</p></details>
<hr>

### PR DESCRIPTION
**Pull request by Stypox**
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

## Description
This pr aims to solve the many issues regarding the ReCaptchaActivity. In #2527 I tried to fix it, though I was unable to test the changes since I couldn't reproduce any ReCAPTCHAs anymore, so it kept crashing. After @B0pol in #2979 provided a way to reproduce, I was able to redesign the activity. Before the cookies were extracted from the page on close, but unfortunately this didn't imply that the captha was solved, since there could have been redirections or the page didn't close on resolution. Now the user is provided with a "Done" button to press when he finishes solving the captcha, that sets the cookies to the downloader.
Sometimes services return a recaptcha challenge error code (429) just to indicate Too Many Requests, so in that case the ReCaptchaActivity is opened, but the only thing the user has to do is press "Done" since there are no recaptchas to solve. ~~This is the only scenario I was able to test, and I am confident the Youtube cookie extraction method works since I didn't change it,~~ **(it didn't work, but it should be fixed now)** ~~though I am not entirely sure that the `handleCookies` function is always called (someone who knows how `WebViewClient`s work?).~~ **(now it is always called on close)**.

Also renamed some recaptcha-related strings to have them match the naming conventions, leading to many changed strings.xml files.

## Follow-ups for next pull requests
Maybe we should keep a hash-table with all cookies and their values and update that table every time we need, instead of overwriting the whole cookie string every time. Since, for now, the only service with recaptchas is YouTube, there is no problem to always overwrite the old Downloader cookies, but for the future we might need to change this.
Anyway in the `handleCookies` function I left the space for other services (other than Youtube) to try and extract cookies.

## Fixes & debug apk
Fixes #3023 fixes #2979 fixes #2924 fixes #2986 fixes #2788 fixes #2484
For some reason I was unable to provide a working apk in #2979, but here is a debug apk anyway: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4130184/app-debug.zip)

### CODE REVIEW

**Comment by B0pol** [comment]
I car confirm it's fixing fine #2979. 
Just a question : could you make background agree with theme?

This is the page I had with peertube.co.uk , my theme was default (grey)

**Comment by TobiGr** [comment]
> Just a question : could you make background agree with theme?

This should be quite easy. Maybe we can pass either some js to the webview after loading the site. For converting R.color ids which are used in the themes to hex, you might use the the `getHexRGBColor` method from [here](https://github.com/TeamNewPipe/NewPipe/blob/0447e4e6645504d24a7752e2f266aa8b2364d4b0/app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.java#L129). However, it should be move the to an util class.

File: app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java [hunk 1]
```diff
@@ -89,74 +91,89 @@ protected void onCreate(Bundle savedInstanceState) {
...
-                    c_s_gl = part.trim();
-                }
-                if (part.trim().startsWith("goojf")) {
-                    c_goojf = part.trim();
-                }
+    private void handleCookies(@Nullable String cookies) {
+        if (MainActivity.DEBUG) Log.d(TAG, "handleCookies: cookies=" + (cookies == null ? "null" : cookies));
+        if (cookies == null) return;
+
+        addYoutubeCookies(cookies);
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: It might be good to check the service id first. Just in case we get a reCAPTCHA from a different service.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: This could be done, but it would require modifying the downloader making it service-aware, so that it can throw service-aware recaptcha exceptions. Another option would be to recognize the service from the url using its url handler, but API urls wouldn't be probably recognized.
So I think this is good as it is, since if the `addYoutubeCookies()` function is able to find YouTube cookies they get saved, otherwise they do not. And, as the comment on the line below suggests, it is simple to add new cookie extractors for other services in the future.

**Comment by Stypox** [comment]
@B0pol I am not sure it is safe to change the background of the webview. It would surely require some (potentially slow) JavaScript code to be run, and it could create graphical problems on complex recaptcha pages (I use an extension to change colors on my Firefox ("Dark Background and Light Text"), but on some websites it doesn't work properly).
I don't think it is really a problem to have an unthemed recaptcha activity, because after all it is shown very rarely. But anyway if we decide to implement it, I think it would be better suited for a separate PR.

File: app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java (hunk 1 above)
Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: Okay :)

File: app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java [hunk 2]
```diff
@@ -89,74 +90,89 @@ protected void onCreate(Bundle savedInstanceState) {
...
-        private final Activity context;
-        private String mCookies;
+    @Override
+    public boolean onCreateOptionsMenu(Menu menu) {
+        boolean ret = super.onCreateOptionsMenu(menu);
+
+        ActionBar actionBar = getSupportActionBar();
+        if (actionBar != null) {
+            actionBar.setDisplayHomeAsUpEnabled(true);
+            actionBar.setHomeAsUpIndicator(getResources().getDrawable(R.drawable.ic_done_white_24dp));
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: I was not able to get a reCAPTCHA while visiting peertube.co.uk, so I could not test your PR. However from what I can say when reading the code, it looks like there is no theme handling in the toolbar. Please ensure to have the correct button color when using the light theme.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: Unfortunately I am unable to test, too (I keep getting Network Errors in peertube.co.uk). But since the app bar background color is always red I don't think it is a problem to have an always white icon.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: Oh, apparently other menu icons are black in white theme even though they are on the exact same background color as dark theme, which is strange. With white theme this is, respectively, how the app and the recaptcha activity look: should I make the recaptcha activity's icon/text color black?

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
</table>

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: I agree that the black text looks not good. But I'd suggest to use the same colors as in the current theme for consistency. Could you open an issue to ask for help polishing the light theme?

File: app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java [hunk 3]
```diff
@@ -138,8 +140,10 @@ private void saveCookiesAndFinish() {
 
 
 
-    private void handleCookies(@Nullable String cookies) {
-        if (MainActivity.DEBUG) Log.d(TAG, "handleCookies: cookies=" + (cookies == null ? "null" : cookies));
+    private void handleCookies(String url) {
+        String cookies = CookieManager.getInstance().getCookie(url);
+        if (MainActivity.DEBUG) Log.d(TAG, "handleCookies: url=" + url + "; cookies=" + (cookies == null ? "null" : cookies));
+        Log.e(TAG, "handleCookies: url=" + url + "; cookies=" + (cookies == null ? "null" : cookies));
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java]: I guess this was accidentally committed.

**Comment by juanfra684** [comment]
I'm testing the apk file attached to the first comment but it doesn't fix my problems with YT captchas. I always get a captcha when I try to watch a YT video. I solve the captcha and can watch the video in the webview of NewPipe. I press ✔️ when I solve the captchas but then I get again another captcha with the next video which I watch.

**Comment by Stypox** [comment]
@juanfra684 could you test this apk, based on the last commit?
[app-debug_1.zip](https://github.com/TeamNewPipe/NewPipe/files/4142954/app-debug_1.zip)

If even the apk above doesn't work, please use the following one. When you press :heavy_check_mark it throws an error on purpose (so that I can see the content of cookies): please paste the bug report content here.
[app-debug_2.zip](https://github.com/TeamNewPipe/NewPipe/files/4142983/app-debug_2.zip)

**Comment by Stypox** [comment]
@TobiGr this is how the Activity looks like now. Is it ok? I decided to move the button to the right for better UI, since it's an action.
Screenshot_20200201-174955

**Comment by juanfra684** [comment]
> @juanfra684 could you test this apk, based on the last commit?
> [app-debug_1.zip](https://github.com/TeamNewPipe/NewPipe/files/4142954/app-debug_1.zip)

app-debug_1.zip is corrupted. I can extract the apk but I can't install it. app-debug_2.zip installs fine.

**Comment by Stypox** [comment]
Could you try again with this apk (as a replacement for app-debug_1.zip)? Thank you :-)
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4143217/app-debug.zip)

**Comment by juanfra684** [comment]
I've the same problems with the new apk. This is the output of app-debug_2 with the captcha solved:
```plain
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe.debug",
   "version": "0.18.2",
   "os": "Linux Android 7.1.2 - 25",
   "time": "2020-02-01 21:58",
   "exceptions": [
      "java.lang.NullPointerException: Found cookies: YSC=AeJKpj2WGsA; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; VISITOR_INFO1_LIVE=fflNk6rzzmc; GPS=1; CONSENT=WP.283253; YSC=AeJKpj2WGsA; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; VISITOR_INFO1_LIVE=fflNk6rzzmc; GPS=1; CONSENT=WP.283253; YSC=AeJKpj2WGsA; s_gl=e3ea30620a3c9e68880a30237b86c6cfcwIAAABHQg==; VISITOR_INFO1_LIVE=fflNk6rzzmc; GPS=1; CONSENT=WP.283253\n\tat org.schabi.newpipe.ReCaptchaActivity.saveCookiesAndFinish(ReCaptchaActivity.java:134)\n\tat org.schabi.newpipe.ReCaptchaActivity.onOptionsItemSelected(ReCaptchaActivity.java:121)\n\tat android.app.Activity.onMenuItemSelected(Activity.java:3248)\n\tat androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)\n\tat androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)\n\tat androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)\n\tat androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)\n\tat androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)\n\tat androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)\n\tat androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)\n\tat androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)\n\tat androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)\n\tat androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)\n\tat androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)\n\tat androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)\n\tat androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)\n\tat android.view.View.performClick(View.java:5637)\n\tat android.view.View$PerformClick.run(View.java:22433)\n\tat android.os.Handler.handleCallback(Handler.java:751)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:154)\n\tat android.app.ActivityThread.main(ActivityThread.java:6121)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)\n"
   ],
   "user_comment": ""
}
```

**Comment by Stypox** [comment]
> I've the same problems with the new apk.

Do you mean that you're not able to install it, or that solving the recaptcha does nothing? @juanfra684 

> This is the output of app-debug_2 with the captcha solved:

Thank you :-)

**Comment by juanfra684** [comment]
> > I've the same problems with the new apk.
> 
> Do you mean that you're not able to install it, or that solving the recaptcha does nothing? @juanfra684

I can install it but YT always shows a captcha with every video. I can watch any video within the webview after of solve the first captcha, so my IP is not blacklisted. The problem only happens when I go to a video from NewPipe directly.

I've tried a few times solving the captchas and touching ✔️ but YT stills shows captchas with every new video.

**Comment by Stypox** [comment]
@juanfra684 
Ok, I should have fixed the problem with the latest commit, thanks to the report you provided.
Sorry if I keep asking you to test APKs :-), here is hopefully the last one: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4145262/app-debug.zip)

**Comment by juanfra684** [comment]
> @juanfra684
> Ok, I should have fixed the problem with the latest commit, thanks to the report you provided.
> Sorry if I keep asking you to test APKs :-), here is hopefully the last one: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4145262/app-debug.zip)

Don't worry. NewPipe is one of my favorite apps, I've not problem helping to test the fixes.

Looks like your last commit fixed the problem. I only was asked to solve the captcha one time. After that everything worked as usual.

Thanks a lot for fixing this!

**Comment by Stypox** [comment]
Thank you very much for testing!
@TobiGr this should be ready :-D

**Comment by mauriciocolli** [comment]
For reference in the future, there's a very easy way to get reCAPTCHAs to test this issue: route your traffic through tor or any popular free proxy. Chances are good that a abuser/spammer already made it blacklisted.

But this appears to have fixed it.

**PS**: One thing though that was already mentioned, we are setting the cookies for **_EVERY_** request, even for those that the service don't use it, what about we don't do that? Maybe something like a cookie jar for services?

I think this could be done before the next release.

**Comment by Stypox** [comment]
> For reference in the future, there's a very easy way to get reCAPTCHAs to test this issue: route your traffic through tor or any popular free proxy. Chances are good that a abuser/spammer already made it blacklisted.
How can I route my NewPipe's traffic through tor? @mauriciocolli

**Comment by TobiGr** [comment]
@Stypox Install [Orbot](https://2019.www.torproject.org/docs/android.html.en). That app is in the GuardianProject repository which is enabled by default in F-Droid.

**Comment by Stypox** [comment]
Thanks

**Comment by Stypox** [comment]
Thanks
