### PR TITLE
Fix Routeractivity theming

### LINKED ISSUE #8179: Download popup file already exists action buttons display issue
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to "Settings" -> "Video and audio" -> Behavior / Preferred 'open' action -> Select "Download"
2. Open Chrome (should work with other web browner)
3. Go to a video link (search "me at the zoo" for example)
4. Open the link with NewPipe
5. The NewPipe download box will open, click on OK to download the video.
6. Wait the download is over
7. On Chrome, select again the same video link
8. Open the link with NewPipe
9. The NewPipe download box will open, click on OK to download the video.
10. The popup "A downloaded file with this file name is already exists" will open but the action buttons "Cancel" and "Overwrite" will not be display

### Expected behavior

Action buttons "Cancel" and "Overwrite" should be display in the the popup "A downloaded file with this file name is already exists"

### Actual behavior

Action buttons "Cancel" and "Overwrite" are not display in the the popup "A downloaded file with this file name is already exists"
The button are there because we can click on them to have the good behavior but they are not displayed.

### Screenshots/Screen recordings

Screenshot_20220412-121359
Screenshot_20220412-122153__01
Screenshot_20220412-122147__01
Expected : 
Screenshot_20220412-122330

### Logs

_No response_

### Affected Android/Custom ROM version

Android 11 / OxygenOS 11.1.2.2

### Affected device model

OnePlus 6T

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
When the app is not running in the foreground and started via ``RouterActivity`` (e.g. clicking/sharing a link to NewPipe) incorrect things start to happens:
* The UI has incorrect colors (seen in #8179)
  * The day/night mode of the app is ignored
* The language is the device language

Why does this happen?
* The RouterActivityThemes are overriding the ``color*``-attributes (``colorPrimary``, ``colorPrimaryDark``, ...). I'm not sure why this was done in the first place, however it causes the theming issues on the UI.
* RouterActivity misses some code from MainActivity, e.g. ``assureCorrectAppLanguage`` and ``ThemeHelper.setDayNightMode``. This causes further problems like the incorrect language or wrong colored theme elements.

#### Before/After Screenshots/Screen Record
Done via the test manual below:

- Before: 
grafik grafik grafik grafik

- After: 
grafik grafik grafik grafik

#### Fixes the following issue(s)

- Fixes #8179; maybe more issues, hard to check when there are >1k open ones

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

##### Test manual
* Change theme to dark
* Change the app-language to something other then the phone-languguage (e.g. German)
* Restart the app (so that the language is applied)
* Close the app completely
* Share a stream link to NewPipe (that you never watched before)
* the ask what to do dialog should come up
* click add to playlist

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Why don't you remove all `RouterActivity` themes and use the app's ones?

> Add to playlist is not implemented inside DownloadDialog ??? https://github.com/TeamNewPipe/NewPipe/pull/7194

What?

**Comment by litetex** [comment]
@Stypox 
> Why don't you remove all RouterActivity themes and use the app's ones?

The overlay hides/makes the app transparent (e.g. ``windowBackground``).
If I use the normal themes you see half of the app in the background which wouldn't be good in my opinion.

> > Add to playlist is not implemented inside DownloadDialog ??? https://github.com/TeamNewPipe/NewPipe/pull/7194
> What?

PR No2 is already work in progress to fix that 😆

File: app/src/main/java/org/schabi/newpipe/RouterActivity.java [hunk 1]
```diff
@@ -127,8 +128,10 @@ protected void onCreate(final Bundle savedInstanceState) {
             }
         }
 
+        ThemeHelper.setDayNightMode(this);
         setTheme(ThemeHelper.isLightThemeSelected(this)
                 ? R.style.RouterActivityThemeLight : R.style.RouterActivityThemeDark);
+        assureCorrectAppLanguage(this);
```
Comment (Redirion) [inline app/src/main/java/org/schabi/newpipe/RouterActivity.java:134]: just a small thing, but I prefer to not import static methods but call them in a static way: Localization.assureCorrectAppLanguage(this);

this way it is directly clear that you are calling a static method of an utility class instead of a local one

Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/RouterActivity.java]: doen

**Review by Redirion — APPROVED** [review]
your last commit message is misleading, as it actually still is a static method :D
