### PR TITLE
Fix crash when rotating device on unsupported channels

### LINKED ISSUE #6696: Crash when rotating device on unsupported channels
### Checklist
- [x] I am using the latest version - 0.21.15
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a channel which is not supported by NewPipe.
2. Rotate your device.
3. Observe app's behavior.

### Actual behavior
The app crashes.

### Expected behavior
The app displays the unsupported channel after device's rotation.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/74829229/126073585-ca479278-202b-4429-b4a5-5d8fd932bd23.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView org.schabi.newpipe.databinding.FragmentChannelBinding.errorContentNotSupported' on a null object reference
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.showContentNotSupported(ChannelFragment.java:510)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.handleResult(ChannelFragment.java:477)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.handleResult(ChannelFragment.java:67)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.doInitialLoadLogic(BaseListInfoFragment.java:115)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.onViewCreated(ChannelFragment.java:125)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Devices info

 - Android version/Custom ROM version: EMUI 10 + Android 11
 - Device model: Honor 9X + Pixel 4A (Android emulator)

### PR DESCRIPTION
**Pull request by GGAutomaton**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

See https://github.com/TeamNewPipe/NewPipe/issues/6696#issuecomment-1087753680

#### Fixes the following issue(s)

- Fixes #6696

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by GGAutomaton** [comment]
Reproduction steps:
1. Open a channel which is not supported by NewPipe, e.g., https://www.youtube.com/channel/UClYV6hHlupm_S_ObS1W-DYw
2. Rotate the screen

Also test rotating on a normal channel, the behavior is the same as before.

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java [hunk 1]
```diff
@@ -524,9 +529,15 @@ public void handleResult(@NonNull final ChannelInfo result) {
...
+        channelContentNotSupported = false;
         for (final Throwable throwable : result.getErrors()) {
             if (throwable instanceof ContentNotSupportedException) {
-                showContentNotSupported();
+                /*
+                channelBinding might not be initialized when handleResult() is called
+                (e.g. after rotating the screen, https://github.com/TeamNewPipe/NewPipe/issues/6696)
+                showContentNotSupported() will be called later
+                 */
+                channelContentNotSupported = true;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:540]: Uhm, and what if `onViewCreated` has already been called when this point is reached? Then `showContentNotSupported();` will never be called.

**Review by Stypox — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java (hunk 1 above)
Comment (GGAutomaton) [reply app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:540]: I haven't encountered this situation before.

Another possible solution for this issue is to swap the order of these two lines. But idk if `handleResult()` will be called before `onViewCreated()`.
https://github.com/TeamNewPipe/NewPipe/blob/173b6c3f00df02e64151ee642323205400d412f2/app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java#L130-L133

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:540]: I would rename `showContentNotSupported` to `showContentNotSupportedIfNeeded` and have it behave this way:
```
if (!channelContentNotSupported || channelBinding == null) {
    return;
}
// all of the core currently in showContentNotSupported
```
Then it could be called both in `onViewCreated` (without the need for the `if`) and here just under `hannelContentNotSupported = true;`. This way we can be sure.

**Comment by Stypox** [comment]
Btw, I don't think I am able to test properly. The crash on this channel is actually fixed, but `showContentNotSupported` should do something: [making views visible and showing kaomojis](https://github.com/TeamNewPipe/NewPipe/blob/2e771cd65ab1eff2cb090351a4083d1d129fe53a/app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java#L573-L576). Could you look into why nothing of that happens? Btw, there is no need to do that in this PR.

**Comment by GGAutomaton** [comment]
> Btw, I don't think I am able to test properly. The crash on this channel is actually fixed, but `showContentNotSupported` should do something: [making views visible and showing kaomojis](https://github.com/TeamNewPipe/NewPipe/blob/2e771cd65ab1eff2cb090351a4083d1d129fe53a/app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java#L573-L576). Could you look into why nothing of that happens? Btw, there is no need to do that in this PR. 

I haven't found the reason yet. I'll try again when I'm free.

**Comment by litetex** [comment]
@Stypox 

You have fallen victim to #6870 😉

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java [hunk 2]
```diff
@@ -77,6 +77,8 @@ public class ChannelFragment extends BaseListInfoFragment<StreamInfoItem, Channe
     private final CompositeDisposable disposables = new CompositeDisposable();
     private Disposable subscribeButtonMonitor;
 
+    private boolean channelContentNotSupported;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:80]:
```suggestion
    private boolean channelContentNotSupported = false;
```

**Review by Stypox — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java [hunk 3]
```diff
@@ -524,9 +527,11 @@ public void handleResult(@NonNull final ChannelInfo result) {
             playlistControlBinding.getRoot().setVisibility(View.GONE);
         }
 
+        channelContentNotSupported = false;
         for (final Throwable throwable : result.getErrors()) {
             if (throwable instanceof ContentNotSupportedException) {
-                showContentNotSupported();
+                channelContentNotSupported = true;
+                showContentNotSupportedIfNeeded();
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:534]:
```suggestion
                showContentNotSupportedIfNeeded();
                break;
```

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
I can confirm it works, then. Thank you! #6870 needs to be solved separately, but at least this crash is fixed.

**Comment by GGAutomaton** [comment]
> I can confirm it works, then. Thank you! #6870 needs to be solved separately, but at least this crash is fixed.
> 
> Btw, you got PR number 8192=2^13, feel honoured by that ;-)

The software engineering course of our college requires to contribute to the open source community.
I have also learned a lot from this project. Thank you for your warm help :)

**Comment by Stypox** [comment]
Great :-D
