### PR TITLE
Remove calls to getNextStream()

### LINKED ISSUE #3684: Autoplay next stream toggle only appears in YouTube
### Version

- 0.19.4

### Steps to reproduce the bug

1. Go to any PeerTube / SoundCloud stream
2. If you were on comments, switch to related streams

### Expected behavior

I can see this, and toggle autoplay next stream easily without needing to go in settings.
Screenshot_20200530-100325_NewPipe_1_1
### Actual behaviour

The toggle is not available

### PR DESCRIPTION
**Pull request by wb9688**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [x] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Fixes the following issue(s)
Fixes #3684

#### Relies on the following changes
TeamNewPipe/NewPipeExtractor#337

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java [hunk 1]
```diff
@@ -152,27 +152,28 @@ public static String cacheKeyOf(@NonNull final StreamInfo info,
...
         }
 
-        List<StreamInfoItem> autoQueueItems = new ArrayList<>();
+        if (relatedItems.get(0) != null && relatedItems.get(0) instanceof StreamInfoItem
+                && !urls.contains(relatedItems.get(0).getUrl())) {
+            return getAutoQueuedSinglePlayQueue((StreamInfoItem) relatedItems.get(0));
+        }
+
+        final List<StreamInfoItem> autoQueueItems = new ArrayList<>();
         for (final InfoItem item : info.getRelatedStreams()) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java:171]:
```suggestion
        for (final InfoItem item : relatedItems) {
```

File: app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedVideosFragment.java [hunk 2]
```diff
@@ -81,22 +72,18 @@ public void onDestroy() {
...
+            final SharedPreferences pref = PreferenceManager
+                    .getDefaultSharedPreferences(getContext());
+            final boolean autoplay = pref.getBoolean(getString(R.string.auto_queue_key), false);
+            autoplaySwitch.setChecked(autoplay);
+            autoplaySwitch.setOnCheckedChangeListener((compoundButton, b) ->
                     PreferenceManager.getDefaultSharedPreferences(getContext()).edit()
-                            .putBoolean(getString(R.string.auto_queue_key), b).apply();
-                }
-            });
+                    .putBoolean(getString(R.string.auto_queue_key), b).apply());
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedVideosFragment.java:86]: I think this indentation is wrong
