### PR TITLE
#5263: Allow the user to pause while a video is buffering

### LINKED ISSUE #5263: Can't pause video while buffering
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

0. Use an unstable Internet connection
1. Open any video
2. Wait some time for the video to go buffering
3. Tap on the screen to access the pause button and tap on it

### Actual behaviour

Pause button doesn't work and video continues to play the moment buffering is done.

### Expected behavior

Video is paused, so you can wait until more video chunks are loaded.

### Device info

 - Android version/Custom ROM version: 6.0.1
 - Device model: Xiaomi Redmi 4

### PR DESCRIPTION
**Pull request by Douile**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Allow the user to pause/unpause while a video is buffering
  - Check whether the `playWhenReady` is true instead of `isPlaying`: `isPlaying` returns false if the video is buffering

#### Fixes the following issue(s)

- fixes #5263 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by opusforlife2** [comment]
Yay! Much needed usability fix.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 1]
```diff
@@ -4012,6 +4012,10 @@ public boolean isPlaying() {
         return !exoPlayerIsNull() && simpleExoPlayer.isPlaying();
     }
 
+    public boolean isPlayingWhenReady() {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:4015]: Rename this to `getPlayWhenReady` and check if it can be used in other places (i.e. in other places where currently `simpleExoPlayer.getPlayWhenReady()` is being used.
```suggestion
    public boolean getPlayWhenReady() {
```

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you!
Almost there ;-)

**Comment by Douile** [comment]
These changes seem to make 
https://github.com/Douile/NewPipe/blob/963a7609f1681ec4942a2a3e560db82f280fc0e3/app/src/main/java/org/schabi/newpipe/player/Player.java#L709-L713

redundant, should I replace this snippit with playPause? I'm not sure why getPlayWhenReady was being used here but not in playPause

**Comment by Stypox** [comment]
@Douile nice catch. Replace every instance of `if (getPlayWhenReady()) play(); else pause();` with `playPause()`, thanks

**Comment by Douile** [comment]
I think that's the only one.

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
@Douile thank you :-D

**Comment by litetex** [comment]
ℹ This PR very likely caused https://github.com/TeamNewPipe/NewPipe/issues/6179, see also https://github.com/TeamNewPipe/NewPipe/issues/6179#issuecomment-837278251
