### PR TITLE
Try to recover pending download missions when possible

### LINKED ISSUE #7059: Unfinished Downloads Disappearing From Downloads List
### Checklist 

- [x] I am using the latest version - x.21.9 

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 

- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md. 

- [x] This issue contains only one bug. I will open one issue for every bug report I want to file. 

### Steps to reproduce the bug 

1. Start a video download
2. Observe the item in progress in the "Downloads" list.
3. Close/stop the app in any way
4. Open the app
5. Open the "Downloads" list, see the item is gone

### Actual behavior 

Since at least the most recent update, I have noticed that partially/non-completed download items are disappearing from the downloads list if the app is an any way stopped or interrupted - manually closed, times out in the background, etc - before they are done. In all previous versions, if you were trying to download something, and you closed the app before it was done I've been regardless as to whether you manually post it or not I - when you opened it again, it would still be there in the downloads list and you could restart/re-queue it. (Note: it just remove the download listing, The partially downloaded file is still in the folder where it was started to save)

### Expected behavior 

All dowload items, finished and incomplete, should be in the download tab until manually removed

### Logs 

No logs 

### Device info 

- Android version/Custom ROM version: Android 10 

- Device model: Galaxy S9/SM-G960U

### LINKED ISSUE #9557: List of downloads refresh after turning on settings to "interrupt on metered networks"
This also occurs for me in 0.24.1:

1. download a file
2. pause it
3. while downloading, go to Settings → Download and turn on "interrupt on metered networks"
4. go to list of “Downloads”

(it may occure also while downloading isn't paused)

Behavior:
list of downloads refreshes without the paused download

_Originally posted by @maninthemiddle01 in https://github.com/TeamNewPipe/NewPipe/issues/7059#issuecomment-1356147259_

### LINKED ISSUE #10527: Download queue deletes when switching to battery save mode
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Hello, 

I found out that download queue clears itself when switching to power saving mode.

How to reproduce:
Go and download anything (I used tp download ca. 7 MB 360p video). 
Since I used mobile data and slow internet (around 10 kB/s) I had to start download manually.

### Expected behavior

To at least keep the download queue but pause the download or even to keep downloading. 

### Actual behavior

At some point my phone switched to power save mode (when falling under 20% battery) and when I opened the app, there were only previous downloads and none from download queue. The file itself was still present but incomplete. 

I also noticed that the app tends to throw an error and pauses downloading when with slow speeds, but starting it again solves the issue.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

android 13 / calyxos 4.14.0

### Affected device model

Google pixel 4a

### Additional information

This is the explained battery saver from settings:
Battery saver turns on dark mode, limits or turns off background activity, certain visual effects, some features and some network connections.

### LINKED ISSUE #11076: Pausing download makes download unrecoverable
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

27

### Steps to reproduce the bug

1. Initiate download 
2. Pause download
3. Do other stuff like use a web browser
4. Try to resume download

### Expected behavior

NewPipe will delete the paused download if it gets swapped out of ram. The file remains, but NewPipe can only overwite it rather than resume. This doesn't appear to be a problem if the download is interrupted. In this case. It will change the status of the download in the notifications and will always allow the download to be resumed. The issue is if you pause the download. 

Current work-arounds:
1. Disconnect data to cause the download interrupted error which works unlike pausing the download 
2. Use something else like yt-dlp (my current solution)

### Actual behavior

_No response_

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

_No response_

### Affected device model

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by whistlingwoods**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR changes the app behavior where it considers ERROR_PROGRESS_LOST as invalid storage, however where it is possible to recover the pending download missions, it tries for that.

#### Fixes the following issue(s)
Fix app can't resume paused downloads in certain following situations:
- Fixes #11076
- Fixes #7059 (a duplicate but most visited issue since it [broke](https://github.com/TeamNewPipe/NewPipe/pull/6721).)
- May Fix #9557
- May Fix #10527 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ShareASmile** [comment]
Steps to follow for rigorously testing the fix under different conditions:

1. Try to download a large file under unstable network conditions e.g. pause it  while you are leaving wifi area to save cellular data and try to resume the download when wifi becomes available again after some time.

2. While downloading keep app in background, pause it and open other heavy ram usage apps to boot it out of memory then reopen app to check if video is still there in downloads list and whether it resumes the download when started again manually from downloads list.

**Comment by ABJ4403** [comment]
> 2\. While downloading keep app in background, pause it and open other heavy ram usage apps to boot it out of memory then reopen app to check if video is still there in downloads list and whether it resumes the download when started again manually from downloads list.

Does `am kill-all` count? Bcz i'd rather do that, tho i have 2nd device that has 2GB RAM and filled up so quick when i load up a game, so i could try thatvas well

File: app/src/main/java/us/shandian/giga/service/DownloadManager.java [hunk 1]
```diff
@@ -582,8 +610,16 @@ private ArrayList<Object> getSpecialItems() {
...
-                // hide missions (if required)
-                remove.removeIf(mission -> pending.remove(mission) || finished.remove(mission));
+                // Don't hide recoverable missions
+                remove.removeIf(mission -> {
+                    if (mission instanceof DownloadMission) {
+                        DownloadMission dm = (DownloadMission) mission;
+                        if (canRecoverMission(dm)) {
+                            return false; // Don't remove recoverable missions
+                        }
+                    }
```
Comment (Isira-Seneviratne) [inline app/src/main/java/us/shandian/giga/service/DownloadManager.java]:
```suggestion
                    if (mission instanceof DownloadMission dm && canRecoverMission(dm)) {
                        return false; // Don't remove recoverable missions
                    }
```

File: app/src/main/java/us/shandian/giga/service/DownloadManager.java [hunk 2]
```diff
@@ -149,12 +151,31 @@ private void loadPendingMissions(Context ctx) {
...
+                setFinished(mis);
+                //noinspection ResultOfMethodCallIgnored
+                sub.delete();
+                continue;
+            }
+
+            // DON'T delete missions with storage issues - try to recover them
+            if (mis.hasInvalidStorage() && mis.errCode != ERROR_PROGRESS_LOST) {
+                // Only delete if it's truly unrecoverable (not just progress lost)
+                if (mis.storage == null && mis.errCode != ERROR_PROGRESS_LOST) {
```
Comment (Isira-Seneviratne) [inline app/src/main/java/us/shandian/giga/service/DownloadManager.java]:
```suggestion
                if (mis.storage == null) {
```

**Review by Isira-Seneviratne — CHANGES_REQUESTED** [review]

File: app/src/main/java/us/shandian/giga/service/DownloadManager.java (hunk 1 above)
Comment (whistlingwoods) [reply app/src/main/java/us/shandian/giga/service/DownloadManager.java]: applied suggestions

File: app/src/main/java/us/shandian/giga/service/DownloadManager.java (hunk 2 above)
Comment (whistlingwoods) [reply app/src/main/java/us/shandian/giga/service/DownloadManager.java]: done

**Review by Isira-Seneviratne — APPROVED** [review]
The changes look good to me as well.
