### PR TITLE
Fix download dialog freeze

### LINKED ISSUE #3609: Pressing Download button in PeerTube mode, halts NewPipe entirely [needs to be killed manually][used to work]
Switching to any instance of peertube (I'm using for example https://peertube.social), 
clicking on the download button halts the entire application. 

GIF-200518_003950
and it must be killed. 
Screenshot_20200518-002933_V Recorder 
this is the OS dialog saying the app is not responding. 

b.t.w. Its not related to way the content actually downloads (standard/storage access framework) since it happens in both ways the download is configured. Probably earlier in the resource fetching cycle.

It used to work fine two versions ago.

### PR DESCRIPTION
**Pull request by wb9688**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
I also forgot to remove some Checkstyle hack that's not needed anymore now that they handle it properly with Gradle when upgrading its version, so I removed that as well.

#### Fixes the following issue(s)
Fixes #3609

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/util/ListHelper.java [hunk 1]
```diff
@@ -293,30 +292,28 @@ static int getHighestQualityAudioIndex(final MediaFormat format,
...
+     * Format will be ignored if it yields no results.
      *
      * @param format       The target format type or null if it doesn't matter
      * @param audioStreams List of audio streams
-     * @return Index of audio stream that can produce the most compact results or -1 if not found
+     * @return Index of audio stream that produces the most compact results or -1 if not found
      */
-    static int getMostCompactAudioIndex(final MediaFormat format,
-                                        final List<AudioStream> audioStreams) {
+    static int getMostCompactAudioIndex(MediaFormat format, final List<AudioStream> audioStreams) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ListHelper.java:309]:
```suggestion
    static int getMostCompactAudioIndex(@Nullable MediaFormat format, final List<AudioStream> audioStreams) {
```

File: app/src/main/java/org/schabi/newpipe/util/ListHelper.java [hunk 2]
```diff
@@ -267,23 +267,22 @@ private static void sortStreamList(final List<VideoStream> videoStreams,
...
      *
-     * @param format       the format to look for
-     * @param audioStreams list the audio streams
-     * @return index of the audio with the highest average bitrate of the default format
+     * @param format       The target format type or null if it doesn't matter
+     * @param audioStreams List of audio streams
+     * @return Index of audio stream that produces the most compact results or -1 if not found
      */
-    static int getHighestQualityAudioIndex(final MediaFormat format,
+    static int getHighestQualityAudioIndex(MediaFormat format,
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ListHelper.java:277]:
```suggestion
    static int getHighestQualityAudioIndex(@Nullable MediaFormat format,
```
