### PR TITLE
Disable media tunneling by default on known unsupported devices

### LINKED ISSUE #8829: Android TV - No video/black screen
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.23.2

### Steps to reproduce the bug

1. Select a video and play it

### Expected behavior

The video should display in the mini-screen and in fullscreen

### Actual behavior

The video is completely black but the audio can be heard.

### Screenshots/Screen recordings

See https://github.com/TeamNewPipe/NewPipe/issues/4842
Exactly the same symptom, but it occurs every video instead of just "next video" 

### Logs

[logcat.txt](https://github.com/TeamNewPipe/NewPipe/files/9367149/logcat.txt)

### Affected Android/Custom ROM version

Android TV 11

### Affected device model

Tmobile TVision HUB v2

### Additional information

* The issue does not occur when video is set to `3gp` format and displays correctly.
* The issue occurred in previous versions of NewPipe occasionally, but now it happens for every video.

### LINKED ISSUE #9023: Crash when going fullscreen (especially Android TVs)
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.0

### Steps to reproduce the bug

1.   Start any video and try to switch to fullscreen mode results in an error message (see screenshot).
2.   No chance to continue the video, 'cause only an remote control is attached, but got no focus to the play button. Only chance is going back and restart the video which brings us back 1.

### Expected behavior

entering fullscreen mode

### Actual behavior

see attached [screenshot]

### Screenshots/Screen recordings

Screenshot 2022-09-25 210614

### Logs

_No response_

### Affected Android/Custom ROM version

AndroidTV 9 and FireTV

### Affected device model

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
In #8875 a setting to disable media tunneling was added. However, the info on devices which do not support media tunneling was removed. That info is re-added and used to disable media tunneling on those devices by default.

Disabling media tunneling seems to also fix the full screen enter/exit bug on Android TVs (#9023)

##### New models added:
- Sony Bravia VH1 (`BRAVIA_VH1`)
- Sony Bravia VH2 (`BRAVIA_VH2`), e.g. model A90J
- Sony Bravia Android TV platform 2 (`BRAVIA_ATV2`)
- Sony Bravia Android TV platform 3 4K (`BRAVIA_ATV3_4K`)
- Phillips 4K (O)LED TV (`PH7M_EU_5596`)
- Panasonic 4KTV-JUP (`TX_50JXW834`)
- Bouygtel4K (Bouygues Telecom Bbox 4K) (`HMB9213NW`)

##### Other changes: 
- Added info to ExoPlayer settings explaining that media tunneling was disabled automatically.  
<details><summary>Media tunneling setting screenshot</summary>

grafik

</details>

#### Fixes the following issue(s)
- Fixes https://github.com/TeamNewPipe/NewPipe/pull/8875#discussion_r1059742968
- Fixes #8829
- Fixes #9023 

#### ToDo
- [ ] Rework applying device detection results and restoring that info correctly from a backup.

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
I wanted to wait on feedback from #8829 and #10112 to include more devices, however there is no response.

**Comment by peat80** [comment]
I believe the tv runs android tv 10.

**Comment by TobiGr** [comment]
@peat80 Please test out the APK (see PR description). I hope that everything works as expected. If it does not, please go to the settings > debug and use on of the options which crash the app and show the error screen. The crash info does contain information on your Android version. If it is Android 10 / SDK level 29, go into the video & audio settings > ExoPlayer settings and check whether the option "Disable media tunneling" is enabled. If it is not enabled, enable it and try to play a video.

**Comment by peat80** [comment]
Back home now. Can confirm tv indeed runs on android 10. The downloded artifact apk has media tunneling disabled per default now and works. 😀👌

**Comment by peat80** [comment]
BRAVIA_VH1 should probably also be added.

There was a closed PR for that:

#9425

**Review by AnantMishra01 — APPROVED** [review]

**Comment by pihug12** [comment]
I don't suffer the "no video / black screen" problem, but disabling "media tunneling" with [this APK](https://github.com/TeamNewPipe/NewPipe/issues/8829#issuecomment-1562939302) solves the fullscreen problem for me.

* Model: Bouygtel4K (_Bouygues Telecom Bbox 4K_)
* Android TV 9 (build "Californie")
* Device ID: HMB9213NW

I don't know if the device should be added to this list or not?

**Comment by TobiGr** [comment]
@pihug12 I disabled it in case there are other people using the same device.

File: app/src/main/java/org/schabi/newpipe/settings/ExoPlayerSettingsFragment.java [hunk 1]
```diff
@@ -1,14 +1,45 @@
...
+                .getDefaultSharedPreferences(requireContext());
+        final boolean mediaTunnelingAutomaticallyEnabled =
+                prefs.getInt(disableMediaTunnelingAutomaticallyKey, -1) == 1;
+        final String summaryText = getString(R.string.disable_media_tunneling_summary);
+        disableMediaTunnelingPref.setSummary(mediaTunnelingAutomaticallyEnabled
+                ? summaryText + getString(R.string.disable_media_tunneling_automatic_info)
+                : summaryText);
+
+        disableMediaTunnelingPref.setOnPreferenceChangeListener((Preference p, Object enabled) -> {
+                    if (((Boolean) enabled).equals(Boolean.FALSE)) {
```
Comment (AudricV) [inline app/src/main/java/org/schabi/newpipe/settings/ExoPlayerSettingsFragment.java:34]: I would swap the condition to prevent any `NullPointerException`:

```suggestion
                    if (Boolean.FALSE.equals(((Boolean) enabled))) {
```

**Review by AudricV — CHANGES_REQUESTED** [review]
Your changes look mostly good to me, however, I think we should use a complete different approach instead of DB migrations, by using an app preference containing with which version of the app the media tunneling check has been ran and run the check with each NewPipe update.

With this value, we can check if the version matches the current one installed + use some logic with the two preferences storing whether the device has been whitelisted automatically and media tunneling has been enabled by user, in order to know if we need to disable automatically media tunneling or not.

This approach should make maintenance less hard than doing a lot of database migrations every time we add a new device.

Could you also format better and improve your method Javadocs? For instance, you are using line returns to separate titles and descriptions, but they are ignored, so you should also use paragraph elements in this case.

**Comment by Ang-le** [comment]
Device ID: BRAVIA_ATV2   
I just tried it and it worked for me in full screen Disable media tunneling.

Thank you

**Comment by TobiGr** [comment]
I added two new devices: `BRAVIA_ATV2` and `BRAVIA_ATV3_4K`.
@AudricV I'll address your review during the next week. Thank you for clarifying what you meant by using preferences.

File: app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java [hunk 2]
```diff
@@ -76,6 +76,14 @@ public static void initSettings(final Context context) {
 
         saveDefaultVideoDownloadDirectory(context);
         saveDefaultAudioDownloadDirectory(context);
+
+
+        final int lastMediaTunnelingUpdate = PreferenceManager.getDefaultSharedPreferences(context)
+                .getInt(context.getString(R.string.media_tunneling_device_blacklist_version), 0);
+        if (Boolean.TRUE.equals(isFirstRun) || DeviceUtils.MEDIA_TUNNELING_DEVICE_BLACKLIST_VERSION
+                != lastMediaTunnelingUpdate) {
+            setMediaTunneling(context);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java:85]: Shouldn't you also check whether it was turned off manually before re-enabling tunneling?

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java]: done

File: app/src/main/java/org/schabi/newpipe/settings/ExoPlayerSettingsFragment.java [hunk 3]
```diff
@@ -1,14 +1,45 @@
...
+        final SwitchPreferenceCompat disableMediaTunnelingPref =
+                (SwitchPreferenceCompat) requirePreference(R.string.disable_media_tunneling_key);
+        final SharedPreferences prefs = PreferenceManager
+                .getDefaultSharedPreferences(requireContext());
+        final boolean mediaTunnelingAutomaticallyEnabled =
+                prefs.getInt(disableMediaTunnelingAutomaticallyKey, -1) == 1;
+        final String summaryText = getString(R.string.disable_media_tunneling_summary);
+        disableMediaTunnelingPref.setSummary(mediaTunnelingAutomaticallyEnabled
+                ? summaryText + getString(R.string.disable_media_tunneling_automatic_info)
+                : summaryText);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/settings/ExoPlayerSettingsFragment.java:31]:
```suggestion
        final String disabledMediaTunnelingAutomaticallyKey =
                getString(R.string.disabled_media_tunneling_automatically_key);
        final SwitchPreferenceCompat disableMediaTunnelingPref =
                (SwitchPreferenceCompat) requirePreference(R.string.disable_media_tunneling_key);
        final SharedPreferences prefs = PreferenceManager
                .getDefaultSharedPreferences(requireContext());
        final boolean mediaTunnelingAutomaticallyDisabled =
                prefs.getInt(disabledMediaTunnelingAutomaticallyKey, -1) == 1;
        final String summaryText = getString(R.string.disable_media_tunneling_summary);
        disableMediaTunnelingPref.setSummary(mediaTunnelingAutomaticallyDisabled
                ? summaryText + " " + getString(R.string.disable_media_tunneling_automatic_info)
                : summaryText);
```

File: app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java [hunk 4]
```diff
@@ -152,4 +154,49 @@ public static boolean showRemoteSearchSuggestions(final Context context,
...
+
+        final int lastMediaTunnelingUpdate = prefs.getInt(blacklistVersionKey, 0);
+        final boolean wasDeviceBlacklistUpdated =
+                DeviceUtils.MEDIA_TUNNELING_DEVICE_BLACKLIST_VERSION != lastMediaTunnelingUpdate;
+        final boolean wasMediaTunnelingEnabledByUser =
+                prefs.getInt(disabledTunnelingAutomaticallyKey, -1) == 0
+                        && !prefs.getBoolean(disabledTunnelingKey, false);
+
+        if (Boolean.TRUE.equals(isFirstRun)
+                || wasDeviceBlacklistUpdated && !wasMediaTunnelingEnabledByUser) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java:175]:
```suggestion
                || (wasDeviceBlacklistUpdated && !wasMediaTunnelingEnabledByUser)) {
```

**Review by Stypox — CHANGES_REQUESTED** [review]
I think a simple list preference with "Tunneling on, tunneling off, automatic" would have been simpler, since with the current code once you manually disable tunneling there is no way to go back to automatic mode. I think we can postpone this to a small PR after the release.

**Review by Stypox — APPROVED** [review]

**Comment by disconnect5852** [comment]
Still not works, on xiaomi mi tv. I open a video, it plays, switch to full screen= error. Then always error until i reboot the device.
Model: MITV-AYFRO
Kernel version: 5.4.210-android12-9-g041469a404b2-ab1407 https://github.com/TeamNewPipe/NewPipe/issues/1 Thu Jun 15 21:14:30 CST 2023
Android TV OS-build: RTTO.211222.001.1407 release-keys

**Comment by TobiGr** [comment]
Did you disable media tunneling in the ExoPlayer settings?
