### PR TITLE
Fix null pointer exception when displaying SearchFragment

### LINKED ISSUE #6522: Crash when pressing search button
### Checklist

- [x] I am using the latest version - 74ad488f4ad2459d38c2141f824534b6aff8302f 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Similar to #6231 but different null pointer exception

`0.` Build the app from `dev` branch

1. Open app
2. Press search button

### Actual behaviour

App crashes (ui error)

### Expected behavior

App doesn't crash (no null pointer exception)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.extractor.linkhandler.SearchQueryHandlerFactory org.schabi.newpipe.extractor.StreamingService.getSearchQHFactory()' on a null object reference
	at org.schabi.newpipe.fragments.list.search.SearchFragment.onCreateOptionsMenu(SearchFragment.java:430)
	at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:3100)
	at androidx.fragment.app.FragmentManager.dispatchCreateOptionsMenu(FragmentManager.java:3181)
	at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:391)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:288)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by Douile**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Fixes null pointer exception when starting SearchFragment

It seems due to #6394 updating the FragmentX library there was a
change to the order of lifecycle calls, as such onResume() was no longer
before onCreateOptionsMenu() creating a null pointer exception when
using service in onCreateOptionsMenu() as it is only set in onResume().

By moving the initialization of service to onStart() which still happens
before onCreateOptionsMenu() this crash can be avoided. This commit also
adds a check for a null service to prevent future crashes for similar
issues.

#### Fixes the following issue(s)

- Fixes #6522

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Wonderful, thanks a lot!

**Review by B0pol — APPROVED** [review]

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java [hunk 1]
```diff
@@ -250,13 +269,6 @@ public void onResume() {
         }
         super.onResume();
 
-        try {
-            service = NewPipe.getService(serviceId);
-        } catch (final Exception e) {
-            ErrorActivity.reportUiErrorInSnackbar(this,
-                    "Getting service for id " + serviceId, e);
-        }
-
```
Comment (B0pol) [inline app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:259]: I don't understand this. onResume() is called when you change service? then it should be updated onResume()? anyway search & switching service works

Comment (TacoTheDank) [reply app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:259]: @B0pol Did you figure something out here to merge this? It seems you had a question that wasn't resolved 🤔

Comment (B0pol) [reply app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:259]: > anyway search & switching service works
