### PR TITLE
Replace UniversalImageLoader with Picasso

### LINKED ISSUE #4638: System UI keeps stopping [Image Loader issue]
### Checklist

- [x] I am using the latest version - 0.20.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Search the concerned video like 'Hello World'.
2. Enqueue in the background
3. Open the video. 
(Both the cases 2. and 3. produce the similar behaviour)

### Actual behaviour
The video or audio(when playing in background) starts playing, the screen starts flickering , in the sense that display gets on and off , flickers for some time displaying the messege -- 'System UI keeps stopping' (giving two options -- app info or close app). The app gets closed for the latter option, but if pressed anywhere else on the screen the video plays continuosly with audio, screen flickering for some time and then phone gets restarted.

### Expected behavior

The video to be played till the end.

### Screenshots/Screen recordings

Screenshot_20201025-053028

### Logs
 None

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Motorola One Power (P30 Note)

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR replaces the outdated [Android-Universal-Image-Loader](https://github.com/nostra13/Android-Universal-Image-Loader) (which has not had any new release in the last 6 years) with the more stable and updated [Picasso](https://github.com/square/picasso). This hopefully fixes a [nasty unfixed issue](https://github.com/nostra13/Android-Universal-Image-Loader/issues/908) in Android-Universal-Image-Loader that was causing #4638. Also, the loading seems smoother to me, and retrieving images from memory cache is now instant, instead of taking a couple of milliseconds (try scrolling fast up and down after all thumbnails have been loaded).
I also added a switch in the *debug* settings to enable [indicators](https://square.github.io/picasso/static/debug.png).

#### Fixes the following issue(s)
Fixes #4638

#### APK testing 
@gulachev @k3a @Sekitan @UserX404 @nonremittal @arielshulman @dboydor @pauseee @astatine (taken from #4638)
Could you test [this APK from the CI](https://github.com/TeamNewPipe/NewPipe/suites/2358978908/artifacts/49936658) and see if it fixes the issue? Thank you ;-)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by arielshulman** [comment]
Hey @Stypox, thanks for your work 🙏
Just ran a first try with known videos which crashed the phone and unfortunetly the error still occurs. 
How can I help?

**Comment by Stypox** [comment]
Oh no... why does it still crash? Maybe the bitmap downloaded from the website itself is broken? Could you provide me the video url?

**Comment by arielshulman** [comment]
[This video](https://www.youtube.com/watch?v=MCIaj-oLi28) is one of the rebellious videos.

**Comment by Stypox** [comment]
Mmmh, this is really strange. I tried copying the thumbnail and returning the copy and I got this strange error... What does it mean?!?
```
W/e.debug.picass: Core platform API violation: Ljava/nio/Buffer;->address:J from Landroid/graphics/Bitmap; using JNI
    Core platform API violation: Ljava/nio/NIOAccess;->getBaseArrayOffset(Ljava/nio/Buffer;)I from Landroid/graphics/Bitmap; using JNI
    Core platform API violation: Ljava/nio/NIOAccess;->getBaseArray(Ljava/nio/Buffer;)Ljava/lang/Object; from Landroid/graphics/Bitmap; using JNI
```

**Comment by Stypox** [comment]
@arielshulman could you test this APK? I implemented what you did in the issue, i.e. resizing to `width - 1` to force the creation of a new thumbnail. For some reason calling `.copy()` would cause the attached completion listeners to not be called and the error above to appear... What's wrong with these Bitmaps?!?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6218052/app-debug.zip)

Oh, btw, some way or another I was able to cause a native stacktrace even on my phone, but this is probably just caused by me recycling the wrong thing (` 'Error, cannot access an invalid/free'd bitmap here!'`), and fortunately the phone didn't crash:
```
2021-03-28 22:11:40.097 16307-16307/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2021-03-28 22:11:40.098 16307-16307/? A/DEBUG: Revision: '0'
2021-03-28 22:11:40.098 16307-16307/? A/DEBUG: ABI: 'arm64'
2021-03-28 22:11:40.101 16307-16307/? A/DEBUG: Timestamp: 2021-03-28 22:11:40+0200
2021-03-28 22:11:40.101 16307-16307/? A/DEBUG: pid: 16092, tid: 16185, name: 8/hqdefault.jpg  >>> org.schabi.newpipe.debug.picasso <<<
2021-03-28 22:11:40.101 16307-16307/? A/DEBUG: uid: 10257
2021-03-28 22:11:40.101 16307-16307/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2021-03-28 22:11:40.101 16307-16307/? A/DEBUG: Abort message: 'Error, cannot access an invalid/free'd bitmap here!'
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x0  0000000000000000  x1  0000000000003f39  x2  0000000000000006  x3  0000007c1b517750
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x4  0000800000000000  x5  0000800000000000  x6  0000800000000000  x7  0000000000800000
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x8  00000000000000f0  x9  0dc63cdfdf89df00  x10 0000000000000001  x11 0000000000000000
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000002  x15 000024f81cbd8448
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x16 0000007d2b49e8c0  x17 0000007d2b47c3b0  x18 0000007c1ab48000  x19 0000000000003edc
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x20 0000000000003f39  x21 00000000ffffffff  x22 0000007c1b51c020  x23 0000007ca0980b9c
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x24 000000000000000c  x25 0000007c1b51c020  x26 0000007c9a401cb0  x27 0000000000000003
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     x28 0000007c1b517e00  x29 0000007c1b5177f0
2021-03-28 22:11:40.102 16307-16307/? A/DEBUG:     sp  0000007c1b517730  lr  0000007d2b42ff48  pc  0000007d2b42ff74
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG: backtrace:
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG:       #00 pc 0000000000081f74  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: bf14cf7a62d1f91755beddd4a937354d)
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG:       #01 pc 00000000000089f8  /system/lib64/liblog.so (__android_log_assert+324) (BuildId: abc9e34f45037deab475aefb9194f1bd)
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG:       #02 pc 0000000000153460  /system/lib64/libandroid_runtime.so (Bitmap_copyPixelsToBuffer(_JNIEnv*, _jobject*, long, _jobject*)+216) (BuildId: f56bc1fc11ff5978e2f1a57f7348acd4)
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG:       #03 pc 000000000013f350  /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG:       #04 pc 00000000001365b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.842 16307-16307/? A/DEBUG:       #05 pc 000000000014508c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #06 pc 00000000002df0d4  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #07 pc 00000000002da3b4  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #08 pc 00000000002e7910  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+14964) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #09 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #10 pc 00000000003679d4  /system/framework/framework.jar (android.graphics.Bitmap.copyPixelsToBuffer)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #11 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #12 pc 0000000000588e8c  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #13 pc 000000000013f468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.843 16307-16307/? A/DEBUG:       #14 pc 0000000000136334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #15 pc 000000000014506c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #16 pc 00000000004a9110  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #17 pc 00000000004aa1a4  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #18 pc 000000000039334c  /apex/com.android.runtime/lib64/libart.so (art::JNI::CallVoidMethodA(_JNIEnv*, _jobject*, _jmethodID*, jvalue const*)+624) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #19 pc 00000000003693e0  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodA(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, jvalue const*, art::Primitive::Type, art::InvokeType)+2000) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #20 pc 000000000002eb50  /apex/com.android.runtime/lib64/libjdwp.so (invoker_doInvoke+2652) (BuildId: ab27d72150946bc52c7d9ee359e337b8)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #21 pc 000000000002b254  /apex/com.android.runtime/lib64/libjdwp.so (reportEvents+592) (BuildId: ab27d72150946bc52c7d9ee359e337b8)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #22 pc 000000000002acd0  /apex/com.android.runtime/lib64/libjdwp.so (event_callback+1000) (BuildId: ab27d72150946bc52c7d9ee359e337b8)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #23 pc 00000000000277f4  /apex/com.android.runtime/lib64/libjdwp.so (cbBreakpoint+360) (BuildId: ab27d72150946bc52c7d9ee359e337b8)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #24 pc 0000000000035ce8  /apex/com.android.runtime/lib64/libopenjdkjvmti.so (openjdkjvmti::JvmtiMethodTraceListener::DexPcMoved(art::Thread*, art::Handle<art::mirror::Object>, art::ArtMethod*, unsigned int)+4080) (BuildId: 8a8b387bc5b8fca176e32439a3d915ba)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #25 pc 00000000002a7fc8  /apex/com.android.runtime/lib64/libart.so (art::instrumentation::Instrumentation::DexPcMovedEventImpl(art::Thread*, art::ObjPtr<art::mirror::Object>, art::ArtMethod*, unsigned int) const+172) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #26 pc 00000000002ec1f8  /apex/com.android.runtime/lib64/libart.so (art::interpreter::InstructionHandler<true, true>::DoDexPcMoveEvent(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame const&, unsigned int, art::instrumentation::Instrumentation const*, art::JValue*)+236) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.844 16307-16307/? A/DEBUG:       #27 pc 00000000002e91ec  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+21328) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #28 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #29 pc 00000000000f38f8  [anon:dalvik-classes2.dex extracted in memory from /data/app/org.schabi.newpipe.debug.picasso-XWyCN2bUdEceLKvtxE2aBg==/base.apk!classes2.dex] (org.schabi.newpipe.player.Player$5.transform)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #30 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #31 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #32 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #33 pc 00000000002e8d38  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+20124) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #34 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #35 pc 0000000000139bd0  [anon:dalvik-classes3.dex extracted in memory from /data/app/org.schabi.newpipe.debug.picasso-XWyCN2bUdEceLKvtxE2aBg==/base.apk!classes3.dex] (com.squareup.picasso.BitmapHunter.applyCustomTransformations)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #36 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #37 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #38 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.845 16307-16307/? A/DEBUG:       #39 pc 00000000002e7910  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+14964) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #40 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #41 pc 0000000000139e20  [anon:dalvik-classes3.dex extracted in memory from /data/app/org.schabi.newpipe.debug.picasso-XWyCN2bUdEceLKvtxE2aBg==/base.apk!classes3.dex] (com.squareup.picasso.BitmapHunter.hunt)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #42 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #43 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #44 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #45 pc 00000000002e8bd4  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+19768) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #46 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #47 pc 000000000013ac08  [anon:dalvik-classes3.dex extracted in memory from /data/app/org.schabi.newpipe.debug.picasso-XWyCN2bUdEceLKvtxE2aBg==/base.apk!classes3.dex] (com.squareup.picasso.BitmapHunter.run)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #48 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #49 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #50 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #51 pc 00000000002e8d38  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+20124) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.846 16307-16307/? A/DEBUG:       #52 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #53 pc 00000000001dd19c  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.Executors$RunnableAdapter.call)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #54 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #55 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #56 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #57 pc 00000000002e8d38  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+20124) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #58 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #59 pc 00000000001e2b10  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.FutureTask.run)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #60 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #61 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #62 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #63 pc 00000000002e8d38  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+20124) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #64 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #65 pc 00000000001ed894  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor.runWorker)
2021-03-28 22:11:40.847 16307-16307/? A/DEBUG:       #66 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #67 pc 00000000002b5b0c  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #68 pc 00000000002da398  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #69 pc 00000000002e8bd4  /apex/com.android.runtime/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false, false>(art::interpreter::SwitchImplContext*)+19768) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #70 pc 0000000000141bd8  /apex/com.android.runtime/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #71 pc 00000000001ec6c8  /apex/com.android.runtime/javalib/core-oj.jar (java.util.concurrent.ThreadPoolExecutor$Worker.run)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #72 pc 00000000002afe1c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1271440803783865717+492) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #73 pc 0000000000588e8c  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #74 pc 000000000013f468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #75 pc 000000000013f65c  /apex/com.android.runtime/lib64/libart.so (art_quick_instrumentation_entry+252) (BuildId: 77524e83b39d990eaaf7c2af505c5eae)
2021-03-28 22:11:40.848 16307-16307/? A/DEBUG:       #76 pc 0dc63cdfdf89df00  <unknown>
```

**Comment by arielshulman** [comment]
> Mmmh, this is really strange. I tried copying the thumbnail and returning the copy and I got this strange error... What does it mean?!?
> 
> ```
> W/e.debug.picass: Core platform API violation: Ljava/nio/Buffer;->address:J from Landroid/graphics/Bitmap; using JNI
>     Core platform API violation: Ljava/nio/NIOAccess;->getBaseArrayOffset(Ljava/nio/Buffer;)I from Landroid/graphics/Bitmap; using JNI
>     Core platform API violation: Ljava/nio/NIOAccess;->getBaseArray(Ljava/nio/Buffer;)Ljava/lang/Object; from Landroid/graphics/Bitmap; using JNI
> ```

This is really strange bitmap and those libraries seems not to like working with it, but this error seems to be lack of  good info 🤷‍♂️

I've tried downloading the debug apk but for some reason youtube doesn't work with it.

**Comment by arielshulman** [comment]
Tried to backtrace (without my laptop, [here](https://android.googlesource.com/platform/frameworks/base/+/9da9df9/core/jni/android/graphics/Bitmap.cpp) ) `'Error, cannot access an invalid/free'd bitmap here!'`, and it seems to come from trying to work with the bitmap after it was recycled as you suggested.

**Comment by Stypox** [comment]
@arielshulman please test the APK that should be built by the CI within minutes from now (I have no idea why my apk does not work)

**Comment by TobiGr** [comment]
Please don't forget to attribute the new library in the about screen (and to remove the replaced one)

**Comment by Stypox** [comment]
@arielshulman for some reason checkstyle was crashing with a totally not understandable and unrelated error, but the real problem was a syntax error caused by rebasing. I don't know how that slipped through. Anyway, now everything should have been built correctly, the apk is here: https://github.com/TeamNewPipe/NewPipe/suites/2389524359/artifacts/50769605

**Comment by arielshulman** [comment]
🤸 Yay!
Works great!
Thanks again for your dedication to solve this quirck.

**Comment by TacoTheDank** [comment]
@Stypox Oh btw, you'll have to rebase or fix the build.gradle confliction from my library rearrangement PR, as a heads up

**Comment by Stypox** [comment]
> Please don't forget to attribute the new library in the about screen (and to remove the replaced one) @TobiGr 

Done

**Comment by TacoTheDank** [comment]
@Stypox By the way, I'm curious, why did you decide to go with Picasso over Glide? Nothing against Picasso - it's just that the two libraries' APIs are somewhat similar - but Picasso seems to get more sporadic / spotty maintenance while Glide is more regularly maintained, so I figured I'd ask.

**Comment by Stypox** [comment]
I went with Picasso because it is more lightweight but still has all the features we need. Even if it has less maintenance it comes from the same organization as OkHttp, so I think we can use it safely

**Review by XiangRongLin — COMMENTED** [review]
I took a quick look. I have no idea about the library i didn't comment on the usage

File: app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java [hunk 1]
```diff
@@ -77,13 +72,9 @@ public String transformUrl(final Matcher match, final String url) {
         itemRoot = itemView.findViewById(R.id.itemRoot);
         itemThumbnailView = itemView.findViewById(R.id.itemThumbnailView);
         itemLikesCountView = itemView.findViewById(R.id.detail_thumbs_up_count_view);
-        itemDislikesCountView = itemView.findViewById(R.id.detail_thumbs_down_count_view);
```
[the remark this answers is not in the document]
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java:80]: It was unused

File: app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt [hunk 2]
```diff
@@ -162,6 +162,10 @@ class AboutActivity : AppCompatActivity() {
                 "OkHttp", "2019", "Square, Inc.",
                 "https://square.github.io/okhttp/", StandardLicenses.APACHE2
             ),
+            SoftwareComponent(
+                "Picasso", "2013", "Square, Inc.",
```
Comment (B0pol) [inline app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt:166]: It should be 2013-2020

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 3]
```diff
@@ -680,33 +680,23 @@ protected void initListeners() {
...
-            };
-
-            IMAGE_LOADER.displayImage(info.getThumbnailUrl(), binding.detailThumbnailImageView,
-                    ImageDisplayConstants.DISPLAY_THUMBNAIL_OPTIONS, onFailListener);
-        }
+        PicassoHelper.loadThumbnail(info.getThumbnailUrl()).tag(PICASSO_VIDEO_DETAILS_TAG)
+                .into(binding.detailThumbnailImageView, new Callback() {
+                    @Override
+                    public void onSuccess() {
+                    }
```
[the remark this answers is not in the document]
Comment (Redirion) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:687]: you should also be able to "hide" this empty block with a () -> {} lambda

**Comment by jimman2003** [comment]
Guys,the dev of UIL is back:
https://github.com/nostra13/Android-Universal-Image-Loader

**Comment by Stypox** [comment]
@jimman2003 I would still switch, Picasso has a better behaviour imho

**Comment by opusforlife2** [comment]
> Guys,the dev of UIL is back:

@jimman2003 Where do you see that? The last commit is over a year ago. And the message saying the dev will not work from November 27 (presumably 2020) is still there.

**Comment by jimman2003** [comment]
> > Guys,the dev of UIL is back:
> 
> @jimman2003 Where do you see that? The last commit is over a year ago. And the message saying the dev will not work from November 27 (presumably 2020) is still there.

Oops well.   Misread the commit log  😭

File: app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt (hunk 2 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt:166]: According to their [README](https://github.com/square/picasso#license): "Copyright 2013 Square, Inc."

I'd just remove all `- 2020`, since they are already outdated and it doesn't make sense that we update them on each new year

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:687]: It is a lambda with two functions, so that can't be done

**Comment by Stypox** [comment]
I rebased and applied the review @XiangRongLin @arielshulman @TobiGr

**Comment by arielshulman** [comment]
I've played with this version and it seems to works great. Thanks @Stypox 🙏

**Comment by TacoTheDank** [comment]
Looks like there's more conflicts 😞

**Comment by Stypox** [comment]
Solved @TacoTheDank @TobiGr

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 4]
```diff
@@ -680,33 +680,24 @@ protected void initListeners() {
...
 
-        if (!isEmpty(info.getUploaderAvatarUrl())) {
-            IMAGE_LOADER.displayImage(info.getUploaderAvatarUrl(),
-                    binding.detailUploaderThumbnailView,
-                    ImageDisplayConstants.DISPLAY_AVATAR_OPTIONS);
-        }
+        PicassoHelper.loadAvatar(info.getSubChannelAvatarUrl()).tag(PICASSO_VIDEO_DETAILS_TAG)
+                .into(binding.detailSubChannelThumbnailView);
+        PicassoHelper.loadAvatar(info.getUploaderAvatarUrl()).tag(PICASSO_VIDEO_DETAILS_TAG)
+                .into(binding.detailUploaderThumbnailView);
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:700]: Why did you implement error handling for the video thumbnail, but not for the channel avatars or anywhere else?

**Review by TobiGr — COMMENTED** [review]
Looks good to me. I have two questions

File: app/src/main/java/org/schabi/newpipe/App.java [hunk 5]
```diff
@@ -104,7 +101,12 @@ public void onCreate() {
         ServiceHelper.initServices(this);
 
         // Initialize image loader
-        ImageLoader.getInstance().init(getImageLoaderConfigurations(10, 50));
+        final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
+        PicassoHelper.init(this);
+        PicassoHelper.setShouldLoadImages(
+                prefs.getBoolean(getString(R.string.download_thumbnail_key), true));
+        PicassoHelper.setIndicatorsEnabled(BuildConfig.DEBUG
```
[the remark this answers is not in the document]
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/App.java:108]: I think it doesn't matter, but I'm fixing this

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 4 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:700]: Because you don't want to see a snackbar error for each image that can't be loaded, so the placeholder is just shown instead in that case. The only image where I thought it would be useful to see an additional snackbar was the video thumbnail in `VideoDetailFragment`, since that's only one single image. Imagine a scenario where the extractor returns invalid urls for all stream info items: a snackbar for each one of them would compromise app usage. Even without a snackbar the user notices that there is an issue, by just seeing that all thumbnails are replaced with the placeholder one.

**Comment by Stypox** [comment]
Rebased and applied your first suggestion

**Comment by TobiGr** [comment]
Sorry, I forgot about this. I tested this thoroughly. The PR dhould be good to merge after a rebase

**Comment by TacoTheDank** [comment]
> Sorry, I forgot about this. I tested this thoroughly. The PR dhould be good to merge after a rebase

And a conflict fix :sweat_smile:

**Comment by Stypox** [comment]
- @TobiGr rebased
- I enforced a 15s timeout for image loading (even though that's already the default in OkHttp3, but just wanted to make sure)
- @litetex could you check if my changes in `SeekbarPreviewThumbnailHolder` are ok? I completely removed `SyncImageLoadingListener` since the timeout is now taken care of by OkHttp3 itself. I tested seekbar preview thumbnails and they work.

**Comment by tsiflimagas** [comment]
One thing I wonder about is if it would be possible to remove that gray placeholder and just leave it blank/black, as it is currently. It's just my personal taste, but it doesn't look that great.

**Comment by Stypox** [comment]
@tsiflimagas you are right, done.

**Comment by litetex** [comment]
@Stypox 
Everything looks fine 😄 
Also reviewed the code a bit and didn't find any problems.

**Comment by Stypox** [comment]
@litetex thank you for confirming :-)
@TobiGr ready for review

**Review by TobiGr — DISMISSED** [review]

**Comment by TobiGr** [comment]
nooooo.... 
I just wanted to merge this and there is a merge conflict again. sorry :(

**Comment by Stypox** [comment]
@TobiGr rebased ;-)

**Review by TobiGr — APPROVED** [review]

File: app/src/main/java/org/schabi/newpipe/App.java [hunk 6]
```diff
@@ -117,6 +119,7 @@ public void onTerminate() {
             disposable.dispose();
         }
         super.onTerminate();
+        PicassoHelper.terminate();
```
Comment (evermind-zz) [inline app/src/main/java/org/schabi/newpipe/App.java:122]: Just wondering why are you are calling PicassoHelper.terminate() after super.onTerminate() call and not before

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/App.java:122]: I don't know if it makes any difference, but I think I chose to do it this way because there could still be something doing image processing before `super.onTerminate()`, but surely there isn't after it.

Comment (evermind-zz) [reply app/src/main/java/org/schabi/newpipe/App.java:122]: I see it seems it is totally irrelevant what is done in this method on a real device. It is never called according to:
https://developer.android.com/reference/android/app/Application#onTerminate()

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/App.java:122]: Mmmh... should we remove it? @TobiGr

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/App.java:122]: I think so. That's at least how I understand the docs

**Comment by Poolitzer** [comment]
@Stypox no idea if fitting or not but #908 is still open, one might want to close that? Or not?

**Comment by Stypox** [comment]
@Poolitzer what? #908 is already closed and has nothing to do with this

**Comment by Stypox** [comment]
> One thing I wonder about is if it would be possible to remove that gray placeholder which appears till the image is loaded and just leave it blank, as it is currently. It's just my personal taste, but it doesn't look that great.

@tsiflimagas This has been reverted in #8530, see there for an explanation, sorry :sweat_smile:
