### PR TITLE
Restore license pop-up when orientation changes

### LINKED ISSUE #4113: License dialog disappear after device rotation
### Version

-0.19.2

### Steps to reproduce the bug

Open licenses dialog and rotate

### Expected behavior

License dialog with correct reading position should remain there

### Actual behaviour

License dialog disappear

### Screenshots/Screen recordings

Screen Shot 2020-08-11 at 7 48 28 PM
Screen Shot 2020-08-11 at 7 48 35 PM

### PR DESCRIPTION
**Pull request by nmurali94**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Keep license pop-up when screen is rotated

#### Fixes the following issue(s)

- Fixes #4113

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java [hunk 1]
```diff
@@ -44,16 +47,21 @@ public static LicenseFragment newInstance(final SoftwareComponent[] softwareComp
...
     }
 
     @Override
     public void onCreate(@Nullable final Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         softwareComponents = (SoftwareComponent[]) getArguments()
                 .getParcelableArray(ARG_COMPONENTS);
-
+        if (savedInstanceState != null) {
+            Serializable license = savedInstanceState.getSerializable(LICENSE_KEY);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java:60]: Add `final`

Comment (nmurali94) [reply app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java]: Done

Comment (wb9688) [reply app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java]: @nmurali94: If you've fixed such an issue, next time please just press the "Resolve conversation" button instead of saying something like "Done".

**Review by Stypox — APPROVED** [review]
Works
