### PR TITLE
Fix foreground service issues

### LINKED ISSUE #12553: Unable to create service
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.28.0-25-202508180153

### Steps to reproduce the bug

1. Click on the link : [notify](https://youtu.be/OZRG7Og61mw?utm_campaign=2025-08-19-youtube-first-launch-teaser%20%2801K318CDH30KCJ5KNDG94SBWPE%29&utm_medium=email&utm_source=Newsletter&_kx=a1m7o-dnv-0MpzU_3UTqUwQmwFH84-rmErkoTiMc53DPD2-WmiAd9TicS7DiGipJ.LNYsuiLNYsui) 
2. That's all

### Expected behavior

Go to a Youtube video

### Actual behavior

Crash : Unable to create service 

### Screenshots/Screen recordings

_No response_

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Timestamp:__ 2025-08-19T22:46:52.098+02:00
* __Package:__ org.schabi.newpipe.refactor.nightly
* __Service:__ none
* __Version:__ 0.28.0-25-202508180153
* __OS:__ Linux Android 15 - 35
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.RouterActivity$FetcherService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{9749d2 20930:org.schabi.newpipe.refactor.nightly/u0a202} targetSDK=35
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5148)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2547)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8934)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{9749d2 20930:org.schabi.newpipe.refactor.nightly/u0a202} targetSDK=35
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5094)
	at android.os.Parcel.readParcelable(Parcel.java:5076)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3256)
	at android.os.Parcel.createException(Parcel.java:3245)
	at android.os.Parcel.readException(Parcel.java:3228)
	at android.os.Parcel.readException(Parcel.java:3170)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7268)
	at android.app.Service.startForeground(Service.java:776)
	at org.schabi.newpipe.RouterActivity$FetcherService.onCreate(RouterActivity.java:949)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5135)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

_No response_

### Affected device model

_No response_

### Additional information

_No response_

### LINKED ISSUE #12564: Crash on toggle the notification option in Settings Screen
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

~0.28.0~ NewPipe-refactor-nightly-25

### Steps to reproduce the bug

1. Hamburger icon
2. Goto Settings
3. Click on Notifications                                                                            

### Expected behavior

_No response_

### Actual behavior

_No response_

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/6c34f3c3-fc9b-45e9-8061-e2d9363b1133

### Logs

2025-08-22 13:18:55.654  4557-4557  AndroidRuntime          org.schabi.newpipe.debug.refactor    E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: org.schabi.newpipe.debug.refactor, PID: 4557
                                                                                                    java.lang.RuntimeException: Unable to start service androidx.work.impl.foreground.SystemForegroundService@a5fb237 with Intent { act=ACTION_START_FOREGROUND cmp=org.schabi.newpipe.debug.refactor/androidx.work.impl.foreground.SystemForegroundService (has extras) mCallingUid=11321 }: android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{d20f224 4557:org.schabi.newpipe.debug.refactor/u0a1321} targetSDK=35 has been prohibited
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5134)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2481)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{d20f224 4557:org.schabi.newpipe.debug.refactor/u0a1321} targetSDK=35 has been prohibited
                                                                                                    	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4922)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4904)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3104)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3093)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3076)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3018)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy6.setServiceForeground(Unknown Source)
                                                                                                    	at android.app.Service.startForeground(Service.java:862)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService$Api31Impl.startForeground(SystemForegroundService.java:190)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService.startForeground(SystemForegroundService.java:138)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundDispatcher.handleNotify(SystemForegroundDispatcher.java:332)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundDispatcher.onStartCommand(SystemForegroundDispatcher.java:221)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService.onStartCommand(SystemForegroundService.java:80)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5116)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2481) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257) 
                                                                                                    	at android.os.Looper.loop(Looper.java:368) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
--------- beginning of main

### Affected Android/Custom ROM version

Android 14

### Affected device model

OnePlus Nord

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR
- Fix foreground notification issue on newer versions of Android.

#### Fixes the following issue(s)
- Fixes #12564
- Fixes #12553
- Fixes foreground notification issue [reported in #12388](https://github.com/TeamNewPipe/NewPipe/pull/12388#issuecomment-3124021524)

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java [hunk 1]
```diff
@@ -167,19 +167,15 @@ public boolean shouldUpdateBufferingSlot() {
                 && notificationBuilder.mActions.get(2).actionIntent != null);
     }
 
-
+    @SuppressLint("NewApi") // ServiceInfo constant is inlined
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java]: Are you sure this is the case? Can you provide a source? We can just keep using `if {} else {}`, it's not too bad after all

**Review by Stypox — DISMISSED** [review]

File: app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java (hunk 1 above)
Comment (Isira-Seneviratne) [reply app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java]: https://stackoverflow.com/questions/12321804/android-version-checking-and-inlining-of-static-final-constants

Also, a lot of the library classes such as NotificationManagerCompat use the same trick.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java]: Mmmh, I would still stay on the safe side and use `if {} else {}`

File: app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java [hunk 2]
```diff
@@ -167,19 +167,16 @@ public boolean shouldUpdateBufferingSlot() {
...
         updateNotification();
 
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
-            player.getService().startForeground(NOTIFICATION_ID, notificationBuilder.build(),
-                    ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PLAYBACK);
-        } else {
-            player.getService().startForeground(NOTIFICATION_ID, notificationBuilder.build());
-        }
+        final int serviceType = Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q
+                ? ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PLAYBACK : 0;
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java:178]: Did you use `0` because `FOREGROUND_SERVICE_TYPE_NONE` is deprecated? I think it is better to use this constant so we know that it is deprecated and what the value stands for.

Comment (Isira-Seneviratne) [reply app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java:178]: No, it's because the ServiceInfo constants aren't used below Android 10, and lint flags it.

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java:178]: Ah ok. Could you just leave a comment about that? I was wondering why there was a 0 and had to look up what it meant.
