### PR TITLE
[fix] Hide controls when resuming playback via double tap

### LINKED ISSUE #6815: Resuming by double tapping does not hide overlay and android task bar
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to any video, play it (bug is present in normal and fullscreen player)
2. Pause the video
3. Resume the video by double tapping in the middle, but not using the pause/play button

### Actual behavior
NewPipe overlay does not hide in normal player, in fullscreen android task bar does not hide either.

### Expected behavior
The same as when resuming with the play button: hide overlay.

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Lenovo L78051 (Z6 Pro)

### PR DESCRIPTION
**Pull request by iampopovich**
Remove redundant comment about hiding controls on double tap

#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR

- record videos
- create clones
- take over the world

#### Before/After Screenshots/Screen Record

- Before:

https://github.com/user-attachments/assets/24d4b8fc-f8fd-47f4-aee8-d5b66b8f9856

- After:

https://github.com/user-attachments/assets/0d8bb770-2b16-4b49-aecd-1056106bf19c

#### Fixes the following issue(s)

- Fixes #6815

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] The proposed changes follow the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md#ai-policy).
- [x] I tested the changes using an emulator or a physical device.

### CODE REVIEW

**Comment by ghost** [comment]
I pulled locally and tested. Confirm this PR solves the bug

File: app/src/main/java/org/schabi/newpipe/player/gesture/BasePlayerGestureListener.kt [hunk 1]
```diff
@@ -47,6 +47,9 @@ abstract class BasePlayerGestureListener(
             startMultiDoubleTap(event)
         } else if (portion === DisplayPortion.MIDDLE) {
             player.playPause()
+            if (player.isPlaying()) {
```
Comment (ghost) [inline app/src/main/java/org/schabi/newpipe/player/gesture/BasePlayerGestureListener.kt]: Please use kotlins property access syntax

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/player/gesture/BasePlayerGestureListener.kt]: done

**Review by TobiGr — APPROVED** [review]
thank you
