### PR TITLE
Prevent recaptcha webview from keeping youtube loaded in background

### LINKED ISSUE #6732: ReCaptcha webview continues playing in background
### Checklist

- [x] I am using the latest version - fd4e1b8d2c09a7df34996e93376d49e5100403c2 (development build) >= v0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play video while blocked by captcha
2. Open captcha webview (press solve)
3. Solve captcha and answer GDPR questions
4. Wait for ad to start playing
5. Press done (tick in top-right)

### Actual behavior

After the webview closes the ad continues playing in the background

### Expected behavior

The webview stops playing any videos loaded. Probably best if it navigates to an empty (about:blank) page so the youtube website's javascript isn't sending requests in the background.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: N/A

### PR DESCRIPTION
**Pull request by Douile**
After the cookies are extracted from the recaptcha webview make it load an empty page to prevent youtube being loaded unecessarily in the background.

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Load empty page in recaptcha webview after youtube is no longer needed

#### Fixes the following issue(s)

- Fixes #6732 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java [hunk 1]
```diff
@@ -162,6 +162,9 @@ private void saveCookiesAndFinish() {
             setResult(RESULT_OK);
         }
 
+        // Navigate to blank page (unloads youtube to prevent background playback)
+        recaptchaBinding.reCaptchaWebView.loadData("", "text/html", null);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java:166]: According to [this SO](https://stackoverflow.com/questions/3715482/how-to-clear-webview-content) you should use
```suggestion
        recaptchaBinding.reCaptchaWebView.loadUrl("about:blank");
```

**Review by Stypox — CHANGES_REQUESTED** [review]

**Comment by nadiration** [comment]
Thank you for doing this! This is specially useful on limited data plans

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
Thank you!
