### PR TITLE
Handling Comment Replies fragments

### LINKED ISSUE #13162: NewPipe shouldn't keep comments' replies in page history if the video to which they belong is not open anymore
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read and understood the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#ai-policy). The content of this bug report is not generated by AI.

### Affected version

0.28.2

### Steps to reproduce the bug

Open a video, see if there are comments with replies to them, open the replies to one comment, watch the video get minimized to the bottom, "reopen" the video from the bottom, open the replies to another comment, once again reopen the minimized video, open another set of replies, and this time close ("X") the video at the bottom. Now try to go back with the Back button. You'll see that NewPipe will make you go through the replies that you had open, even though the video is no longer open.

### Expected behavior

Clear previously open comments' replies from memory if the video to which they belong is no longer open, freeing users from having to go back for who-knows-how-long in page history due to previously open replies.

### Actual behavior

All replies are being kept in page history.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

Android 16 / OneUI 8.0

### Affected device model

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by aivelon**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing) ⚠️ **Your PR must target the [`refactor`](https://github.com/TeamNewPipe/NewPipe/tree/refactor) branch**
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Remove existing comment replies screens before adding new one. This will avoid infinite stacking of comment replies views.

#### Before/After Screenshots/Screen Record

- Before: https://filedn.eu/lVAaQLqg1VOYMzxdXQPHpt4/Newpipe-testing/before.mkv
- After: https://filedn.eu/lVAaQLqg1VOYMzxdXQPHpt4/Newpipe-testing/after.mkv

#### Fixes the following issue(s)

- Fixes #13162 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] The proposed changes follow the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md#ai-policy).
- [x] I tested the changes using an emulator or a physical device.

### CODE REVIEW

**Comment by hollownights** [comment]
Gonna leave my last comment on #13162 to be discussed here too, in case any reviewer misses it.

> I have been reconsidering part of my understanding of this problem, though. To use yours PR description, I think that to...
>
> > Remove existing comment replies screens before adding new one.
> 
> ... is absolutely great and solve the annoying problem with infinite back-pages, but I'm not sure that to... 
> 
> > Also close all comment replies screens when the video details screen is closed.
> 
> ... is ideal anymore. Reason being that closing the replies' page that the user has on screen may be a little disconcerting, cause, sure, the user may not want to watch/listen to the video anymore, but they may still be reading the comments on screen.

**Comment by aivelon** [comment]
please review.....changes have been made after discussion in the linked issue.

File: app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java [hunk 1]
```diff
@@ -501,13 +501,44 @@ public static void openCommentAuthorIfPresent(@NonNull final FragmentActivity ac
...
+        closeCommentRepliesFragments(activity);
         defaultTransaction(activity.getSupportFragmentManager())
                 .replace(R.id.fragment_holder, new CommentRepliesFragment(comment),
                         CommentRepliesFragment.TAG)
                 .addToBackStack(CommentRepliesFragment.TAG)
                 .commit();
     }
 
+    // This removes all of the top CommentRepliesFragment instances.
+    // Ideally there should only be one since we remove existing before opening a new one.
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java]: please use JDOc style for this method comment `/**`

Comment (aivelon) [reply app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java]: done
