### PR TITLE
Fix player controls not hiding if resumed from media button

### LINKED ISSUE #3403: The player controls don't hide when using external controls
### Version

0.19.2

### Steps to reproduce the bug

1. Play video with a bluetooth speaker connected
2. Press "pause" on the bluetooth speaker
3. Press "play" on the bluetooth speaker
4. The video starts playing again

### Expected behavior

The player controls should hide after a few seconds
### Actual behaviour

The player controls remain on screen and disappear only when it is tapped. This means that the play/pause controls on the bluetooth speaker become useless.

### LINKED ISSUE #7340: Play Button does not hide if playback is resumed externally (keyboard or bluetooth earpiece)
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Start playing a video
2. Pause the video (doesn't matter how it's done, can be with the pause button or externally)
3. Use either a keyboard's space button or a bluetooth earpiece to resume the playback.

### Actual behavior

The play button stays visible.

### Expected behavior

The play button should hide, like when you tap the button manually.

### Device info
Not applicable, happens on all the devices I've tested.

### PR DESCRIPTION
**Pull request by ktprograms**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Added `hideControls(0, 0)` to the Space key pressed and the `PlayerMediaSession` `play` method (only if the player is currently playing)

#### Before/After Screenshots/Screen Record

| Before | After |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/71804605/139620899-b62f3eb7-1d07-44d3-959e-104d46e9fbea.mp4"/> | <video src="https://user-images.githubusercontent.com/71804605/139621120-d73b284d-de60-4eb7-af34-eaae7df747d6.mp4"/> |

#### Fixes the following issue(s)

- ~~Fixes #7340~~ (I made that issue then only looked at how to fix it)
- Fixes #3403

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 1]
```diff
@@ -3754,6 +3754,9 @@ public boolean onKeyDown(final int keyCode) {
             case KeyEvent.KEYCODE_SPACE:
                 if (isFullscreen) {
                     playPause();
+                    if (isPlaying()) {
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:3757]: Why is this needed?

Comment (ktprograms) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:3757]: So that the behaviour is consistent with manually pausing (keeps the controls visible).

**Review by TobiGr — APPROVED** [review]

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 1 above)
Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:3757]: Okay but why is this only the case for the full-screen player?

Comment (ktprograms) [reply app/src/main/java/org/schabi/newpipe/player/Player.java]: The `if (isFullscreen)` was already there so I just left it. But I've tested and it works fine even when not in fullscreen so I've removed the `if (isFullscreen)` in https://github.com/TeamNewPipe/NewPipe/pull/7341/commits/29348411520f56f07865c6deef722ae107b9a205

**Comment by ktprograms** [comment]
@litetex Can you please review?

**Comment by litetex** [comment]
@ktprograms 

I'm currently trying to understand if this is the correct place for ``hideControls``.
<details><summary>But the code who is calling this is <i>a bit</i> complicated:</summary>

grafik
(It also pretty annoying that there are zero comments and the code got rewritten in like 10 commits)

</details>

Because when e.g. ``Player#onPaused`` is called then there is always a call for ``showControls(400)`` executed.
However this is not the case in ``Player#onPlaying`` but I don't know why.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 2]
```diff
@@ -3752,8 +3752,9 @@ public boolean onKeyDown(final int keyCode) {
             default:
                 break;
             case KeyEvent.KEYCODE_SPACE:
-                if (isFullscreen) {
```
Comment (ImDeadGuy) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:3755]: Not sure why this check existed here in the first place, what can/should happen when pressing Space outside of full screen? (typing in the search or comment box?)
If in doubt, could just leave the original if() check, and just add the if (isPlaying) part.

**Review by ImDeadGuy — APPROVED** [review]
Honestly, this bug has been _bugging_ me for months (almost always use BT headphones with the tablet slightly out of reach).
Just want this fix in sooner than later, and I've tested the custom APK in Checks and it works as expected. 👍

**Comment by Bugginme** [comment]
@ImDeadGuy same :/

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 2 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:3755]: See #5331. In that PR there doesn't seem to be any explanation about why the `if (isFullscreen)`. So I think we can safely remove it, what do you think @mbarashkov?

Comment (mbarashkov) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:3755]: @Stypox In that PR, I had to do this because not in full screen space key was used on TV's to navigate the screen vertically, as I recall.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:3755]: Ok, that makes sense, thank you. Then I'll restore the previous `if (isFullscreen)`.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 3]
```diff
@@ -3752,8 +3752,9 @@ public boolean onKeyDown(final int keyCode) {
...
-                    playPause();
+                playPause();
+                if (isPlaying()) {
+                    hideControls(0, 0);
                 }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:3758]:
```suggestion
                if (isFullscreen) {
                    playPause();
                    if (isPlaying()) {
                        hideControls(0, 0);
                    }
                }
```

File: app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java [hunk 4]
```diff
@@ -88,6 +88,7 @@ public MediaDescriptionCompat getQueueMetadata(final int index) {
     @Override
     public void play() {
         player.play();
+        player.hideControls(0, 0);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java:91]:
```suggestion
        // hide the player controls even if the play command came from the media session
        player.hideControls(0, 0);
```

**Review by Stypox — CHANGES_REQUESTED** [review]

**Comment by Stypox** [comment]
@litetex what do you think about my suggestions? If they look good, commit them and then merge and squash (after 0.22.1)

**Comment by litetex** [comment]
@Stypox 
I think you can try to add them 😄

**Comment by ktprograms** [comment]
@litetex What do you mean?

Should I commit/squash the suggestions?

**Review by Stypox — APPROVED** [review]

**Comment by ImDeadGuy** [comment]
Hey guys, is this meant to be fixed now in release 23?

Because it's definitely not. Resuming from the BT headset play/pause button still keeps the UI on screen forever.

**Comment by TiA4f8R** [comment]
It was meant to be fixed, yes, but the latest ExoPlayer update broke the original fix, and a new fix has been provided in the PR linked above: #8315.
