### PR TITLE
 Fix Kodi button showing up with unsupported services

### LINKED ISSUE #1166: soundcloud kore not found
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

If I try to stream soundcloud on kore the error (kore not found) will popup. When I stream/share youtube link with kore it works perfectly.

### LINKED ISSUE #1930: NewPipe fails to see that Kore (Kodi remote) is installed
While it has previously worked on this installation (same version, 0.14.2 from F-Droid), NewPipe now fails to register that Kore is installed, so it's not possible to queue videos Kodi.
I've tried reinstalling both NewPipe and Kore but even with Kore open in the background, it's not recognised as being there. It used to occasionally work but has now stopped, even if I restart my phone (Mi4C, running the latest MIUI). 

- [ yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [yes] I checked if the issue/feature exists in the latest version.
-

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This PR disables the share to Kodi button when the current service is not supported (see the Kore  [AndroidManifest.xml](https://github.com/xbmc/Kore/blob/master/app/src/main/AndroidManifest.xml)). Supported services are Youtube and Soundcloud. From that manifest I could also deduce that replacing `https` with `http` is not needed anymore.

#### Fixes the following issue(s)
- fixes #1166
- closes #1930

#### Testing apk
I tested if the urls correctly matched Kore's manifest, by installing the app (even without connecting it to anything) and sharing urls. Before this fix sharing MediaCCC urls would have generated an error (thus leading to a "Missing Kore app, install it?" dialog), so this method of testing is good. 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4588833/app-debug.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by Stypox** [comment]
@TobiGr done, and tested again, by enqueueing videos from different services and going backward and forward in the main player.

**Comment by TobiGr** [comment]
According to https://octodon.social/@dennix/104122037269553457 there is a kodi plugin which allows to open media.ccc videos with kodi.

**Comment by Stypox** [comment]
@TobiGr is that an app with a standalone AndroidManifest.xml?

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 1]
```diff
@@ -665,8 +666,7 @@ public boolean onOptionsItemSelected(final MenuItem item) {
                 return true;
             case R.id.action_play_with_kodi:
                 try {
-                    NavigationHelper.playWithKore(activity, Uri.parse(
-                            url.replace("https", "http")));
+                    NavigationHelper.playWithKore(activity, Uri.parse(currentInfo.getUrl()));
```
Comment (wb9688) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:669]:
```suggestion
                    NavigationHelper.playWithKore(activity, Uri.parse(url));
```

File: app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java [hunk 2]
```diff
@@ -712,6 +709,13 @@ public void onShuffleClicked() {
         protected void onMetadataChanged(@NonNull final MediaSourceTag tag) {
             super.onMetadataChanged(tag);
 
+            // show kodi button if it supports the current service and it is enabled in settings
+            boolean showKodiButton =
```
Comment (wb9688) [inline app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java:713]: `final`

**Comment by wb9688** [comment]
@TobiGr: There indeed is a [Kodi plug-in](https://github.com/voc/plugin.video.media-ccc-de), however Kore doesn't seem to have support for it in [its AndroidManifest.xml](https://github.com/xbmc/Kore/blob/master/app/src/main/AndroidManifest.xml).

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:669]: I changed this because url is the originalUrl, that can be in a non-standard form, while getUrl() gets the standard url

File: app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java (hunk 2 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java:713]: Yes 😫😂

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (wb9688) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:669]: Oh, you're right, I thought I had checked that…

**Comment by TobiGr** [comment]
@wb9688 Thank you for checking that and opening the ticket!

We can add mediaCCC to `isServiceSupportedByKore()` once they changed their manifest. Looks good to merge :+1:

**Comment by Stypox** [comment]
@wb9688 @TobiGr fixed
