### PR TITLE
Prevent error msg: 'Unrecoverable player error occurred' while playin…

### LINKED ISSUE #6502: 'Unrecoverable player error occurred' while playing video during rotation
### Checklist

- [x] I am using the latest version - 0.21.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Playing a video in VideoDetailFragment and rotating the screen to landscape (back and forth more often) can trigger this error message. Especially if rotation for whatever reason takes long or playing a high resolution (1080p) video.

### Actual behaviour

error msg: 'Unrecoverable player error occurred'

### Expected behavior

no error message and the video should keep playing

### Logs
    The underlying logcat error messages:
    05-12 16:38:38.251 24920 26037 E Surface : getSlotFromBufferLocked: unknown buffer: 0x923fc810
    05-12 16:38:38.251 24920 26037 W ACodec  : [OMX.qcom.video.decoder.avc] can not return buffer 35 to native window

### Device info

 - Android version/Custom ROM version: LineageOS 14.1
 - Device model: klte

### PR DESCRIPTION
**Pull request by evermind-zz**
…g video during rotation (#6502)

Playing a video in VideoDetailFragment and rotating the screen to landscape (back and forth more often)
can trigger this error message. Especially if rotation for whatever reason takes long or
playing a high resolution (1080p) video.

The underlying logcat error messages:
05-12 16:38:38.251 24920 26037 E Surface : getSlotFromBufferLocked: unknown buffer: 0x923fc810
05-12 16:38:38.251 24920 26037 W ACodec  : [OMX.qcom.video.decoder.avc] can not return buffer 35 to native window

The problem is that that Exoplayer is trying to write to our -- during rotation -- no longer existant
(VideoDetailFragment) SurfaceView.

Solution:
Implementing SurfaceHolder.Callback and using DummySurface we can now handle the lifecycle of the Surface.

How?: In case we are no longer able to write to the Surface eg. through rotation/putting in
background we can set a DummySurface. Although it only works on API >= 23.
Result: we get a little video interruption (audio is still fine) but we won't get the
'Unrecoverable player error occurred' error message.

This implementation is based on and more background information:
 'ExoPlayer stuck in buffering after re-adding the surface view a few time 2703'

 -> exoplayer fix suggestion link
  https://github.com/google/ExoPlayer/issues/2703#issuecomment-300599981

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- no error message 'Unrecoverable player error occurred'  of video while rotation

#### Fixes the following issue(s)

- Fixes #6502 

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 1]
```diff
@@ -4234,4 +4242,86 @@ public PlayQueueAdapter getPlayQueueAdapter() {
...
+            if (surfaceHolderCallback != null) {
+                if (binding != null) {
+                    binding.surfaceView.getHolder().removeCallback(surfaceHolderCallback);
+                }
+                surfaceHolderCallback.release();
+                surfaceHolderCallback = null;
+            }
+        }
+    }
+    //endregion SurfaceHandlerCallback
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:4326]: This whole region of code should be moved to another class, `Player` is too big.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 2]
```diff
@@ -4234,4 +4242,86 @@ public PlayQueueAdapter getPlayQueueAdapter() {
...
+
+        public void release() {
+            if (dummySurface != null) {
+                dummySurface.release();
+                dummySurface = null;
+            }
+        }
+    }
+
+    private void setupVideoSurface() {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:4302]: Can we be completely completely sure that this isn't called twice? That would create leaks and certainly other issues. Maybe call `cleanupVideoSurface()` just at the beginning of `setupVideoSurface()`, to ensure there is no `Surface` left behind.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 3]
```diff
@@ -267,6 +270,7 @@
     private SimpleExoPlayer simpleExoPlayer;
     private AudioReactor audioReactor;
     private MediaSessionManager mediaSessionManager;
+    private SurfaceHolderCallback surfaceHolderCallback;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:273]:
```suggestion
    @Nullable private SurfaceHolderCallback surfaceHolderCallback;
```

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you!

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 1 above)
Comment (evermind-zz) [reply app/src/main/java/org/schabi/newpipe/player/Player.java]: done

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 2 above)
Comment (evermind-zz) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:4246]: done

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 3 above)
Comment (evermind-zz) [reply app/src/main/java/org/schabi/newpipe/player/Player.java]: done

**Review by Stypox — DISMISSED** [review]
I tested and it works well on both API 19 emulated and API 29 real.

**Comment by evermind-zz** [comment]
I've merged the changes and updated pull request

**Review by Stypox — APPROVED** [review]
