### PR TITLE
NullPointerException on screen rotation during exit fix

### LINKED ISSUE #5973: NullPointerException on screen rotation during exit
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Watch a video in landscape
2. Press the return button repeatedly 
2.1. Video swipes down
2.2 Back to start page (Subscribed channels for me)
2.3 Exit app
3. Turn the phone to portrait
(Not sure about the timing, but I got the error now multiple times, I guess during the last step 2.3.)

### Actual behaviour

See crash log below

### Expected behavior

The app should exit

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'androidx.viewpager.widget.ViewPager org.schabi.newpipe.databinding.FragmentVideoDetailBinding.viewPager' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.updateTabLayoutVisibility(VideoDetailFragment.java:1012)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$initListeners$2(VideoDetailFragment.java:653)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$initListeners$2$VideoDetailFragment(VideoDetailFragment.java)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$KSgfQ0ZoZbJufG4lEaiRA-Ac5xI.onOffsetChanged(lambda)
	at com.google.android.material.appbar.AppBarLayout.onOffsetChanged(AppBarLayout.java:762)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.setHeaderTopBottomOffset(AppBarLayout.java:1739)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.setHeaderTopBottomOffset(AppBarLayout.java:1215)
	at com.google.android.material.appbar.HeaderBehavior.setHeaderTopBottomOffset(HeaderBehavior.java:158)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior$1.onAnimationUpdate(AppBarLayout.java:1409)
	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1350)
	at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1262)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1310)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Lineage OS for microg
 - Device model: tenshi

### PR DESCRIPTION
**Pull request by sauravrao637**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- check  if the binding is null before attempting to retrieve its objects. 

#### Fixes the following issue(s)

- Fixes #5973

#### Relies on the following changes

- Could not reproduce the bug even after several attempts to do so thus had to rely on crash report provided with the issue which clearly shows  _Attempt to read from field 'androidx.viewpager.widget.ViewPager org.schabi.newpipe.databinding.FragmentVideoDetailBinding.viewPager' on a null object reference_ thus we add a check for null value for binding before accessing its objects  
 
#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 1]
```diff
@@ -156,8 +156,12 @@
...
     private boolean showDescription;
     private String selectedTabTag;
-    @AttrRes @NonNull final List<Integer> tabIcons = new ArrayList<>();
-    @StringRes @NonNull final List<Integer> tabContentDescriptions = new ArrayList<>();
+    @AttrRes
+    @NonNull
+    final List<Integer> tabIcons = new ArrayList<>();
+    @StringRes
+    @NonNull
+    final List<Integer> tabContentDescriptions = new ArrayList<>();
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:164]: Restore this

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 2]
```diff
@@ -672,8 +676,8 @@ protected void initListeners() {
             if (motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
                 animate(binding.touchAppendDetail, true, 250, AnimationType.ALPHA,
                         0, () ->
-                        animate(binding.touchAppendDetail, false, 1500,
-                                AnimationType.ALPHA, 1000));
+                                animate(binding.touchAppendDetail, false, 1500,
+                                        AnimationType.ALPHA, 1000));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:680]: And this

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 3]
```diff
@@ -1009,6 +1013,11 @@ private boolean shouldShowComments() {
     }
 
     public void updateTabLayoutVisibility() {
+
+        if (binding == null) {
+            //If binding is null we do not need to and should not do anything with its object(s)
+            return;
+        }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1020]: Maybe also add a space below here

**Review by Stypox — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (sauravrao637) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:164]: My IDE automatically reformat the code , I had to do editing in github file itself :)
Is there some way so that it does not do this ?

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 2 above)
Comment (sauravrao637) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:676]: I am not able to resolve this , if you can request the changes I'll merge it and will be thankful if you help me out

Comment (sauravrao637) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:676]: If i don't reformat the code , it gives checkstyle violation :(

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java]: What IDE are you using? Android studio doesn't do that usually

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 4]
```diff
@@ -672,8 +672,8 @@ protected void initListeners() {
             if (motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
                 animate(binding.touchAppendDetail, true, 250, AnimationType.ALPHA,
                         0, () ->
-                        animate(binding.touchAppendDetail, false, 1500,
-                                AnimationType.ALPHA, 1000));
+                                animate(binding.touchAppendDetail, false, 1500,
+                                        AnimationType.ALPHA, 1000));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:676]: Oh, strange, this shouldn't happen. Try to apply this suggestion:
```suggestion
                        animate(binding.touchAppendDetail, false, 1500,
                                AnimationType.ALPHA, 1000));
```

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 3 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1016]: It is still not there

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (sauravrao637) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java]: Android Studio with some altered settings

**Review by Stypox — APPROVED** [review]
Thank you and sorry for being nitpicking :-D

**Comment by sauravrao637** [comment]
@Stypox  Thanks for helping out  and it's fine ,I am new here so would love to learn and suggestions are always welcome :)
