### PR TITLE
Fix notifying about old "new" streams

### LINKED ISSUE #10237: Repeated duplicate notification for subscription
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Subscribe to lastweektonight
2. Watch videos as they arrive
3. Sometimes, you get notifications for an episode you've already watched. Typically one of the two latest ones.

### Expected behavior

Since I've already seen it, I'd expect no notification for that episode

### Actual behavior

The notification re-appears at semi-regular intervals.

### Screenshots/Screen recordings

Screenshot_20230716-155055

### Logs

_No response_

### Affected Android/Custom ROM version

Android 13, June 2023 security patches

### Affected device model

Pixel 7a

### Additional information

I have seen this for quite a while, and it appears to happen more often now than before. It currently alternates between notifying for "FYC" and "Timeshares" so maybe these are switching location in the page layout or something?

### LINKED ISSUE #10553: Notifications (get notified) for uploads from EXACTLY 3 month ago | Bug?
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. subscribe to a channel
2. activate Notifications
3. activate "get notified"

### Expected behavior

Get Notifications **only** for new videos.

### Actual behavior

Receive notifications for **exactly 3 month old** videos, alongside the correct upload notifications

### Screenshots/Screen recordings

_No response_

### Logs

no logs to provide, because there is no crash.

### Affected Android/Custom ROM version

Android 13 (iodéOS 4.6)

### Affected device model

star2lte

### Additional information

https://github.com/TeamNewPipe/NewPipe/issues/10237 addresses a different notification issue.

A few out of many examples: 

- got notified on 08.Nov for an upload from 08.Aug
- got notified on 06.Nov for an upload from 06.Aug
and so on

There where never a current notification for the channel I got notified for the 3 month old video, but it could be that there where notifications for current videos from other channels parallel.

My language and local setting in Android are:
Englisch (Germany)
so the time format is: dd.mm.yyyy

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
After fetching new streams for the feed, "old" streams are removed from the database. However, if a channel contains only streams which are considered old, they are also removed. Thus they are shown as new when refreshing the feed the next time. For a more detailed explanation, [read this comment](https://github.com/TeamNewPipe/NewPipe/issues/10237#issuecomment-1750176520) in the original issue.

#### Fixes the following issue(s)
- Fixes #10237
- Fixes #10553

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt [hunk 1]
```diff
@@ -93,18 +93,28 @@ abstract class FeedDAO {
...
-            ON s.uid = f.stream_id
-
-            WHERE s.upload_date < :offsetDateTime
-        )
+        DELETE FROM feed
+        WHERE feed.stream_id IN (SELECT uid from (
+              SELECT s.uid,
+              (SELECT MAX(upload_date)
+                    FROM streams
+                    WHERE uploader_url = s.uploader_url) max_upload_date
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt:111]: Comparing based on the uploader url is hacky, and may not work e.g. for channels where youtube may return different uploader urls (e.g. Vevo and non-Vevo channels). I tested this alternative manually on my database, and it didn't return any duplicates, while yours did. Returning duplicates is not that bad, but it might still prevent some videos feed entries from ever being deleted.
```suggestion
              (SELECT MAX(upload_date)
                    FROM streams s1
                    INNER JOIN feed f1
                    ON s1.uid = f1.stream_id
                    WHERE f1.subscription_id = f.subscription_id) max_upload_date
```

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you for creating a test!
