### PR TITLE
more dl features

### LINKED ISSUE #345: Allow resume of download
Hey,
I tried downloading a video but didn't finish the download (about 30% downloaded). When I tried to resume the download a few days later it said "Error" in the download (probably cause some link expired). It would be awesome to be able to resume the download but apparently it just overwrites the already-downloaded file with the new one.

Thanks.

### LINKED ISSUE #938: Regenerate expired links
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Please add the feature to refresh the download link after it expires. Currently the only way is to delete the failed download and try again. Too bad for someone who has a very slow internet, like me

### LINKED ISSUE #2111: Downloading large capacity videos will fail
screenshot_2019-02-10-16-47-12-892_org schabi newpipe

### LINKED ISSUE #2451: Newpipe doesn't reload the expired links
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

If we pause a download for a few hours, we can't resume it because the link is expired. The error message is "403 not found". Can you please make it so newpipe can reload the page automatically when the link expired and resume the download.

### LINKED ISSUE #2542: Repack OPUS to OGG container
I noticed that the files from the OPUS downloads are encapsulated in a WEBM container (WEBM is a video+audio container). That's maybe OK for VLC, but it's bad for other (audio only) players.
As audio only, OPUS should be encapsulated in an OGG container (just like VORBIS), but unlike OGG-Vorbis that uses the OGG extension, OGG-OPUS should use the extension OPUS, see below.

I also noticed that the OPUS formats 249, 250 and 251 have a WEBM container as default.
So we need to repack the OPUS stream (without transcoding it) from the WEBM to an OGG container after the download is done. 
```
# youtube-dl output with -F or --list-formats

format code  extension  resolution note
249          webm       audio only DASH audio   50k , opus @ 50k, ?.??MiB
250          webm       audio only DASH audio   63k , opus @ 70k, ?.??MiB
251          webm       audio only DASH audio  123k , opus @160k, ?.??MiB
```
From: https://tools.ietf.org/html/rfc7845#section-9
```
9.  Content Type

   An "Ogg Opus file" consists of one or more sequentially multiplexed
   segments, each containing exactly one Ogg Opus stream.  The
   RECOMMENDED mime-type for Ogg Opus files is "audio/ogg".

   If more specificity is desired, one MAY indicate the presence of Opus
   streams using the codecs parameter defined in [RFC6381] and
   [RFC5334], e.g.,

                            audio/ogg; codecs=opus

   for an Ogg Opus file.

   The RECOMMENDED filename extension for Ogg Opus files is '.opus'.
```

### LINKED ISSUE #2676: Videos in WebM and 3GP containers are not seekable
Don't know if it's actually a bug or not, but at least on my device (Moto G6 Plus) noticed NewPipe (0.17.3) downloads videos in WebM and 3GP containers (both use VP9 video and Opus audio formats) that are not seekable, unlike MP4. I played the files on MX Player on Android and Media Player Classic on Windows and in neither of them seeking worked properly. However, seeking works just fine on WebM videos downloaded with JDownloader 2 Windows application, on both applications mentioned. I believe seeking would also work in 3GP videos, but this container doesn't show up in the list of available ones, only Matroska, MP4 and WebM.

Using well known MediaInfo tooI to analyse the same video, NewPipe WebM video uses Format version 2, while jDownloader uses version 4 and employs Lavf to encode the videos. I wonder if that difference might be related to why video seeking feature works in one application but not in other.

Also unsure whether it's a related issue to mine, but in another issue in which a user relates that an Opus audio file downloaded with NewPipe is not seekable, apparently because it's not encapsulated in the appropriate (OGG) container: https://github.com/TeamNewPipe/NewPipe/issues/2340.

### PR DESCRIPTION
**Pull request by kapodamy**
This pull request does:
- download opus (webm files) as ogg. close #2542 close #938
- recover expired downloads, resolve #2451 fix #345
- show a proper description on the error reporter when a download fails
- possible fix for #2640 (cut-off audio in m4a). fixes #2111
- possible fixes for #2634 and #2429
- calculate eta

required:
- [x] NPE change (https://github.com/TeamNewPipe/NewPipeExtractor/pull/199)
- [x] seeking is not available in webm (regresion from #2149) fixes #2676

[ ✔ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Would it be possible to retain .opus for Ogg Opus files? Or is that a hard requirement for the fix?

It's not a deal breaker, but I find it convenient to tell apart between my Ogg Vorbis and Ogg Opus files by looking at the extensions rather than having to open MediaInfo or similar utilities.

Ogg Vorbis streams, if present, should certainly have the .ogg (or .oga) extension.

**Comment by kapodamy** [comment]
@opusforlife2 yes, is possible

**Comment by kapodamy** [comment]
@TobiGr can you take a look on https://github.com/TeamNewPipe/NewPipeExtractor/pull/199

**Comment by TobiGr** [comment]
@kapodamy I'll merge the extractor PR after a rebase. Can you rebase this PR, too? We won't wait for the other PRs because their authors do not respond / apply the requested changes.

**Comment by kapodamy** [comment]
@TobiGr ok

**Comment by TobiGr** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Throwable java.lang.Throwable.getCause()' on a null object reference
        at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:319)
        at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:308)
        at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:145)
```
This happened when I turned off wifi while downloading. I got the normal error screen. I might be better to modify the notification to promt the error. When taping on the notification or the unfinished item in the downloads view, more info should be displayed.

**Comment by TobiGr** [comment]
image
I know there is few space. But `@` seems to be wrong here. Maybe something like `0:42 left/remaining`

**Comment by kapodamy** [comment]
@TobiGr NPE is not working for me

using 
`implementation 'com.github.TeamNewPipe:NewPipeExtractor:5c420340ceb39'`
or
`implementation 'com.github.TeamNewPipe:NewPipeExtractor:b6d3252'` i get:
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=v-RE7RUzjf8
* __Content Language:__ AR
* __Service:__ YouTube
* __Version:__ 0.17.4
* __OS:__ Linux Android 7.0 - 24


<details><summary><b>Crash log</b></summary><p>

```
org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'property="og:restrictions:age"'
	at org.jsoup.select.QueryParser.parse(QueryParser.java:44)
	at org.jsoup.select.Selector.select(Selector.java:91)
	at org.jsoup.nodes.Element.select(Element.java:363)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:700)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14826)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
</p></details>
<hr>

**Comment by kapodamy** [comment]
now the ETA looks like
Screenshot_1574786435

File: app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java [hunk 1]
```diff
@@ -2,6 +2,15 @@
 
 import android.content.Context;
 import android.os.Bundle;
+import androidx.annotation.NonNull;
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java]: These imports are unused

File: app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+import org.schabi.newpipe.extractor.stream.AudioStream;
+import org.schabi.newpipe.extractor.stream.Stream;
+import org.schabi.newpipe.extractor.stream.SubtitlesStream;
+import org.schabi.newpipe.extractor.stream.VideoStream;
+
+import java.io.Serializable;
+
+public class MissionRecoveryInfo implements Serializable, Parcelable {
+    private static final long serialVersionUID = 0L;
+    //public static final String DIRECT_SOURCE = "direct-source://";
```
Comment (TobiGr) [inline app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.java]: I guess this can be removed

File: app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java [hunk 3]
```diff
@@ -0,0 +1,434 @@
...
+        /* step 1: get the amount of frames per seconds */
+        switch (webm_track.kind) {
+            case Audio:
+                resolution = getSampleFrequencyFromTrack(webm_track.bMetadata);
+                if (resolution == 0f) {
+                    throw new RuntimeException("cannot get the audio sample rate");
+                }
+                break;
+            case Video:
+                // WARNING: untested
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java]: What does this mean?

File: app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java [hunk 4]
```diff
@@ -0,0 +1,434 @@
...
+        if ("A_OPUS".equals(webm_track.codecId)) {
+            return new byte[]{
+                    0x4F, 0x70, 0x75, 0x73, 0x54, 0x61, 0x67, 0x73,// "OpusTags" binary string
+                    0x07, 0x00, 0x00, 0x00,// writting application string size
+                    0x4E, 0x65, 0x77, 0x50, 0x69, 0x70, 0x65,// "NewPipe" binary string
+                    0x00, 0x00, 0x00, 0x00// additional tags count (zero means no tags)
+            };
+        } else if ("A_VORBIS".equals(webm_track.codecId)) {
+            return new byte[]{
+                    0x03,// ????????
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java]: ?

File: app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java [hunk 5]
```diff
@@ -0,0 +1,434 @@
...
+        // not implemented for the desired codec
+        return null;
+    }
+
+    private void write(ByteBuffer buffer) throws IOException {
+        output.write(buffer.array(), 0, buffer.position());
+        buffer.position(0);
+    }
+
+    //<editor-fold defaultstate="collapsed" desc="WebM track handling">
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java]: What are those comments for? Did I miss something before? There are some more `<editor>` comments below.

File: app/src/main/java/org/schabi/newpipe/streams/WebMReader.java [hunk 6]
```diff
@@ -15,7 +15,7 @@
  */
 public class WebMReader {
 
-    //<editor-fold defaultState="collapsed" desc="constants">
+    //<editor-fold defaultstate="collapsed" desc="constants">
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/streams/WebMReader.java]: and in this file, too

File: app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.java (hunk 2 above)
Comment (kapodamy) [reply app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.java]: yes

File: app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java (hunk 3 above)
Comment (kapodamy) [reply app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java]: ogg can be used for muxing a video stream (normally THEORA), but i never tested. is here beacause only took me 3 lines of code :)

File: app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java (hunk 4 above)
Comment (kapodamy) [reply app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java]: probably is the vorbis header version or the firs tag count. I do not know

File: app/src/main/java/org/schabi/newpipe/streams/WebMReader.java (hunk 6 above)
Comment (kapodamy) [reply app/src/main/java/org/schabi/newpipe/streams/WebMReader.java]: ¿what is wrong? the are "manual folding" comments [Code Folding - User Interface Specification](https://ui.netbeans.org/docs/ui/code_folding/cf_uispec.html#custom)

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/streams/WebMReader.java]: If I understand it correctly, these comments are used by NetBeans to collapse certain code fragments. But they do not belong in the main repository code. Please remove them.
I can understand that the collapsed code helps you with coding. I'd suggest you to put these comments into a single commit on another branch which allows you to cerry pick the editor comments when working locally.

**Comment by TobiGr** [comment]
Can you please check, why WebM with 720p downloads have no audio track? The same video with audio track is available when using 0.17.4, but not on your latest commit.

File: app/src/main/java/org/schabi/newpipe/streams/WebMReader.java (hunk 6 above)
Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/streams/WebMReader.java]: Thanks :+1:

**Comment by benymos** [comment]
Je ne comprends rien, il n'y a pas un lien pour télécharger newpipe 0.18.2

**Comment by Stypox** [comment]
@benymos download it from here: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.2
Click on the `NewPipe_v0.18.2.apk` button in the Assets menu.

Translated into French using DeepL // Traduit en français à l'aide de DeepL:
@benymos le télécharger ici: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.2
Cliquez sur le bouton `NewPipe_v0.18.2.apk` dans le menu Assets.
