### PR TITLE
Better popup resizing with pinch gestures

### LINKED ISSUE #515: Popup window resize
It would be nice to have some way to resize the pop-up window, not necessarily on the pop-up itself, some presets in the settings (like large, medium, small) should be enough

### LINKED ISSUE #2880: {Add Feature}popup resize problem
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Add a feature for popup video player to easy resize it.
Problem -- Many time size so big and lock  screen size.
https://apkpure.com/popup-video-player-multiple-popup-video-player/toolsdeveloper.popupvideoplayer
like the app show the button..

image -- https://image.winudf.com/v2/image/dG9vbHNkZXZlbG9wZXIucG9wdXB2aWRlb3BsYXllcl9zY3JlZW5fMF8xNTI1MjA0OTM3XzA3MQ/screen-0.jpg?h=355&fakeurl=1&type=.jpg

### LINKED ISSUE #2918: Resizing popup player
Popup player doesn't incrementally scale its size with gestures, but follow fingers until these not moving to the end of lateral display edges.

A pinch to zoom way could be much better.

### PR DESCRIPTION
**Pull request by harshlele**
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

The current popup window does resize with pinch gestures, but it's a bit weird. It resizes to the distance between the 2 fingers, and changes its position to one of the fingers. I changed it so that the window size scales to the pinch-in/out gesture and stays in the same position.

Fixes #515 fixes #2880 fixes #2918

APK:
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4184242/app-debug.zip)

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 1]
```diff
@@ -1082,25 +1106,52 @@ public boolean onTouch(View v, MotionEvent event) {
...
+                float firstPointerMoveY = event.getY(0) - initFirstPointerY;
+                float secPointerMoveX = event.getX(1) - initSecPointerX;
+                float secPointerMoveY = event.getY(1) - initSecPointerY;
+                //minimum threshold beyond which pinch gesture will work
+                int scaledTouchSlop = ViewConfiguration.get(PopupVideoPlayer.this).getScaledTouchSlop();
 
-            checkPopupPositionBounds();
-            updateScreenSize();
+                if(firstPointerMoveX > scaledTouchSlop ||firstPointerMoveY > scaledTouchSlop ||
+                        secPointerMoveX > scaledTouchSlop || secPointerMoveY > scaledTouchSlop){
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]:
```suggestion
                        secPointerMoveX > scaledTouchSlop || secPointerMoveY > scaledTouchSlop) {
```

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 2]
```diff
@@ -1082,25 +1106,52 @@ public boolean onTouch(View v, MotionEvent event) {
...
+                    double newWidth = popupWidth;
 
-            return true;
+                    //calculate current distance between the pointers
+                    float currentXDiff = event.getX(0) - event.getX(1);
+                    float currentYDiff = event.getY(0) - event.getY(1);
+                    double currentPointerDistance = Math.sqrt(currentXDiff * currentXDiff + currentYDiff * currentYDiff);
+
+                    //scale popup width
+                    double scale = 1 + (currentPointerDistance - initPointerDistance)/ initPointerDistance;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]: This is algebraically equal to:
```suggestion
                    double scale = currentPointerDistance / initPointerDistance;
```

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 3]
```diff
@@ -1082,25 +1106,52 @@ public boolean onTouch(View v, MotionEvent event) {
...
+
+                    newWidth = (popupWidth * scale);
+
+                    //change co-ordinates of popup so the center stays at the same position
+                    if(currentPointerDistance > initPointerDistance){
+                        popupLayoutParams.x -= (newWidth - popupWidth)/2;
+                    }
+                    else{
+                        popupLayoutParams.x += (popupWidth - newWidth)/2;
+                    }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]: This piece is also algebraically equal to:
```suggestion
                    popupLayoutParams.x += (popupWidth - newWidth) / 2;
```
Also, shouldn't you first normalize newWidth (i.e. doing `newWidth = (int) Math.min(screenWidth, newWidth);`)? Otherwise the popup center would be moved around. Or do the `checkPopupPositionBounds();` and `updateScreenSize();` functions prevent this?

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 4]
```diff
@@ -1082,25 +1106,52 @@ public boolean onTouch(View v, MotionEvent event) {
...
 
-            final int width = (int) Math.min(screenWidth, diff);
-            updatePopupSize(width, -1);
+                    double newWidth = popupWidth;
 
-            return true;
+                    //calculate current distance between the pointers
+                    float currentXDiff = event.getX(0) - event.getX(1);
+                    float currentYDiff = event.getY(0) - event.getY(1);
+                    double currentPointerDistance = Math.sqrt(currentXDiff * currentXDiff + currentYDiff * currentYDiff);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]: There is the [Java Math.hypot() function](https://www.tutorialspoint.com/java/lang/math_hypot.htm) that does exactly this
```suggestion
                    double currentPointerDistance = Math.hypot(event.getX(0) - event.getX(1), event.getY(0) - event.getY(1));
```

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 5]
```diff
@@ -1082,25 +1106,52 @@ public boolean onTouch(View v, MotionEvent event) {
...
+                    //scale popup width
+                    double scale = 1 + (currentPointerDistance - initPointerDistance)/ initPointerDistance;
+
+                    newWidth = (popupWidth * scale);
+
+                    //change co-ordinates of popup so the center stays at the same position
+                    if(currentPointerDistance > initPointerDistance){
+                        popupLayoutParams.x -= (newWidth - popupWidth)/2;
+                    }
+                    else{
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]:
```suggestion
                    } else {
```

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java (hunk 3 above)
Comment (harshlele) [reply app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]: Not sure if i got your question, but yeah `checkPopupPositionBounds()` checks whether the popup is outside the screen, `updateScreenSize()` just stores the screen size, and `updatePopupSize()` actually changes the popup size(and the width is normalised before that).

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]: Ok, I see, thank you for the answer

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 6]
```diff
@@ -1082,25 +1105,47 @@ public boolean onTouch(View v, MotionEvent event) {
...
+                float firstPointerMoveY = event.getY(0) - initFirstPointerY;
+                float secPointerMoveX = event.getX(1) - initSecPointerX;
+                float secPointerMoveY = event.getY(1) - initSecPointerY;
+                //minimum threshold beyond which pinch gesture will work
+                int scaledTouchSlop = ViewConfiguration.get(PopupVideoPlayer.this).getScaledTouchSlop();
 
-            checkPopupPositionBounds();
-            updateScreenSize();
+                if(firstPointerMoveX > scaledTouchSlop ||firstPointerMoveY > scaledTouchSlop ||
+                        secPointerMoveX > scaledTouchSlop || secPointerMoveY > scaledTouchSlop) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]:
```suggestion
                if (firstPointerMoveX > scaledTouchSlop || firstPointerMoveY > scaledTouchSlop
                        || secPointerMoveX > scaledTouchSlop || secPointerMoveY > scaledTouchSlop) {
```

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 7]
```diff
@@ -1082,25 +1105,47 @@ public boolean onTouch(View v, MotionEvent event) {
         private boolean handleMultiDrag(final MotionEvent event) {
             if (event.getPointerCount() != 2) return false;
 
-            final float firstPointerX = event.getX(0);
-            final float secondPointerX = event.getX(1);
+            if(initPointerDistance != -1){
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java]:
```suggestion
            if (initPointerDistance != -1) {
```

**Comment by Hubcapp** [comment]
I do prefer this behavior, but it seems that expanding isn't as smooth as it was with the weird "wherever your finger is" resize.

When i drag the popup box to the right side of the screen and expand, it remains the same size until I'm finished resizing it, but it moves the box over to the left.

For 4:3 video, you can see the black bars coming off the sides (why they need to be there at all for popup mode, i don't know, but it's an indicator that resizing is laggy)

**Comment by Oizaro** [comment]
@harshlele There is a little glitch during popup scaling, in practice animation doesn't correctly follow the fingers movements

**Comment by Oizaro** [comment]
Except this all working well.

**Comment by harshlele** [comment]
@Hubcapp @Oizaro  im not sure how to solve that problem. i tried a few things but its always a bit stuttery.

**Comment by harshlele** [comment]
@Stypox  is there like a linting test for the coding style so all these small coding style mistakes could be caught before I commit?

APK:
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4308230/app-debug.zip)

**Comment by Stypox** [comment]
@harshlele running Android Studio code refactoring on the files you changed should do the trick

**Comment by Stypox** [comment]
I tested this once again and could not find problems. I can't reproduce the issue pointed out by @Oizaro, but even if the bug exists I don't think it is really a big problem.
So could you @harshlele rebase and fix checkstyle problems, so than it can then be merged? Sorry for the delay ;-)

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 8]
```diff
@@ -1082,25 +1105,47 @@ public boolean onTouch(View v, MotionEvent event) {
...
 
-            return true;
+                    //calculate current distance between the pointers
+                    double currentPointerDistance = Math.hypot(event.getX(0) - event.getX(1),
+                                                                event.getY(0) - event.getY(1));
+
+                    //scale popup width
+                    double scale = currentPointerDistance / initPointerDistance;
+
+                    newWidth = (popupWidth * scale);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java:1130]: Remove the `double newWidth = popupWidth;` declaration above and put it directly here:
```suggestion
                    double newWidth = (popupWidth * scale);
```

File: app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java [hunk 9]
```diff
@@ -1082,25 +1105,47 @@ public boolean onTouch(View v, MotionEvent event) {
...
+
+                    //change co-ordinates of popup so the center stays at the same position
+                    popupLayoutParams.x += (popupWidth - newWidth)/2;
+
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java:1134]: Also remove some of these spaces and group similar/related statements toghether, to enhance readability
