### PR TITLE
Fix display of channel details when it has no videos

### LINKED ISSUE #5959: Can't subscribe to channels without videos
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Search Youtube for "subscribers without videos", tap on a channel that doesn't show any videos. 

The search term is just to find empty channels, I don't want to subscribe to those, but sometimes people announce new channels that don't have videos yet and it would be nice to have them in Newpipe so they show up in the new video feed once videos get uploaded.

### Actual behaviour

The channel header with subscribe button shows up for a moment, then gets replaced by a "No videos" message.

### Expected behavior

Channel header stays, the "No videos" message only occupies the space where the videos would go, so the subscribe button is always visible.

There's also a loading circle animation when looking for videos on a channel that seems to do the same and could also just be below the header instead of replacing it to keep the UI less busy.

### Device info

 - Android version/Custom ROM version:
 - Device model:

### PR DESCRIPTION
**Pull request by sauravrao637**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- in ChannelFragment.java do not throw emptyStateView error if no videos are present as there will be header in list which shows channel metadata and thus should be visible to user as expected by issue fix, also when there is no video the playlistController is hidden to prevent the app crash

- showEmptySpace() hides all the views in list including header when there is some error so it should be not called when there is header in the list, so changes are done accordingly in BaseListInfoFragment.java

#### Fixes the following issue(s)

- Fixes #5959

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java [hunk 1]
```diff
@@ -257,10 +261,13 @@ protected void setInitialData(final int sid, final String u, final String title)
     private void dynamicallyShowErrorPanelOrSnackbar(final ErrorInfo errorInfo) {
         if (infoListAdapter.getItemCount() == 0) {
             // show error panel only if no items already visible
+
```
Comment (mhmdanas) [inline app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java:264]: Please remove those empty lines you added

**Review by mhmdanas — CHANGES_REQUESTED** [review]

**Comment by mhmdanas** [comment]
Thanks for opening a PR! Please try to make your PR title more descriptive next time. Instead of "Fixes #ISSUE," instead put the issue itself. For example, see the edited title.

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java [hunk 2]
```diff
@@ -461,8 +460,13 @@ public void handleResult(@NonNull final ChannelInfo result) {
         if (menuRssButton != null) {
             menuRssButton.setVisible(!TextUtils.isEmpty(result.getFeedUrl()));
         }
-
-        playlistControlBinding.getRoot().setVisibility(View.VISIBLE);
+        //PlalistControls should be visible only if there is some item in
+        // infoListAdapter other than header
+        if (!(infoListAdapter.getItemCount() == 1)) {
```
Comment (mhmdanas) [inline app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:465]:
```suggestion
        if (infoListAdapter.getItemCount() != 1) {
```

**Review by mhmdanas — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java (hunk 1 above)
Comment (sauravrao637) [reply app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java:264]: Thanks a lot.
Any more suggestions are most welcome.
PlaylistController need to be modified such that if no videos and somehow there is a way user is able to interact with the controller then app should not crash .

**Comment by XiangRongLin** [comment]
@cybersphinx @sauravrao637 Can one of you provide a channel link where that is the case

**Comment by sauravrao637** [comment]
> @cybersphinx @sauravrao637 Can one of you provide a channel link where that is the case

Yeah Sure [here](https://www.youtube.com/channel/UCMzrBz4aRMfF349WFnJl_3Q) it is .
:)
or you can search "no videos channel" and filter by channel and browse one with no video

**Comment by peat80** [comment]
https://www.youtube.com/channel/UC4_2gEWKp78sE7MJMIqAZLQ

Try these one. 😀

**Comment by sauravrao637** [comment]
@mhmdanas  Hi, I am waiting for review please update soon :)

**Comment by sauravrao637** [comment]
Hi ! @XiangRongLin 
I think you by mistake labeled this "pull request" as bug

**Comment by XiangRongLin** [comment]
@sauravrao637 I can't reproduce the behaviour described in the issue with your provided channel on v0.20.10

File: app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java [hunk 3]
```diff
@@ -227,7 +228,9 @@ public void handleResult(@NonNull final I result) {
                 showListFooter(hasMoreItems());
             } else {
                 infoListAdapter.clearStreamItemList();
-                showEmptyState();
+                if (!(result instanceof ChannelInfo && infoListAdapter.getItemCount() == 1)) {
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java:231]: Please add a comment, why the item count must be 1 as you did below

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java [hunk 4]
```diff
@@ -461,8 +460,13 @@ public void handleResult(@NonNull final ChannelInfo result) {
         if (menuRssButton != null) {
             menuRssButton.setVisible(!TextUtils.isEmpty(result.getFeedUrl()));
         }
-
-        playlistControlBinding.getRoot().setVisibility(View.VISIBLE);
+        //PlalistControls should be visible only if there is some item in
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:463]:
```suggestion
        // PlalistControls should be visible only if there is some item in
```

**Review by TobiGr — COMMENTED** [review]
Thank you. Works for me. Please re-add the empty lines to increase readability.

**Comment by TobiGr** [comment]
@XiangRongLin that's interesting. It must be a regression introduced in 0.21.0. 0.20.11 works, too

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java (hunk 4 above)
Comment (mhmdanas) [reply app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:463]: Also should be `PlaylistControls` instead of `PlalistControls`.

**Comment by XiangRongLin** [comment]
> @XiangRongLin that's interesting. It must be a regression introduced in 0.21.0. 0.20.11 works, too.
> 
> I guess that was caused by #5148 

I can't read... i somehow read 0.21.0 in the issue as 0.20.10

I was already wondering if i should update my app, when i couldn't reproduce it.

**Review by sauravrao637 — COMMENTED** [review]
I've done the required changes :)
Please have a look

**Comment by sauravrao637** [comment]
> @sauravrao637 I can't reproduce the behaviour described in the issue with your provided channel on v0.20.10
Try with this one[https://www.youtube.com/channel/UCo0rk6fLb2V4SqBQwNBFuDA]( https://www.youtube.com/channel/UCo0rk6fLb2V4SqBQwNBFuDA)

**Review by XiangRongLin — APPROVED** [review]

**Comment by XiangRongLin** [comment]
@mhmdanas You need to remove your "Changes Requested" status before this can be merged. Otherwise the button is not clickeable

File: app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java [hunk 5]
```diff
@@ -462,7 +462,13 @@ public void handleResult(@NonNull final ChannelInfo result) {
             menuRssButton.setVisible(!TextUtils.isEmpty(result.getFeedUrl()));
         }
 
-        playlistControlBinding.getRoot().setVisibility(View.VISIBLE);
+        //PlaylistControls should be visible only if there is some item in
```
Comment (mhmdanas) [inline app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java:465]:
```suggestion
        // PlaylistControls should be visible only if there is some item in
```

**Review by mhmdanas — APPROVED** [review]

**Comment by mhmdanas** [comment]
@XiangRongLin done.

**Comment by XiangRongLin** [comment]
@sauravrao637 Can you squash it down to a single commit with the message set to the PR message. If i do it, the contributation may not show up on your profile.

**Comment by sauravrao637** [comment]
@XiangRongLin  , I did it after so many attempts :) but the message is "squash" :(

**Comment by XiangRongLin** [comment]
@sauravrao637 try this one https://www.git-tower.com/learn/git/faq/edit-fix-commit-message/

**Review by XiangRongLin — APPROVED** [review]
