### PR TITLE
Fix order of local search results

### LINKED ISSUE #7133: NewPipe v0.21.10 broke 'Search History' functionality
### Checklist
- [x] I am using the latest version - v0.21.10
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Press the search icon
2. Search YouTube for anything, say 'Taylor Swift' and click any of the search suggestions

### Actual behavior
The search itself works, but my searched text 'Taylor Swift' doesn't get added to my search history

### Expected behavior
The searched text 'Taylor Swift' should get added to my search history

### Device info
 - Android version/Custom ROM version: MIUI v12.0.3 running Android 10 32-bit
 - Device model: Xiaomi Redmi 7A (2GB RAM, 32GB storage, 17GB free space)

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Results from the local database were being fetched from the database in the correct order, but then the `DISTINCT` part of the query was not done by SQL but by Java using a `Set`, which then caused all items to be ordered alphabetically and not by creation date. This PR fixes this by having the related queries just return a list of strings that are already the correct ones and in the correct order. I just added `DISTINCT` to the queries.

#### Fixes the following issue(s)
Fixes #7133

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java [hunk 1]
```diff
@@ -36,16 +36,16 @@
...
     @Query("SELECT * FROM " + TABLE_NAME
             + " WHERE " + SERVICE_ID + " = :serviceId" + ORDER_BY_CREATION_DATE)
     @Override
     Flowable<List<SearchHistoryEntry>> listByService(int serviceId);
 
-    @Query("SELECT * FROM " + TABLE_NAME + " WHERE " + SEARCH + " LIKE :query || '%'"
-            + " GROUP BY " + SEARCH + " LIMIT :limit")
-    Flowable<List<SearchHistoryEntry>> getSimilarEntries(String query, int limit);
+    @Query("SELECT DISTINCT " + SEARCH + " FROM " + TABLE_NAME
+            + " WHERE " + SEARCH + " LIKE :query || '%'" + ORDER_BY_CREATION_DATE + " LIMIT :limit")
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java:49]: `` || ``

Shouldn't that be an "OR" - we are in SQL not Java :D

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java [hunk 2]
```diff
@@ -744,11 +741,11 @@ public boolean onBackPressed() {
                 .getRelatedSearches(query, similarQueryLimit, 25)
                 .toObservable()
                 .map(searchHistoryEntries -> {
-                    final Set<SuggestionItem> result = new HashSet<>(); // remove duplicates
-                    for (final SearchHistoryEntry entry : searchHistoryEntries) {
-                        result.add(new SuggestionItem(true, entry.getSearch()));
+                    final ArrayList<SuggestionItem> suggestionItems = new ArrayList<>();
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:744]: Maybe use java lambda(s) here.

Example:
```java
return searchHistoryEntries.stream()
    .map(entry -> new SuggestionItem(true,entry))
    .collect(Collectors.toList());
```

File: app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java (hunk 1 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java:49]: That's string concatenation

Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java:49]: Oh wow I didn't know that.
Normal SQL-languages use "CONCAT" or "+" for that but sqlite seems to be special in that case...

File: app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java [hunk 3]
```diff
@@ -244,9 +244,9 @@ private boolean isStreamHistoryEnabled() {
                 .subscribeOn(Schedulers.io());
     }
 
-    public Flowable<List<SearchHistoryEntry>> getRelatedSearches(final String query,
-                                                                 final int similarQueryLimit,
-                                                                 final int uniqueQueryLimit) {
+    public Flowable<List<String>> getRelatedSearches(final String query,
+                                                     final int similarQueryLimit,
+                                                     final int uniqueQueryLimit) {
```
Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java:249]: Do you want to try adding a test for this? Similiar to `LocalPlaylistManagerTest.kt`

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java (hunk 2 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java]: Done

File: app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java (hunk 3 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java:249]: Done, and I also found a bug, thank you for reminding me to write tests :-)

**Review by litetex — DISMISSED** [review]
LGTM;

Tested it - seems to work as expected.

👍 for the UnitTests

File: app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt [hunk 4]
```diff
@@ -0,0 +1,32 @@
+package org.schabi.newpipe.testUtil
+
+import androidx.room.Room
+import androidx.test.core.app.ApplicationProvider
+import org.junit.Assert.assertSame
+import org.schabi.newpipe.NewPipeDatabase
+import org.schabi.newpipe.database.AppDatabase
+
+class DatabaseMocker {
```
Comment (XiangRongLin) [inline app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt:9]: I find the naming misleading since it's not mocking the database but creating an actual in-memory database.

For me a mock is something where by default the methods return "nothing" or the closest thing to nothing (empty objects) unless one specifically defines what should be returned. This does not apply to the in-memory database.

**Review by XiangRongLin — COMMENTED** [review]
I haven't looked at the tests themselves.

File: app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt (hunk 4 above)
Comment (Stypox) [reply app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt:9]: Well, it is mocking NewPipeDatabase.databaseInstance with the in-memory database... How would you call it?

Comment (XiangRongLin) [reply app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt:9]: I think you have a different understanding from me if what a mock is.
I find this explanation decent https://stackoverflow.com/a/17810004

---

Going with that thread it would be a fake. But calling it `TestDatabase` would be fine too

Comment (XiangRongLin) [reply app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt:9]: A mock would be like in `ContentSettingsManagerTest`
https://github.com/TeamNewPipe/NewPipe/blob/ad405d9e0b63ac96949953f9fca0c125ee35f3c4/app/src/test/java/org/schabi/newpipe/settings/ContentSettingsManagerTest.kt#L56

Comment (Stypox) [reply app/src/androidTest/java/org/schabi/newpipe/testUtil/DatabaseMocker.kt]: Done

**Review by XiangRongLin — APPROVED** [review]
Tests look good 👍
