### PR TITLE
Load full stream info when enqueuing a stream

### LINKED ISSUE #7035: Queued videos metadata not properly updating
### Checklist

- [x] I am using the latest version - d9086300f310dd5a508824244dd9b84b9398bcff (debug build) >= 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any video
2. Queue any video loaded in fast mode where the duration/metadata of the video has not been loaded (no duration on the thumbnail)
3. Skip to the queued video

### Actual behavior

The metadata while loaded for the video is not updated in the player: the progress bar ends at 00:-1, you are unable to seek and the queue time report does not include the videos duration. However if you minimize the video the duration of the video is displayed on the thumbnail after the queued video starts playing.

### Expected behavior

Like when you play a video without metadata directly from the feed the loaded metadata should be shown in the player: duration should be correct and seeking should be available.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: N/A

### PR DESCRIPTION
**Pull request by Douile**
Please feel free to criticize the code here, I am not sure if I am using workers correctly or if there is a better way to do this. I essentially copied the code from https://github.com/TeamNewPipe/NewPipe/blob/faa7a91764cf633e668d9621eb6884b5db58bfa1/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L878-L906

I decided loading the information when adding to the queue is better than loading when the video starts playing as it allows the queue progress text to be correct as well. 

#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

This PR calls getStreamInfo causing a full network fetch of stream info (I believe only if required) when adding a stream item to the queue. This should prevent UI issues of missing metadata when queuing videos that have been fast-loaded and are missing metadata.

#### Fixes the following issue(s)

- Fixes #7035

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ktprograms** [comment]
I think how you're doing it now will always cause a full network fetch. The best way would probably be to check if (for example) the `item.getDuration()` is `null`, and only then doing the fetch. If it isn't `null`, you can just keep the old code (so have an `if` / `else` statement).

Here's the before and after of a similar case of adding the network fetch I recently implemented:
#### Before:
https://github.com/TeamNewPipe/NewPipe/blob/2b41f710a8cfa2ce8237de4a36bcba4b13dca78c/app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java#L32-L37
#### After:
https://github.com/TeamNewPipe/NewPipe/blob/faa7a91764cf633e668d9621eb6884b5db58bfa1/app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java#L36-L59

<hr/>

(In the after, `openChannelFragment` is a helper method that calls `NavigationHelper.openChannelFragment`):
https://github.com/TeamNewPipe/NewPipe/blob/faa7a91764cf633e668d9621eb6884b5db58bfa1/app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java#L209-L216

**Comment by GneHHHc233** [comment]
Hey, brother, thank you for solving the problem that my device YouTube can't get

**Comment by Stypox** [comment]
> The best way would probably be to check if (for example) the item.getDuration() is null, and only then doing the fetch. If it isn't null, you can just keep the old code (so have an if / else statement).

Yes, good idea. The stream info would anyway be fetched when the stream is loaded and played, but not fetching it beforehand is a good idea nonetheless.

**Comment by Douile** [comment]
Changes made in #6872 will conflict with this PR so I will wait for it to be merged before continuing here.

**Comment by Stypox** [comment]
> getStreamInfo does check the cache

There are "three" "stages" of stream loading:
1. stream info *item* loaded with fast feed, with some metadata fields, thus missing duration field
2. stream info *item* loaded with any other method (search, trending, ... including slow feed), with all metadata fields
3. stream info with all of the data needed to play

Stream info *item*s are those loaded alongside other stream info items (i.e. when fetching a list, e.g. search results, trending, feed, ...), while stream info is loaded e.g. when a video is opened or played.

If when calling `getStreamInfo` the 3rd type of stream loading was already done before, then the cache kicks in, otherwise it doesn't, since `getStreamInfo` aims to collect all of the data needed to play a video. So preventing an early call to `getStreamInfo` would be nice, as the cache would not kick in for most stream info items, unless they have already been opened.

**Comment by Stypox** [comment]
> Changes made in #6872 will conflict with this PR so I will wait for it to be merged before continuing here.

**Comment by Douile** [comment]
When new info is fetched the feed item still doesn't update, I'm not sure where to trigger this update.

**Comment by Douile** [comment]
Ayyy found it, https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L975-997

**Comment by Douile** [comment]
Nvm that was the wrong thing...

**Comment by Douile** [comment]
lmk if this needs a refactor because I'm not sure if it the best way of doing.

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 1]
```diff
@@ -203,4 +209,42 @@ private static void openChannelFragment(final Fragment fragment,
...
+    /////////////////////////////////////////////
+
+    private interface InfoCallback {
+        void onInfo(SinglePlayQueue item);
+    }
+
+    private static void fetchItemInfoIfSparse(final Fragment fragment,
+            final StreamInfoItem item,
+            final InfoCallback callback) {
+        if (item.getDuration() < 0) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:224]: The duration would be `< 0` even for live stream, but in that case fetching the info before enqueueing would not be any useful since the duration would still be `< 0`. So I'd do it like this:
```suggestion
        if ((item.getStreamType() == StreamType.LIVE_STREAM || item.getStreamType() == StreamType.AUDIO_LIVE_STREAM) && item.getDuration() < 0) {
```

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 2]
```diff
@@ -60,11 +62,15 @@
...
+                fullItem -> NavigationHelper.enqueueOnPlayer(fragment.getContext(), fullItem)
+        );
     }),
 
     enqueue_next(R.string.enqueue_next_stream, (fragment, item) -> {
-        NavigationHelper.enqueueNextOnPlayer(fragment.getContext(), new SinglePlayQueue(item));
+        fetchItemInfoIfSparse(fragment, item,
+                fullItem -> NavigationHelper.enqueueNextOnPlayer(fragment.getContext(), fullItem)
+        );
     }),
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:74]: Why did you only do it for enqueue? I also get the problem of the missing duration field in the play queue when I press on "Start playing on ..."

**Review by Stypox — CHANGES_REQUESTED** [review]
I can confirm it works when enqueueing a stream whose duration is unknown, thank you!

I get this crash when I long press an item in the fast feed, press on "Start playing in the background" and just after that I long press on another item. (both items are without duration before long pressing).

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Language:__ en
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 10 - 29


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.local.feed.FeedFragment.showStreamDialog(FeedFragment.kt:336)
	at org.schabi.newpipe.local.feed.FeedFragment.access$showStreamDialog(FeedFragment.kt:80)
	at org.schabi.newpipe.local.feed.FeedFragment$listenerStreamItem$1.onItemLongClick(FeedFragment.kt:395)
	at com.xwray.groupie.GroupieViewHolder$2.onLongClick(GroupieViewHolder.java:32)
	at android.view.View.performLongClickInternal(View.java:7339)
	at android.view.View.performLongClick(View.java:7297)
	at android.view.View.performLongClick(View.java:7315)
	at android.view.View$CheckForLongPress.run(View.java:27850)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</p></details>
<hr>

File: app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt [hunk 3]
```diff
@@ -159,6 +159,11 @@ class FeedFragment : BaseStateFragment<FeedState>() {
         }
     }
 
+    // TODO: Move
+    fun redrawContent() {
+        groupAdapter.notifyItemRangeChanged(0, Int.MAX_VALUE)
+    }
```
[the remark this answers is not in the document]
Comment (Douile) [reply app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt:165]: Ah forgot to remove this

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java (hunk 2 above)
Comment (Douile) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:74]: Ah, for some reason I neglected to check those options :)

**Comment by Stypox** [comment]
In order to fix the exception I posted above I think you just need to alter the `PlayerHolder.getQueueSize()` method to something along these lines
```java
if (!isPlayerOpen()) return 0;
final PlayQueue playQueue = player.getPlayQueue();
return playQueue == null ? 0 : playQueue.size();
```

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 4]
```diff
@@ -60,20 +62,31 @@
      * Info: Add this entry within showStreamDialog.
      */
     enqueue(R.string.enqueue_stream, (fragment, item) -> {
-        NavigationHelper.enqueueOnPlayer(fragment.getContext(), new SinglePlayQueue(item));
+        fetchItemInfoIfSparse(fragment, item,
+                fullItem -> NavigationHelper.enqueueOnPlayer(fragment.getContext(), fullItem)
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:66]: I think all lambda parameters should lie on the same line (also below) ;-)
```suggestion
        fetchItemInfoIfSparse(fragment, item, fullItem ->
                NavigationHelper.enqueueOnPlayer(fragment.getContext(), fullItem)
```

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 5]
```diff
@@ -60,20 +62,31 @@
...
+    }),
 
-    start_here_on_popup(R.string.start_here_on_popup, (fragment, item) ->
-            NavigationHelper.playOnPopupPlayer(fragment.getContext(),
-                    new SinglePlayQueue(item), true)),
+    start_here_on_popup(R.string.start_here_on_popup, (fragment, item) -> {
+        fetchItemInfoIfSparse(fragment, item, fullItem -> {
+                    NavigationHelper.playOnPopupPlayer(fragment.getContext(),
+                            fullItem, true);
+                });
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:88]: This is the correct formatting, though the braces are unneeded
```suggestion
        fetchItemInfoIfSparse(fragment, item, fullItem ->
                NavigationHelper.playOnPopupPlayer(fragment.getContext(), fullItem, true));
```

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 6]
```diff
@@ -203,4 +216,44 @@ private static void openChannelFragment(final Fragment fragment,
...
+        if (!(item.getStreamType() == StreamType.LIVE_STREAM
+                || item.getStreamType() == StreamType.AUDIO_LIVE_STREAM)
+                && item.getDuration() < 0) {
+            // Sparse item: fetched by fast fetch
+            ExtractorHelper.getStreamInfo(
+                    item.getServiceId(),
+                    item.getUrl(),
+                    false
+            )
+
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:240]:
```suggestion
```

**Review by Stypox — CHANGES_REQUESTED** [review]
Code now looks good, the formatting just needs to be fixed

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 7]
```diff
@@ -203,4 +209,43 @@ private static void openChannelFragment(final Fragment fragment,
...
     }
+
+    /////////////////////////////////////////////
+    // helper functions                        //
+    /////////////////////////////////////////////
+
+    private interface InfoCallback {
+        void onInfo(SinglePlayQueue item);
+    }
+
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:220]: Sorry for not noticing this before... instead of creating a new interface just for that one method you can use [a Java `Consumer<SinglePlayQueue>`](https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html). Just replace `InfoCallback` with `Consumer<SinglePlayQueue>` and replace `callback.onInfo` with `callback.accept`

**Review by Stypox — CHANGES_REQUESTED** [review]

**Review by Stypox — APPROVED** [review]
Works perfectly, thank you!

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 8]
```diff
@@ -203,4 +210,39 @@ private static void openChannelFragment(final Fragment fragment,
                 fragment.requireActivity().getSupportFragmentManager(),
                 item.getServiceId(), uploaderUrl, item.getUploaderName());
     }
+
+    /////////////////////////////////////////////
+    // helper functions                        //
+    /////////////////////////////////////////////
+
+    private static void fetchItemInfoIfSparse(final Fragment fragment,
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:218]: Why is the fragment used as param here? The only usage for fragment is `fragment.getContext()` in this method.

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 9]
```diff
@@ -203,4 +210,39 @@ private static void openChannelFragment(final Fragment fragment,
...
+            final StreamInfoItem item,
+            final Consumer<SinglePlayQueue> callback) {
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:220]: What is the advantage of using a consumer for a `SinglePlayQueue`? The method is more generic if the consumer accepts a `StreamInfoItem`.

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 10]
```diff
@@ -203,4 +210,39 @@ private static void openChannelFragment(final Fragment fragment,
...
+                                new HistoryRecordManager(fragment.getContext());
+                        recordManager.saveStreamState(result, 0)
+                                .subscribeOn(Schedulers.io())
+                                .observeOn(AndroidSchedulers.mainThread())
+                                .doOnError(throwable -> Log.e("StreamDialogEntry",
+                                        throwable.toString()))
+                                .subscribe();
+
+                        callback.accept(new SinglePlayQueue(result));
+                    }, throwable -> Log.e("StreamDialogEntry", throwable.toString()));
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:243]: I think we should report these error via the UI. Otherwise the user gets no feedback on his action if something fails. However, I am not sure how to handle network related errors here. @Stypox Any idea?

**Review by TobiGr — COMMENTED** [review]
While rebasing #7570 I ran into a few smaller things which I would like to get an answer / opinion on.

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java (hunk 9 above)
Comment (Douile) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:220]: This was because getStreamInfo returns a `StreamInfo` not a `StreamInfoItem`, forgive me if this exists but I didn't find a way to easily cast/convert between these types.

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java (hunk 10 above)
Comment (Douile) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:243]: Maybe we toast the user and fallback to returning the sparse info item then, although that still has its issues.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:243]: You could use an error notification, just like https://github.com/TeamNewPipe/NewPipe/pull/7538/files#diff-212f79b4111281cdfbffed5f79bca8922f99be14642ef90d524e6c9de9a436f7R66

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java (hunk 9 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:220]: Yes, this is ok
