### PR TITLE
Don't enable SAF on Fire TV

### LINKED ISSUE #6455: SAF file open/close dialogues can't be confirmed on FireTV (FireOS bug)
### Checklist

- [x] I am using the latest version - v0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

So this isn't really a bug by NewPipe. In fact NewPipe doesn't do anything wrong but the new SAF dialogue triggers a long standing bug/limitation in FireOS used on some Amazon FireTV devices.

The issue is that Amazon forgot to modify the SAF file open/save dialogues to make them work with a remote. While you can navigate them, it's not possible to confirm any selection made in these menus unless you are using a separate input device like a mouse.

My Fire TV Stick 4K running the latest FireOS 6 (based on Android 7.1) is affected by this issue. I don't know if newer FireTV devices running FireOS 7 (based on Android 9) are still affected by this.

If possible, one solution would be to detect FireOS TV devices and disable SAF by default for the time being.

Do you think it's worth spending time working around an OS bug like this?

Edit: Of course this bug only applies to Fire TVs and TV boxes. The SAF dialogues can be navigated perfectly fine on my Fire HD 10 tablet with its touch screen.

### Steps to reproduce the bug

1. Install NewPipe on an up to date FireTV 4K Stick
2. Leave the settings on default (SAF is turned on by default)
3. Use any option that causes the SAF file open/save dialogue to appear - for example try downloading a video
4. The SAF file save dialogue will appear.
5. You will notice that it's not possible to confirm this dialogue. For example in the save dialogue you won't be able to choose a folder for the default download location as you can't reach "select".

### Device info

 - Android version/Custom ROM version: FireOS 6 based on Android 7.1
 - Device model: Fire TV Stick 4K

### PR DESCRIPTION
**Pull request by mhmdanas**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR
Don't enable SAF when on Fire TV.

#### Fixes the following issue(s)

- Fixes #6455

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java [hunk 1]
```diff
@@ -35,6 +36,18 @@
     private DeviceUtils() {
     }
 
+    public static boolean isFireTv() {
+        if (isFireTV != null) {
+            return isFireTV;
+        }
+
+        final boolean isFireTv =
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java:44]: why do you create a new variable?

Comment (mhmdanas) [reply app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java:44]: I was just following the pattern of `isTv()` below. If you think it's not needed I can remove it.

File: app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java [hunk 2]
```diff
@@ -110,7 +111,9 @@ private static String getNewPipeChildFolderPathForDir(final File dir) {
     }
 
     public static boolean useStorageAccessFramework(final Context context) {
-        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
+        if (DeviceUtils.isFireTv()) {
+            return false;
+        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
             return true;
         } else if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
             return false;
```
Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java:119]: Can the 2 `return false` cases be combined with `||`?

Comment (mhmdanas) [reply app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java]: Done.

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java]: There should be a comment for each condition. I forgot to request that when reviewing the SAF PR.
```suggestion
        if (DeviceUtils.isFireTv()
            || Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
             // SAF file open/close dialogues can't be confirmed on FireTV (see #6455)
             // SAF is not supported on Android versions prior Lollipop
            return false;
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            return true;
```
@Stypox I forgot the reason for using SAF on Android 10 and above only.

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java]: Edit: delete me, I am stupid and late to the game :laughing:

Comment (mhmdanas) [reply app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java]: So is this fine as-is, or do I add a comment for Lollipop? I think the Lollipop part is fairly explanatory, while I added a comment for the FireTV part because it's not immediately obvious.

**Review by XiangRongLin — APPROVED** [review]
Codewise looks fine to me.

Please use squash merge

File: app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java (hunk 2 above)
Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java]: All good.
