### PR TITLE
Fix PlaylistAppendDialog showing when no local playlists exist

### LINKED ISSUE #4339: Add to playlist results in flashing if no playlist created before
### Version
- v0.19.8 / 0.20.0 RC

### Steps to reproduce the bug
1. Do a clean install or delete all created local playlists.
2. Search for a stream and long press on it to open the menu.
3a. Choose "Add to playlist" (or whatever it is called in the English version) or
3b Schedule the stream into the background player and click on the "Add to playlist"-button in the toolbar (more clearly visible)

### Expected behavior
The "create new playlist"-dialog should appear directly.

### Actual behaviour
**UI**: Before the actual dialog is visible there is a flash (sometimes)
**Code**: The app opens `PlaylistAppendDialog` and inflates the view. If no playlist exists it calls `dismiss` and opens `PlaylistCreationDialog`.

### PR DESCRIPTION
**Pull request by vkay94**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Added methods to `PlaylistDAO` and `LocalPlaylistManager` to get an observable for checking if there is a playlist
- Added method `checkPlaylists` to `PlaylistAppendDialog` which gives the opportunity to react on existing playlists
- Inserted the check into the three corresponding places (menus + background player)

#### Fixes the following issue(s)

- fixes #4339 

#### Testing apk

[app-debug-fix-createplaylist.zip](https://github.com/TeamNewPipe/NewPipe/files/5295452/app-debug-fix-createplaylist.zip)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java [hunk 1]
```diff
@@ -38,6 +40,27 @@
 
     private CompositeDisposable playlistDisposables = new CompositeDisposable();
 
+    public static Disposable checkPlaylists(
+            final Context context, final Invoker onSuccess, final Invoker onFailed
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java:44]: Maybe use different names here, like onPlaylistFound

File: app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java [hunk 2]
```diff
@@ -38,6 +40,27 @@
...
+                .subscribe(hasPlaylists -> {
+                    if (hasPlaylists) {
+                        onSuccess.invoke();
+                    } else {
+                        onFailed.invoke();
+                    }
+                });
+    }
+
+    public interface Invoker {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java:60]: You can just use a Runnable instead

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java [hunk 3]
```diff
@@ -126,4 +126,10 @@ public String getPlaylistThumbnail(final long playlistId) {
                 }).subscribeOn(Schedulers.io());
     }
 
+    public Maybe<Boolean> hasPlaylists() {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java:129]: Should't this return a Single? Is it impossible for the database getCount to return a Single? I might be wrong

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java [hunk 4]
```diff
@@ -40,8 +41,14 @@
 
     append_playlist(R.string.append_playlist, (fragment, item) -> {
         if (fragment.getFragmentManager() != null) {
-            PlaylistAppendDialog.fromStreamInfoItems(Collections.singletonList(item))
-                    .show(fragment.getFragmentManager(), "StreamDialogEntry@append_playlist");
+            final PlaylistAppendDialog d = PlaylistAppendDialog
+                    .fromStreamInfoItems(Collections.singletonList(item));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:45]: Maybe extract this code to a function so that it can be reused above

**Review by Stypox — COMMENTED** [review]
Thank you for looking into this! The changes look mostly good. :-D

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java (hunk 3 above)
Comment (vkay94) [reply app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java:129]: I've tried `Single` (`.single(0L)` on `Flowable`) but the `subscribe`-block won't be called (I logged it).

File: app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java (hunk 4 above)
Comment (vkay94) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:45]: I'm not sure what you mean by "extract" in this context. Probably a wrapper for the check- and show-logic? Something like one signature:

`static Disposable safeShow(context, fm, tag, <input>)`

where input is either `StreamInfo` or `List<StreamInfoItem>` or 'List<PlayQueueItem>' (by overriding).

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java:45]: Oh, sorry, since the two blocks of code actually do different things you can ignore this suggestion

**Comment by vkay94** [comment]
@Stypox I pushed your recommendations to the branch. Thanks for them! (Why didn't I think about the Runnable? xD - I'm too spoiled with Kotlin's built-in lambda as parameters ^^)

**Review by Stypox — APPROVED** [review]
Now code looks good to me, thank you again!

**Review by TobiGr — APPROVED** [review]
Fixed a merge conflict
