### PR TITLE
Fix clearing queue when tapping on timestamp

### LINKED ISSUE #11013: Tapping on timestamps clears queue (0.27.0 regression)
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

27.0

### Steps to reproduce the bug

I was previously using the NewPipe in version 26.x. I received alert a new version was avail and upgraded to 27.0.

I have always used the current Active playlist as a a 'Now Playing/Watch Later Queue'.

In version 27.0 I've had twice occurences when attempting to using the timestamp fragments/jump of the description of videos mess up the playlist.

 The first time (which I didn't record as it was unexpected) it appeared to wipe out the next  to be played videos and show me the current video and one new video to be played a previous already viewed "session". However despite that that old video was back in Active Queue it also didn't even play that video. 

The second time with the recording attached below. The Active Queue wipes out all the videos on the playlist both past and to be played.

In both cases the currently playing video also starts over back from the 0:00 position

Steps I think reproduce the error. 

1. Play a video with a timestamp fragment in the description
2. Search more videos in the search bar.
3. Use Enqueue and/or Enqueue Next mixture to add it to the current Active Playlist Queue
4. While video still playing click on the timestamp video 

### Expected behavior

The pop-out player should open and the video time should jump to the correct timestamp..

### Actual behavior

Pop-out player opens and playlist typically clears and current video is reset to 0:00 timestamp.

### Screenshots/Screen recordings

https://github.com/TeamNewPipe/NewPipe/assets/21159693/b54616b4-8661-424f-b20d-b9d448160801

### Logs

_No response_

### Affected Android/Custom ROM version

Android 13

### Affected device model

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Profpatsch**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

This is a fix for #11013 

But for the fix to work, I started cleaning up the Player intent handler a little.

I could possible have hacked it into the if/if/else chain somehow, but there’s just too many different ways to call the intent that it would have broken some other case.

So instead I opted for starting to rewrite the intent into a simple tagged enum value.
This refactor is only done until the point where I could make the fix so far though, see the commit descriptions.

I also simplified the handler in the first few commits, removing intent keys that were not set in any intent calls anymore. This is in theory a breaking change to the PlayerService intent, but I don’t consider that a public API of NewPipe that people use.

#### Before/After Screenshots/Screen Record

- Before:
  

https://github.com/user-attachments/assets/0f828b73-e3c1-4df5-ab68-9bded1fe3677

- After:

https://github.com/user-attachments/assets/c42205cf-921b-4924-a31e-c41c2f142c83

#### Fixes the following issue(s)

- Fixes #11013 

#### Relies on the following changes

- 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Profpatsch** [comment]
Edit: added videos

**Comment by SavSanta** [comment]
I was trying to test this out but didn't see a CIntab in the elft pane and thusly no napp apl to confirm the fix.

I do see the pipeline mentions:
```
Some checks haven't completed yet

2 expected, 2 successful checks
pending checks

build-and-test-jvmExpected — Waiting for status to be reported
Required
test-android (21, default, x86)
test-android (21, default, x86)Expected — Waiting for status to be reported
```

So presuming this is inhibiting articact creation?(Dunno don't use CI). So will check back later to see if I can test.

**Comment by Profpatsch** [comment]
@SavSanta Okay now the artifact is there, happy testing :)

**Comment by Profpatsch** [comment]
@SavSanta you can also test https://github.com/TeamNewPipe/NewPipe/pull/12254, which is all these changes plus the timestamps skips the current player instead of always opening the popup

**Comment by SavSanta** [comment]
> @SavSanta Okay now the artifact is there, happy testing :)

Unfortunately I'm going to my current job site where I won't have phone to do more explorative testing

> @SavSanta Okay now the artifact is there, happy testing :)

So I'm in a bit discombobulated. Just got back into country late last nite and I'm already off to work with no sleep where I also won't have my phone for my extensive gui testing.

 Tho I did a quick helter skelter test while on the train and I can corroborate at least that *heck yeah DUDE*. We must bow before you because I think your fix/mods worked. 


https://github.com/user-attachments/assets/dbe3331a-f19d-4081-bfe2-5794600191f1

File: app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java [hunk 1]
```diff
@@ -71,6 +71,22 @@ private PlayQueueItem(@Nullable final String name, @Nullable final String url,
...
+     * @return whether the two items are the same so the stream can be re-used.
+     */
+    public boolean isSameItem(@Nullable final PlayQueueItem other) {
+        if (other == null) {
+            return false;
+        }
+        // We assume that the same service & URL uniquely determines
+        // that we can keep the same stream running.
+        return getServiceId() == other.getServiceId()
+                && getUrl().equals(other.getUrl());
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java]: Doesn't matter much:
```suggestion
        return this.serviceId == other.serviceId
                && this.url.equals(other.url);
```

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 2]
```diff
@@ -359,6 +359,7 @@ public void handleIntent(@NonNull final Intent intent) {
         final PlayerType oldPlayerType = playerType;
         playerType = PlayerType.retrieveFromIntent(intent);
         initUIsForCurrentPlayerType();
+        // TODO: what does the following comment mean? Is that a relict?
         // We need to setup audioOnly before super(), see "sourceOf"
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: This remained here accidentally after https://github.com/TeamNewPipe/NewPipe/commit/f6e2dd1480a71fa61d8a285912beb11c9169c069, when there used to be 3 player classes one child of the other and where it made sense to do some stuff before calling the "super()" method. You can remove both comments

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 3]
```diff
@@ -367,22 +366,26 @@ public void handleIntent(@NonNull final Intent intent) {
...
-            if (playQueue != null) {
-                final int currentIndex = playQueue.getIndex();
-                playQueue.append(newQueue.getStreams());
-                playQueue.move(playQueue.size() - 1, currentIndex + 1);
+        switch (playerIntentType) {
+            case Enqueue -> {
+                if (playQueue != null) {
+                    playQueue.append(newQueue.getStreams());
+                }
+                return;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: Early returning here can leave the player in an invalid state, but you already fixed it in the latest commit

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 4]
```diff
@@ -344,18 +352,31 @@ public int getOverrideResolutionIndex(final List<VideoStream> sortedVideos,
...
+        // TODO: this should be in the second switch below, but I’m not sure whether I
+        // can move the initUIs stuff without breaking the setup for edge cases somehow.
+        switch (playerIntentType) {
+            case TimestampChange -> {
+                // TODO: this breaks out of the pattern of asking for the permission before
+                // sending the PlayerIntent, but I’m not sure yet how to combine the permissions
+                // with the new enum approach. Maybe it’s better that the player asks anyway?
+                if (!PermissionHelper.isPopupEnabledElseAsk(context)) {
+                    return;
+                }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:370]: This early return will leave the player in an uninitialized state with a broken notification, if the player was closed before. But this comment is not relevant if we also merge #12254.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 5]
```diff
@@ -365,29 +386,63 @@ public void handleIntent(@NonNull final Intent intent) {
...
+                        ExtractorHelper.getStreamInfo(dat.getServiceId(), dat.getUrl(), false);
+                streamItemDisposable.add(single.subscribeOn(Schedulers.io())
+                        .observeOn(AndroidSchedulers.mainThread())
+                        .subscribe(info -> {
+                            final PlayQueue newPlayQueue = new SinglePlayQueue(info,
+                                    dat.getSeconds() * 1000L);
+                            NavigationHelper.playOnPopupPlayer(context, playQueue, false);
+                        }, throwable -> {
+                            final var errorInfo = new ErrorInfo(throwable, UserAction.PLAY_ON_POPUP,
+                                    dat.getUrl());
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: Remove

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 6]
```diff
@@ -365,29 +386,63 @@ public void handleIntent(@NonNull final Intent intent) {
...
+                            // This will only show a snackbar if the passed context has a root view:
+                            // otherwise it will resort to showing a notification, so we are safe
+                            // here.
+                            ErrorUtil.showSnackbar(context,
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: showNotification

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 7]
```diff
@@ -365,29 +386,63 @@ public void handleIntent(@NonNull final Intent intent) {
...
                 if (playQueue != null) {
+                    final PlayQueue newQueue = getPlayQueueFromCache(intent);
+                    if (newQueue == null) {
+                        return;
+                    }
                     final int currentIndex = playQueue.getIndex();
                     playQueue.append(newQueue.getStreams());
                     playQueue.move(playQueue.size() - 1, currentIndex + 1);
                 }
                 return;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: Shouldn't `handleIntentPost(oldPlayerType);` be called also before each early return?

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 8]
```diff
@@ -347,49 +352,141 @@ public int getOverrideResolutionIndex(final List<VideoStream> sortedVideos,
...
-            return;
+        final PlayerType newPlayerType;
+        // TODO: this should be in the second switch below, but I’m not sure whether I
+        // can move the initUIs stuff without breaking the setup for edge cases somehow.
+        switch (playerIntentType) {
+            case TimestampChange -> {
+                // TODO: this breaks out of the pattern of asking for the permission before
+                // sending the PlayerIntent, but I’m not sure yet how to combine the permissions
+                // with the new enum approach. Maybe it’s better that the player asks anyway?
+                if (!PermissionHelper.isPopupEnabledElseAsk(context)) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:368]: You can't call this with the service context, since the service has no UI

Comment (Profpatsch) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:368]: fixed in the commit of https://github.com/TeamNewPipe/NewPipe/pull/12254

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 7 above)
Comment (Profpatsch) [reply app/src/main/java/org/schabi/newpipe/player/Player.java]: Last commit
