### PR TITLE
Fix crash on startup when there is no internet connection

### LINKED ISSUE #4920: App crashes when launched without internet
### Checklist

- [x] I am using the latest version - 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Close NewPipe (if open)
2. Remove the app from Recents
3. Disconnect the device from the internet
4. Launch NewPipe

### Actual behaviour

App crashes.
(Unfortunately, NewPipe has stopped.)

### Expected behavior

In the previous release (v0.20.2), the app would open without internet.

### Screen recording

final-4920

### Device info

 - Android version/Custom ROM version: Android 6.0.1
 - Device model: Samsung SM-G550FY

I could reproduce this on 2 devices.

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
The crash was caused by an `Observable`'s `Callable` returning `null` when fetching the latest available app version without internet connection, but RxJava's `Observable`s do not accept `null` results. So I used a `Maybe` instead, and removed a `null` check inside the subscriber since nullity is already taken care of by the `Maybe`. I also did some refactoring in the `CheckForNewAppVersion` file.

A further crash was caused by the `onError()` interface not being implemented. That produced a crash instead of handling the connectivity error.

#### Fixes the following issue(s)
Fixes #4920

#### APK testing 
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5577476/app-debug.zip)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xibr** [comment]
Can confirm that it's fixed now.
Thanks

**Comment by TobiGr** [comment]
@Stypox I changed 
https://github.com/TeamNewPipe/NewPipe/blob/8bcf0c64983bc1c72eeb8b8c9fa289dad8a5149a/app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java#L173-L175

to return true and get this error with no internet connection:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.schabi.newpipe.debug, PID: 7060
    java.lang.IllegalAccessError: Method 'void org.schabi.newpipe.report.ErrorInfo.<init>(org.schabi.newpipe.report.UserAction, java.lang.String, java.lang.String, int)' is inaccessible to class 'org.schabi.newpipe.report.ErrorInfo$Creator' (declaration of 'org.schabi.newpipe.report.ErrorInfo$Creator' appears in /data/app/~~PspBUZrsPUhmRQWJlecdjQ==/org.schabi.newpipe.debug-w9bjRJSRX4HK0ZrNMsAJkw==/base.apk!classes2.dex)
        at org.schabi.newpipe.report.ErrorInfo$Creator.createFromParcel(Unknown Source:39)
        at android.os.Parcel.readParcelable(Parcel.java:3281)
        at android.os.Parcel.readValue(Parcel.java:3174)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getParcelable(Bundle.java:1001)
        at android.content.Intent.getParcelableExtra(Intent.java:8276)
        at org.schabi.newpipe.report.ErrorActivity.onCreate(ErrorActivity.java:209)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/ACRA: ACRA caught a IllegalAccessError for org.schabi.newpipe.debug
    java.lang.IllegalAccessError: Method 'void org.schabi.newpipe.report.ErrorInfo.<init>(org.schabi.newpipe.report.UserAction, java.lang.String, java.lang.String, int)' is inaccessible to class 'org.schabi.newpipe.report.ErrorInfo$Creator' (declaration of 'org.schabi.newpipe.report.ErrorInfo$Creator' appears in /data/app/~~PspBUZrsPUhmRQWJlecdjQ==/org.schabi.newpipe.debug-w9bjRJSRX4HK0ZrNMsAJkw==/base.apk!classes2.dex)
        at org.schabi.newpipe.report.ErrorInfo$Creator.createFromParcel(Unknown Source:39)
        at android.os.Parcel.readParcelable(Parcel.java:3281)
        at android.os.Parcel.readValue(Parcel.java:3174)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.Bundle.getParcelable(Bundle.java:1001)
        at android.content.Intent.getParcelableExtra(Intent.java:8276)
        at org.schabi.newpipe.report.ErrorActivity.onCreate(ErrorActivity.java:209)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Stypox** [comment]
@TobiGr I approve your changes. I added a PR to move all of the error handling in one place (no need to try-catch in the callable, if the exception would be handled by the error lambda). I also used the shortand way to log exceptions with also a message (i.e. `Log.w(TAG, msg, exception)`, which, by looking at the code, is equal to `Log.w(TAG, msg + '\n' + getStackTraceString(exception))`). I tested as you said and also disabled the connectivity check at the top of the callable, to force network issues in the downloader, and everything works as expected.

**Comment by Stypox** [comment]
Apk with `isGithubApk` returning always `true` and connectivity checks disabled: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5579477/app-debug.zip)

File: app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java [hunk 1]
```diff
@@ -218,15 +208,14 @@ public static Disposable checkNewVersion(@NonNull final App app) {
...
                                 }
                             }
                         },
-                        throwable -> {
+                        e -> {
                             // connectivity problems, do not alarm user and fail silently
                             if (DEBUG) {
-                                Log.i(TAG, "Could not get NewPipe API: network problem");
-                                Log.i(TAG, Log.getStackTraceString(throwable));
+                                Log.w(TAG, "Could not get NewPipe API: network problem", e);
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java:218]: i just thought about checking whether there was really a network problem by calling `ExceptionUtils.isNetworkRelated(e)`

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java:218]: What else can it be? And even if the error was different, I don't think it would be an issue, since the whole stacktrace would be printed out anyway

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java:218]: ok

**Review by TobiGr — APPROVED** [review]
