### PR TITLE
Catch errors while processing timestamp-links

### LINKED ISSUE #6842: Clicking the 1st comment of this youtube video to expand exists & crashes newpipe to homescreen
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Newpipe exists to the homescreen which I believe is a form of crash. This does not invoke Guru Meditation or any other bug report pop-up

### Expected behavior

Expand the comment with ellipsis "..."

### Screenshots/Screen recordings

The comment which crashes the app in question

### Device info

 - Android version/Custom ROM version: Android 10, miui 12

 - Device model: Redmi 7a

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Catches errors while processing timestamp-links.

#### Fixes the following issue(s)
- Fixes #6842 

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by TobiGr** [comment]
Why is that method even called? This fixes the symtoms of parsing an unexpactedly structured URL. Shouldn't we take a closer look at the `PATTERN`?
```
(\\d+:)?(\\d+)?:(\\d+)
```
This regex looks like it is accepting more than it should.

**Comment by Stypox** [comment]
Maybe we should use:
```regex
(\\d{1,2}:)?(\\d{1,2})?:(\\d{1,2})
```

File: app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java [hunk 1]
```diff
@@ -53,20 +56,25 @@
...
+                }
+                if (minutes != null) {
+                    timestamp += (Integer.parseInt(minutes.replace(":", "")) * 60);
+                }
+                if (seconds != null) {
+                    timestamp += (Integer.parseInt(seconds));
+                }
+                return streamUrl + url.replace(match.group(0), "#timestamp=" + timestamp);
+            } catch (final Exception ex) {
+                Log.d(TAG, "Unable to process url='" + url + "' as timestampLink", ex);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java:75]: I think this would also be good as an error
```suggestion
                Log.e(TAG, "Unable to process url='" + url + "' as timestampLink", ex);
```

**Review by Stypox — CHANGES_REQUESTED** [review]

**Comment by litetex** [comment]
I think a problem with using
```
(\\d{1,2}:)?(\\d{1,2})?:(\\d{1,2})
```

Is that you get cut-off results like:
grafik

Should we stick with the old implementation?

Btw: Is it correct that even results like ``:12`` are consider valid?

**Comment by Stypox** [comment]
> Is that you get cut-off results like:

Oh ok, then nevermind. Just keep the current one, but check that minutes and seconds are <= 60

> Btw: Is it correct that even results like :12 are consider valid?

I think so, but as @TiA4f8R

**Comment by Stypox** [comment]
Wait, but why isn't `TextLinkifier` used? There the correct timestamps patter is used (we worked on it together a couple hours on Element):
```java
(?:^|(?!:)\W)(?:([0-5]?[0-9]):)?([0-5]?[0-9]):([0-5][0-9])(?=$|(?!:)\W)
```

**Comment by Stypox** [comment]
Using `TextLinkifier.TIMESTAMPS_PATTERN` and this code for `timestampLink` seems to work for me. Using `TextLinkifier` wouldn't work since it would disable clicks on the text view.
```java
    private final Linkify.TransformFilter timestampLink = new Linkify.TransformFilter() {
        @Override
        public String transformUrl(final Matcher match, final String url) {
            final int timestampStart = match.start(2);
            final int timestampEnd = match.end(3);
            final String parsedTimestamp = commentText.substring(timestampStart, timestampEnd);
            final String[] timestampParts = parsedTimestamp.split(":");

            final int seconds;
            if (timestampParts.length == 3) { // timestamp format: XX:XX:XX
                seconds = Integer.parseInt(timestampParts[0]) * 3600 // hours
                        + Integer.parseInt(timestampParts[1]) * 60 // minutes
                        + Integer.parseInt(timestampParts[2]); // seconds
            } else if (timestampParts.length == 2) { // timestamp format: XX:XX
                seconds = Integer.parseInt(timestampParts[0]) * 60 // minutes
                        + Integer.parseInt(timestampParts[1]); // seconds
            } else {
                return url;
            }
            return streamUrl + url.replace(match.group(0), "#timestamp=" + seconds);
        }
    };
```

**Comment by litetex** [comment]
I'm also currently writing some unit-tests and fun fact:
"Timestamp format: XX:XX:XX" never works because the wrong group (it should be group 1 but it's group 2) is matched 😆 

So e.g. 1:23:45 becomes 1425s (23:45) when it should be 5025s

Fixing it on the fly

File: app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * Extracts timestamps.
+ */
+public final class TimestampExtractor {
+    public static final Pattern TIMESTAMPS_PATTERN = Pattern.compile(
+            "(?:^|(?!:)\\W)(?:([0-5]?[0-9]):)?([0-5]?[0-9]):([0-5][0-9])(?=$|(?!:)\\W)");
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java:11]: Why stop with hours at `60`? I'd just make that illimitate: on a video 100 hours long, how could one target the 90th hour (e.g. 90:32:11)
```suggestion
            "(?:^|(?!:)\\W)(?:([0-9]+):)?([0-5]?[0-9]):([0-5][0-9])(?=$|(?!:)\\W)");
```

**Review by Stypox — CHANGES_REQUESTED** [review]

File: app/src/test/java/org/schabi/newpipe/util/external_communication/TimestampExtractorTest.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+@RunWith(Parameterized.class)
+public class TimestampExtractorTest {
+
+    @Parameterized.Parameter(0)
+    public Duration expected;
+
+    @Parameterized.Parameter(1)
+    public String stringToProcess;
+
+    @Parameterized.Parameters(name = "Expecting {0} for \"{1}\"")
```
Comment (Stypox) [inline app/src/test/java/org/schabi/newpipe/util/external_communication/TimestampExtractorTest.java:25]: Oh, does this look great :-D

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you, I like this implementation :-)

File: app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java (hunk 2 above)
Comment (opusforlife2) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java:11]: @Stypox ~illimitate~ limitless

Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java:11]: > Why stop with hours at `60`? I'd just make that ~illimitate~ limitless: on a video 100 hours long, how could one target the 90th hour (e.g. 90:32:11)

Some things to consider:
* Don't ask me I just copied it 😆, ask the inventor → https://github.com/TeamNewPipe/NewPipe/pull/6851#issuecomment-894060228
* Such a solution will throw an error if it exceeded the int limit
* Video lengths are capped on most platforms:
  * YouTube: max 12h
  Source: https://support.google.com/youtube/answer/71673
  * SonarCloud: max 6h 
  Source: https://help.soundcloud.com/hc/en-us/articles/115003452847-Uploading-requirements
  * Media CCC: ?
  * PeerTube: depends on the instance; clicked through a few instances and most of the have a contingent of ~20GB which are ~31h in average resolution video (I'm posting no links regarding peer tube instances, most of whom I visited host hoax videos - even though I searched with "Sensitive videos: blur")
  * Bandcamp: 600MB; mp3 min bitrate =96Kbps (according to [adobe](https://www.adobe.com/creativecloud/video/discover/audio-bitrate.html)) → 600MB / 96Kbps / 8 = ~781s = ~13h
  Source: https://get.bandcamp.help/hc/en-us/articles/360007901993-What-s-the-maximum-upload-size-

According to https://www.statista.com/statistics/1026923/youtube-video-category-average-length/ the average YT video has a length of ~12minutes. I myself rarely see/noticed videos which are longer than 1-2h.

According to the above the case of navigating to a video timestamp which is >60h is nearly zero. 
If there is such a case, it currently [simply doesn't detect the timestamp](https://regex101.com/r/EWQG8D/1) and the user has to move there by himself.

So I wouldn't change anything for now. 
If someone will ever have that problem, the person can open an issue.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TimestampExtractor.java:11]: Ok, you are right

**Review by Stypox — APPROVED** [review]

**Comment by opusforlife2** [comment]
@litetex Remember to always add a PR to the draft release whenever you merge it.
