### PR TITLE
Fix lingering focus highlight overlay

### LINKED ISSUE #3904: Issues with the white highlight box/marker on FireTV
When controlling NewPipe on a FireTV using the remote, selected on screen items have a white line around them.

Unfortunately there are a few situations where the highlight marker is displayed when it shouldn't be or its behaving unexpectedly.

Personally I would differentiate between 1 major annoyances and a few minor glitches/issues, of which 2 are worth reporting:

Major annoyance:

Topright
1. Enable autoplay
2. Wait for the next video to autoplay

Result: Now there will be a white box on top of the fullscreen video on the top right.

Solution: Press down on the remote to remove this box.

This is a major issue in my opinion as this issue occurs at the start of every autoplay video. In addition, in the long term there is the chance of burnout on OLED screens.

Then there are a few minor issues/glitches, 2 of which are worth reporting:

Minor annoyance 1:

Middle
1. Open the on screen menu with the "back", "play/pause", "forward" menu items
2. Close this menu 
3. Press the button "<<" or ">>" on the remote

Result: Now an empty white box is displayed on top of the video where the "play/pause" button was.

Solution: Press the back button to remove this box.

Minor annoyance 2:

whole
1. Open a video from the list "next" on the right side of a video.
2. The video will load but the white highlight box will be around the whole lower part of the app.

Result: You can't press the okay button to start the video.

Solution:

1. Press down on the remote.
2. The highlight marker will now jump down to the 3. comment but then automatically shoot up to the first comment again.
3. Press up on the remote to highlight the video.

### PR DESCRIPTION
**Pull request by Alexander--**
#### What is it?
- [x] Bug fix (user facing)
- [ ] Feature (user facing)
- [ ] Code base improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Agreement
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

Fixes #3904

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/views/FocusOverlayView.java [hunk 1]
```diff
@@ -123,6 +105,10 @@ private void updateRect() {
         }
     }
 
+    private boolean isShown(final View view) {
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/views/FocusOverlayView.java:108]:
```suggestion
    private boolean isShown(@NonNull final View view) {
```
