### PR TITLE
Fixed a bug that caused the background player to stop working

### LINKED ISSUE #9131: Start playing in background after clicking background in playlists bug
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open any playlist 
2. Click on background header 
3. Long press on any video except first one(which is already playing) select 'start playing in background'

### Expected behavior

The selected video should be played in background.

### Actual behavior

The first element(video/shorts) continue to play in background and no change occurs. The player does not register the aforesaid user command.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

Color OS v6.0

### Affected device model

Oppo Realme 1 CPH1861

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jared234**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

The bug was caused by an incorrect comparison between the existing `PlaylistQueue` and the new `PlaylistQueue`. In the `handleIntent` method in the `Player` class, both are compared, and if they are considered equal, the existing `PlaylistQueue` remains unchanged (because why reinitialize the same queue?). However, the overridden equality check was incorrect, as it only checks if the streams are the same, without considering the `queueIndex`. By inserting this check, the bug is fixed and only if the queues are actually identical, the existing queue is not reinitialized anymore.
I also had to change a test that tests if the equality check disregards the index. However, IMO if you do that the "equal" check doesn't make sense, since these queues cannot be considered equal.
#### Fixes the following issue(s)

- Fixes #9131 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java [hunk 1]
```diff
@@ -527,6 +527,9 @@ public boolean equals(@Nullable final Object obj) {
         if (size() != other.size()) {
             return false;
         }
+        if (other.getIndex() != getIndex()) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java:530]: This method is also used in other places where checking for the index is not wanted, e.g. in `VideoDetailFragment`. I would completely remove the `equals()` and `hashCode()` methods and create two new methods: `equalStreams(PlayQueue)` and `equalStreamsAndIndex(PlayQueue)`. Then the two methods can be called when needed, providing an easier to read code, and also preventing casting from `Object`.

**Review by Stypox — CHANGES_REQUESTED** [review]

**Comment by Jared234** [comment]
The "SonarCloud Quality Gate" failed. However, the "bug" it found cannot occur. If you take a look at the `equalStreams` method, you can see that it checks if `other` is null. Therefore, the `getIndex()` method can only be called on `other` in the `equalStreamsAndIndex` method if it is not null.  
Is there any way to ignore these kinds of issues? Or should I implement an additional check?

**Review by Stypox — DISMISSED** [review]
LGTM, thank you!

**Review by Stypox — APPROVED** [review]
