### PR TITLE
Integer overflow fixes in downloader

### LINKED ISSUE #3296: ArrayIndexOutOfBoundsException while postprocessing download of 1080p60fps video
### Version

- 0.19.0 RC5

### Steps to reproduce the bug

1. Open https://www.youtube.com/watch?v=I5Zb4w03atU in NewPipe
2. Start a download with 1080p 60fps
3. Wait until download finished
4. Postprocessing fails at ~18%

For more info, see https://github.com/TeamNewPipe/NewPipe/issues/3266#issuecomment-605659721

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=I5Zb4w03atU [ {type=video format=MPEG-4 quality=1080p60 videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.19.0
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: src.length=7730 srcPos=-15217326 dst.length=8192 dstPos=0 length=8192
	at java.lang.System.arraycopy(System.java:527)
	at us.shandian.giga.io.CircularFileWriter$BufferedFile.write(CircularFileWriter.java:405)
	at us.shandian.giga.io.CircularFileWriter.write(CircularFileWriter.java:231)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.outWrite(Mp4FromDashWriter.java:502)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.build(Mp4FromDashWriter.java:363)
	at us.shandian.giga.postprocessing.Mp4FromDashMuxer.process(Mp4FromDashMuxer.java:22)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(Unknown Source:0)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>

### PR DESCRIPTION
**Pull request by kapodamy**
fix two integers overflow cases

#### What is it?
- [✔] Bug fix
- [✖] Feature

#### Fixes the following issue(s)
fixes #3296

#### Testing apk
_no needed_

#### Agreement
- [✔] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java [hunk 1]
```diff
@@ -317,7 +313,7 @@ private String boxName(int type) {
     private Box readBox() throws IOException {
         Box b = new Box();
         b.offset = stream.position();
-        b.size = stream.readInt();
+        b.size = stream.readUnsignedInt();
```
Comment (wb9688) [inline app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java:316]: Was it a bug that it had `readInt()` instead of `readUnsignedInt()` here? Or did you somehow accidentally change this? Other than this, this PR looks good, but I haven't tested it yet.

Comment (kapodamy) [reply app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java:316]: no, the fix is here https://github.com/TeamNewPipe/NewPipe/pull/3325/commits/62d934dd8e89cc751c90e0c6a9ec36ea606cfbee

Comment (wb9688) [reply app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java:316]: I understand that, but why did you change this line?

Comment (kapodamy) [reply app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java:316]: * in somewhere was an overflow (the file was to big), so i discarded every possible overflow. Also, in mp4 box sizes are unsigned values, but since in DASH streams, bigger boxes llike `mdat` never reachs 2GB
* yes, size cannot be negative
