### PR TITLE
Fix playback speed not being updated in PlayQueueAcitvity

### LINKED ISSUE #6419: Playback tempo isn't reflected in background play without scrubbing or pausing
### Checklist

- [x] I am using the latest version - 0.21.3
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any YouTube video. I specifically tested this with a few random videos from the trending page.
2. Play the video with only background audio.
3. While the video is playing, change the tempo in the playback speed controls option on the top right. 

### Actual behaviour

The new tempo is not reflected in the playback speed control display from the playback queue unless you scrub around the video's audio or pause.

### Expected behavior

The updated playback speed should be reflected immediately after changing the playback speed.

### Screenshots/Screen recordings

NewPipe Playback speed bug

In the screenshot, the video is playing at about 2x speed. However, the playback speed in the top right still says 0.61x.

### Device info

 - Android version/Custom ROM version: Android 11, specifically (RQ2A.210505.002)
 - Device model: Google Pixel 4

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Update playback speed when changing it in the PlayQueueAcitvity
#### Fixes the following issue(s)
Fixes #6419

#### APK testing 
On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java [hunk 1]
```diff
@@ -457,6 +457,10 @@ public void onPlaybackParameterChanged(final float playbackTempo, final float pl
         if (player != null) {
             player.setPlaybackParameters(playbackTempo, playbackPitch, playbackSkipSilence);
         }
+        if (menu != null) {
+            final MenuItem item = menu.findItem(R.id.action_playback_speed);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java:461]: Just call `onPlaybackParameterChanged()` instead

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java]: Done

**Review by Stypox — APPROVED** [review]
