### PR TITLE
Fixed resuming streams at the last playback position

### LINKED ISSUE #13139: [Regression] Resume playback from last position no longer working
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read and understood the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#ai-policy). The content of this bug report is not generated by AI.

### Affected version

0.28.2

### Steps to reproduce the bug

1. Find a stream that you've already watched but didn't finish (and it shows the red line under it showing how much you've watched); alternatively make one by playing something but not finished it
2. Close the player, then go to history and play the stream again

### Expected behavior

Stream plays from the last playback position as displayed by the red line under the thumbnail

### Actual behavior

It resumes from the beginning

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/dc9ed424-02d8-46db-86b6-095f36a0d68e

### Logs

_No response_

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy S8

### Additional information

Recording was provided by someone else

### PR DESCRIPTION
**Pull request by absurdlylongusername**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing) ⚠️ **Your PR must target the [`refactor`](https://github.com/TeamNewPipe/NewPipe/tree/refactor) branch**
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

Reason for the bug is that https://github.com/TeamNewPipe/NewPipe/commit/1d8ea0181fc6a447153b0f1ffe4f27006bd1109a adds a call to `useVideoAndSubtitles` in the `initPlayback` overrides in the UI classes. This causes the recovery position for the queue item to be overridden due to the following flow:

- `Player.handleIntent` is called
- The `if (intent.getBooleanExtra(RESUME_PLAYBACK, false)` branch is reached
- It gets the playback position of the current queue item from the database via `loadStreamState`
- `newQueue.setRecovery(newQueue.getIndex(), state.getProgressMillis());` sets the recovery position to the value from DB
- Then calls `initPlayback(newQueue, playWhenReady);`
- `initPlayback` then calls `UIs.call(PlayerUi::initPlayback);`, which in turn calls `initPlayback` on one of `BackgroundPlayerUi`, `PopupPlayerUi`, `MainPlayerUi`
- `initPlayback` override in these classes calls `Player.useVideoAndSubtitles`
- `useVideoAndSubtitles` does `setRecovery()`
- This `setRecovery()` however gets the recovery position from `simpleExoPlayer.getCurrentPosition()` (which is effectively zero since we just started to resume playback), and this overwrites the previous recovery position we just set `setRecovery` in `handleIntent`
- `onPlaybackSynchronize` gets called at some point and seeks to the recovery position (which we just set to 0)
- And thus, it seeks to 0 instead of seeking to the saved playback position

The if conditions I added are supposed to ensure `setRecovery` is only called when there is no pending recovery (it won't be overwriting a recovery position that's already been set), or when exoplayer is far along in it's setup so that there's stuff to play (timeline is not empty).

I considered doing a proper refactor of this, because I don't really think calling `useVideoAndSubtitles` from the UIs is the best way to achieve the goal of minimizing bandwidth when playing in the background as it breaks separation of concerns, but I decided it's not worth it and can be tackled in NewPlayer at a later date.

#### Before/After Screenshots/Screen Record

Maybe later

#### Fixes the following issue(s)

- Fixes #13139 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] The proposed changes follow the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md#ai-policy).
- [x] I tested the changes using an emulator or a physical device.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 1]
```diff
@@ -2234,6 +2241,10 @@ The current metadata may be null sometimes (for e.g. when using an unstable conn
             index of the video renderer or playQueueManagerReloadingNeeded returns true
             */
             setRecovery(); // making sure to save playback position before reloadPlayQueueManager()
+            if (hasTimeline || !hasPendingRecovery) {
+                // making sure to save playback position before reloadPlayQueueManager()
+                setRecovery();
+            }
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: Is this really needed here? `setRecovery()` is called anyway.

File: app/src/main/java/org/schabi/newpipe/player/Player.java [hunk 2]
```diff
@@ -2214,13 +2210,24 @@ public void useVideoAndSubtitles(final boolean videoAndSubtitlesEnabled) {
...
             // In case we don't know the source type, fall back to either video-with-audio, or
             // audio-only source type
             final SourceType sourceType = videoResolver.getStreamSourceType()
                     .orElse(SourceType.VIDEO_WITH_AUDIO_OR_AUDIO_ONLY);
 
             setRecovery(); // making sure to save playback position before reloadPlayQueueManager()
+            if (hasTimeline || !hasPendingRecovery) {
+                // making sure to save playback position before reloadPlayQueueManager()
+                setRecovery();
+            }
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/player/Player.java]: > The if conditions I added are supposed to ensure `setRecovery` is only called when there is no pending recovery (it won't be overwriting a recovery position that's already been set), or when exoplayer is far along in it's setup so that there's stuff to play (timeline is not empty).

Hm, `setRecovery() `is called anyway here, independently from whether a recovery position was already set or not.. Don't you need to remove the first call? This is at least what I understood from your detailed explanation.

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 1 above)
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/player/Player.java:2245]: See above.

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 2 above)
Comment (absurdlylongusername) [reply app/src/main/java/org/schabi/newpipe/player/Player.java]: Lmao my bad, this a git issue, seems the rebasing I did onto dev didn't actually end up as it showed in Android Studio. Above setRecovery is not supposed to be there x).

I've confirmed this doesn't actually work with the above setRecovery still in place. I've removed it now

File: app/src/main/java/org/schabi/newpipe/player/Player.java (hunk 1 above)
Comment (absurdlylongusername) [reply app/src/main/java/org/schabi/newpipe/player/Player.java:2245]: See answer to above
