### PR TITLE
Share improvements + fix crash when no default browser is set on some devices

### LINKED ISSUE #3925: Error while opening content in browser
### Version

0.19.6

### Steps to reproduce the bug

1. Go to 'info about video'
2. Press on 'open in browser'

### Expected behavior

Opening url in browser.

### Actual behaviour

UI crashes

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ ru
* __Service:__ none
* __Version:__ 0.19.6
* __OS:__ Linux Android 7.0 - 24

<details><summary><b>Crash log</b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.youtube.com/... pkg=com.huawei.android.internal.app }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1854)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
	at android.app.Activity.startActivityForResult(Activity.java:4391)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:4335)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:4697)
	at android.app.Activity.startActivity(Activity.java:4665)
	at org.schabi.newpipe.util.ShareUtils.openUrlInBrowser(ShareUtils.java:36)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onOptionsItemSelected(VideoDetailFragment.java:702)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2830)
	at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2717)
	at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:412)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:389)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:313)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1203)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3197)
	at android.widget.AbsListView$3.run(AbsListView.java:4140)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

```
</p></details>
<hr>

### PR DESCRIPTION
**Pull request by TiA4f8R**
#### What is it?
- [x] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### General description of the changes
This PR improves sharing content to other apps with the following changes:

- fix crash when no browser is set on some devices (NewPipe thinks that the system app chooser is a browser because its package ID isn't "android" due to some OEM's system customizations)
- try to use Android's system share sheet instead of OEM's share sheet (this last is used as a fallback if this first was removed) for:
  - share content in clipboard (playlists, videos, tracks, channels and bug reports)
  - open content in browser (playlists, videos, tracks, channels, report on GitHub in bug reports options and comments, install a player prompts) where there is no default app
  - open a video stream / an audio stream in a external player where there is no default app
- fix double toast `Copied to clipboard` shown when copying formatted report in crash report activity

#### Code changes
- catch ActivityNotFoundException when opening an URL or a file if it's a chooser
- add openFileInApp method in ShareUtils to be able to open streams in external app / downloads in default app or in the app chooser
- edit getDefaultAppPackageName method of ShareUtils to be able to return default app for opening downloads, streams, or URLs
- use ShareUtils.openFileInApp for downloads / playing streams in external player
- use ShareUtils.shareUrl for sharing crash report from ErrorActivity to other apps and for sharing a stream in the play queue
- use ShareUtils.openUrlInBrowser when tap "Install" button from install VLC and install Kore dialogs
- use an ACTION_CHOOSER intent and putting as an extra intent the ACTION_SEND intent to share downloads
- add a string open_with in English and French which is used for Android's system chooser title
- add / edit comments and change JavaDocs for remembering that "android" package isn't returned when no default app on some devices
- also indent checkstyle-suppressions.xml file

Here is the difference between the original code and my changes (my device is an Honor 9X, running EMUI 10):

| Before this PR | After this PR |
|----------------|---------------|
| Share panel before               | Share panel after              |
| Share panel before this PR               | Share panel after this PR              |
| Open in browser before               | Open in browser after              |
| Open in browser before this PR              | Open in browser after this PR              |
| Open a download before             | Open a download after              |
| Open a download when no default app set before this PR              | Open a download when no default app set after this PR              |

#### What I changed to do this
The trick to do this is to use an ACTION_CHOOSER intent and put the share intent (ACTION_SEND) or the view intent (ACTION_VIEW) as an extra intent.
Note also if Android's system chooser (in the intent ACTION_CHOOSER) has been directly modified by the OEM, this PR will not change it.

#### A few note about UX
With my changes, we can't choose which app to always open an intent but only choose for once (if there isn't a default app).

#### Fixes the following issue(s)
Fixes #3925

#### APK testing
[NewPipe share improvements debug apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5810811/NewPipe.share.improvements.debug.apk.zip) (based on 92a87a5ed2e259ab36eaa5d95703ecdca7f61c08)

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

**Important note: I am not an Android / Java developer** so please be indulgent with me.

### CODE REVIEW

**Comment by TiA4f8R** [comment]
@test2a Can you please test the above APK and let me know if the crash when opening content in browser if you didn't set a default browser is fixed for you and when you share a video or a playlist, all is working? Thank you in advance.

**Comment by test2a** [comment]
@TiA4f8R 
Screenshot_20201216-104135

the new share screen is not showing for me.






 i think the browser thing has been somehow fixed but the issue remains. if i set newpipe to "open links in the app" in settings, then that app is always triggered. i am forced to set to ask everytime and then the above screen shows.

**Comment by TiA4f8R** [comment]
@test2a This is intended, that's how Android works. Also, your chooser dialog is from Android system (I have it too on my old Asus Zenfone 4 Max running Android 8.1.0), so all is working when opening content in browser.

About the share screen, can you share a playlist and say me if all is working by posting a screenshot from it?

Moreover, with the informations you provided in #4140, it seems your device isn't running Android 10 and this share sheet is from Android 10. So it's normal.

**Comment by test2a** [comment]
@TiA4f8R yeah. i am on 8 i think. anyways, how to share a playlist?? i see no option in bookmarked playlists

**Comment by test2a** [comment]
@TiA4f8R okay. got it. this just works 
Screenshot_20201216-173829

**Comment by test2a** [comment]
Screenshot_20201216-173917

**Comment by TiA4f8R** [comment]
@test2a Thanks for testing! All should work.

**Comment by TiA4f8R** [comment]
@TobiGr @B0pol In Android Messages of Google, I can select a date from a SMS but the text selection is different and seems to be the text selection of Android because when I use Share command, it opens Android Share Sheet and not Huawei Share Sheet, contrary to NewPipe. Check the two screenshots below:



Android Messages date text selection



NewPipe text selection (that's also the case of other apps)

I disable Android system on user 0 and here's the crash I got from logcat by using share command in the first screenshot (renabled it after, don't worry):

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CHOOSER (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2113)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1739)
	at android.app.Activity.startActivityForResult(Activity.java:5363)
	at aodd.startActivityForResult(PG:5)
	at android.app.Activity.startActivityForResult(Activity.java:5304)
	at aodd.startActivityForResult(PG:2)
	at android.app.Activity.startActivity(Activity.java:5734)
	at aodd.startActivity(PG:5)
	at android.app.Activity.startActivity(Activity.java:5702)
	at aodd.startActivity(PG:2)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
	at bds.x(PG:12)
	at wm.n(PG:1)
	at wp.e(PG:2)
	at wm.r(PG:2)
	at wm.q(PG:1)
	at wm.performIdentifierAction(PG:1)
	at bdw.onMenuItemClick(PG:1)
	at bdd.onClick(PG:3)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

So did you know if we can do something for text selection in NewPipe to get the same result?

**Comment by TiA4f8R** [comment]
To do (if possible):

- [ ] Use ShareUtils.openUrlInBrowser for links in description of videos and tracks
- [ ] Use ShareUtils.openUrlInBrowser for links in search results (COVID-19, ...)

Also a few note about UX: with my changes, we can't choose which app to always open an intent but only choose for once (if there isn't a default app).

**Comment by TiA4f8R** [comment]
Can someone help me for the things above?

**Comment by TiA4f8R** [comment]
@MathJoDE Does the APK in description is working for sharing a video/playlist, opening a video/playlist in a browser, opening a NewPipe download, and a link in comment of a video? Thanks for testing in advance.

**Comment by MathJoDE** [comment]
@TiA4f8R Seems to work great!

I tested successful:
* share a video/playlist/channel
* open a video/playlist/channel in a browser
* open a NewPipe download
* open a link in comment of a video
* (fixing #5308) on error page: buttons to 
  * read privacy policy
  * accept privacy policy to report on Github

**Comment by TiA4f8R** [comment]
@MathJoDE Like on my device (Honor 9X, EMUI 10), is Android's system chooser showing on your device instead of Huawei chooser / Huawei Share?
Also when you open a download, does the download open in a video / audio player or did you have a chooser (I want to know if you have or not a default app to open your download to be sure if all my code is working even if I tested on my device)? It will be great if you can post screenshots of all cases if possible.
Thanks for testing!

**Comment by MathJoDE** [comment]
> @MathJoDE Like on my device (Honor 9X, EMUI 10), is Android's system chooser showing on your device instead of Huawei chooser / Huawei Share?

Yes, for all test cases I mentioned in my post above, now the Android system chooser pops up. (In contrast to current stable version 0.20.8, where the Huawei chooser pops up.) It's exemplary shown in the left screenshot below.

> Also when you open a download, does the download open in a video / audio player or did you have a chooser (I want to know if you have or not a default app to open your download to be sure if all my code is working even if I tested on my device)? It will be great if you can post screenshots of all cases if possible.

Also for opening a Download the Android system chooser shows up (right screenshot)

Screenshots:
| opening a link in a comment | opening a download |
|-----------------------------------|--------------------------|
| <details> <summary>show screenshot</summary> link-in-comment </details> | <details> <summary>show screenshot</summary> downloaded-video </details> |

----

For links in video descriptions and also for links in these legal notices by youtube (that something belongs to a public broadcast service, or the COVID notices) below videos, still the Huawei Chooser pops up. (left screenshot below). Also at a channel's rss feed, still the Huawei Chooser is used (right screenshot).

| opening link in video description/legal notice | opening a channel's rss feed |
| ----------------------------------------------- | ------------------------------------- |
| <details> <summary>show screenshot</summary> link-in-vid-description-and-legal-hint </details> | <details> <summary>show screenshot</summary> channels-rss-feed </details> |

I assume that's what the ToDos in the PRs opening comment are addressing, in which the RSS feed point seems to miss.

---

I'm not really experienced with Java, and even less with Android developing, but based on the diff of your changes in this PR I fiddled a bit around[1]. So the following is absolutely untested and just guessed. Maybe it can help, if not, just ignore it ^^

I suppose [here](https://github.com/TiA4f8R/NewPipe/blob/877bd84bff1ba7d8dbe9477c0a92515ab01e8c7e/app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java#L209) the `ShareUtils.openUrlInBrowser` should be used for also opening the rss feed link with android's default chooser.

[1] using `git grep -B 10 -A 2 "startActivity("`

**Comment by TiA4f8R** [comment]
@MathJoDE Thanks for your searches and your response! I will do in a future commit the trick for RSS feed.
For links in video description and meta info, I don't know how to do this (it seems that links are generated with an Android library). I need help from a member of NewPipe's team to change the behavior beacuse I am not a developer.

**Comment by B0pol** [comment]
I disagree with last change. We don't want to open RSS feed in browser, but in default app configured to handle RSS or other feeds. It's fine to open RSS feed in your RSS app. On top of that, most popular browsers don't support RSS feeds anymore.

The "**why**" I introduced this change initially — open in browser instead of open in default app — was because YouTube, PeerTube or other services links would loop in NewPipe if NewPipe is set as default for these links.

**Comment by TiA4f8R** [comment]
@B0pol Ok, I will revert it.

**Comment by TiA4f8R** [comment]
@B0pol I understand what you mean, but I changed getDefaultAppPackageName to return the default app for an intent passed as an argument and not only for http links. The openUrlInBrowser method just create an intent like as previous for RSS feeds. I just tried with two RSS apps and if I set it to always open the links that they can open it opens the RSS app; if I don't set it, it will open a chooser. This behavior is the same in the original app and my modifications.

(I will upload screencasts later.)

**Comment by TiA4f8R** [comment]
@B0pol I did some changes related to what you said in your last comment. Can you please let me know if those are good or not? Thanks in advance.

**Comment by TiA4f8R** [comment]
Hi, can someone help me to create methods to set a custom action when clicking on links in content description from a plain text like on SoundCloud and for a description from a Mardown text? Thank you in advance.

**Comment by TiA4f8R** [comment]
While debugging my changes in Chrome Developer Tools and opening a YouTube video, this crash happens. How to fix it?

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.IllegalStateException
	at com.facebook.stetho.common.Util.throwIfNot(Util.java:56)
	at com.facebook.stetho.common.android.HandlerUtil.verifyThreadAccess(HandlerUtil.java:38)
	at com.facebook.stetho.inspector.elements.android.AndroidDocumentProviderFactory.verifyThreadAccess(AndroidDocumentProviderFactory.java:53)
	at com.facebook.stetho.inspector.helper.ThreadBoundProxy.verifyThreadAccess(ThreadBoundProxy.java:36)
	at com.facebook.stetho.inspector.elements.Document$ProviderListener.onAttributeModified(Document.java:725)
	at com.facebook.stetho.inspector.elements.android.AndroidDocumentProvider.onAttributeModified(AndroidDocumentProvider.java:211)
	at com.facebook.stetho.inspector.elements.android.TextViewDescriptor$ElementContext.afterTextChanged(TextViewDescriptor.java:78)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:10634)
	at android.widget.TextView.setText(TextView.java:6335)
	at android.widget.TextView.setText(TextView.java:6154)
	at android.widget.TextView.setText(TextView.java:6106)
	at org.schabi.newpipe.util.LinkHelper.createLinksFromHtmlBlock(LinkHelper.java:40)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$prepareDescription$11$VideoDetailFragment(VideoDetailFragment.java:1233)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$nQlGpf89J6dlFXrUIggLADRLDEI.apply(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
	at io.reactivex.rxjava3.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:41)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

**Comment by TobiGr** [comment]
There is no `onError()` method implemented in the subscripe method:
https://github.com/TeamNewPipe/NewPipe/blob/395f6f6e4ede09d19860b82032ea98b54e6664a0/app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java#L1231-L1241

**Comment by TiA4f8R** [comment]
@TobiGr Thanks for your response. So, what I should do?

**Comment by TiA4f8R** [comment]
@TobiGr I removed the use of disposables when preparing HTML descriptions in prepareDescription method of the VideoDetail fragment. I tried to open a YouTube video when debugging the app in Chrome Developer Tools and it opens fine with the description which is successfully shown. Is it ok to remove this use ?

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java [hunk 1]
```diff
@@ -21,22 +22,80 @@ private ShareUtils() {
...
+     * {@link ShareUtils#openInDefaultApp(Context, Intent)}
+     *
+     * @param context                the context to use
+     * @param url                    the url to browse
+     * @param httpDefaultBrowserTest the boolean to set if the
+     *                               test for the default browser will be for HTTP protocol
+     *                               or for the created intent
+     */
+    public static void openUrlInBrowser(final Context context, final String url,
+                                        final Boolean httpDefaultBrowserTest) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:34]: Why `Boolean` and not `boolean`?

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java [hunk 2]
```diff
@@ -21,22 +22,80 @@ private ShareUtils() {
...
      * @param url     the url to browse
-     */
+     **/
     public static void openUrlInBrowser(final Context context, final String url) {
-        final String defaultBrowserPackageName = getDefaultBrowserPackageName(context);
+        openUrlInBrowser(context, url, true);
+    }
+
+    /**
+     * Open a content with the system default browser.
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:76]: Copy-paste leftover

File: app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java [hunk 3]
```diff
@@ -569,27 +567,14 @@ public static Intent getIntentByLink(final Context context,
...
         try {
             // Try market:// scheme
-            context.startActivity(new Intent(Intent.ACTION_VIEW, openMarketUrl(packageName)));
+            ShareUtils.openUrlInBrowser(context, "market://details?id=" + packageName, false);
         } catch (final ActivityNotFoundException e) {
             // Fall back to google play URL (don't worry F-Droid can handle it :)
-            context.startActivity(new Intent(Intent.ACTION_VIEW, getGooglePlayUrl(packageName)));
+            ShareUtils.openUrlInBrowser(context,
+                    "https://play.google.com/store/apps/details?id=" + packageName, false);
         }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java:578]: This can probably also be moved to `ShareUtils`

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java [hunk 4]
```diff
@@ -21,22 +22,80 @@ private ShareUtils() {
...
+     * <p>
+     * If no app is set as default, fallbacks to
+     * {@link ShareUtils#openInDefaultApp(Context, Intent)}
+     *
+     * @param context the context to use
+     * @param intent  the intent of the file to open
+     */
+    public static void openContentInApp(final Context context, final Intent intent) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:84]: Could you give a better name to this? For me the difference between `openContentInApp` and `openInDefaultApp` isn't clear

File: app/src/main/java/org/schabi/newpipe/about/AboutActivity.java [hunk 5]
```diff
@@ -146,16 +146,20 @@ public View onCreateView(@NonNull final LayoutInflater inflater, final ViewGroup
...
 
             aboutBinding.donationLink.setOnClickListener(v ->
-                    openUrlInBrowser(context, context.getString(R.string.donation_url)));
+                    openUrlInBrowser(context, context.getString(R.string.donation_url),
+                            false));
 
             aboutBinding.websiteLink.setOnClickListener(nv ->
-                    openUrlInBrowser(context, context.getString(R.string.website_url)));
+                    openUrlInBrowser(context, context.getString(R.string.website_url),
+                            false));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/about/AboutActivity.java:158]: Could you move the `false`s that would fit into the 100 character limit inline? Also above

File: app/src/main/java/org/schabi/newpipe/util/LinkHelper.java [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+import android.text.util.Linkify;
+import android.view.View;
+import android.widget.TextView;
+
+import androidx.core.text.HtmlCompat;
+
+import io.noties.markwon.Markwon;
+import io.noties.markwon.linkify.LinkifyPlugin;
+
+public final class LinkHelper {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/LinkHelper.java:17]: `LinkHelper` doesn't feel like the right name to me, though I don't have a better suggestion

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java [hunk 7]
```diff
@@ -79,13 +156,15 @@ private static String getDefaultBrowserPackageName(final Context context) {
      * @param url     the url to share
      */
     public static void shareUrl(final Context context, final String subject, final String url) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:158]: Shouldn't this be called `shareText`, since it is now used to also share `json`?

**Review by Stypox — CHANGES_REQUESTED** [review]
The `LinkHelper` is a good idea. Thank you!

File: app/src/main/java/org/schabi/newpipe/util/LinkHelper.java (hunk 6 above)
Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/LinkHelper.java:17]: What do you think of something like LinkCreator or LinkTransformer?

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java (hunk 7 above)
Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:158]: Yes, I will change method name (a lot files will be changed).

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java (hunk 1 above)
Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:34]: Oh, I didn't know this (I am not a developer). I will change it.

File: app/src/main/java/org/schabi/newpipe/util/LinkHelper.java (hunk 6 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/LinkHelper.java:17]: `TextLinkifier`, maybe?

File: app/src/main/java/org/schabi/newpipe/util/ShareUtils.java (hunk 4 above)
Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:84]: I was thinking first of openFileInApp but I also use this method to play content in an external app.

Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/ShareUtils.java:84]: Method name changed to openIntentInApp

**Comment by TiA4f8R** [comment]
@Stypox Changes requested applied. Please don't merge this now, I want to implement #3253 in this PR.

**Comment by Stypox** [comment]
@TiA4f8R The changes you pushed are looking good, thanks ;-)

> Change text selection "Share" action to use ShareUtils.shareUrl

Since all other apps don't do this, I wouldn't do it here either. Or at least not in this PR, but in a future one.

> For links in video description and meta info, I don't know how to do this (it seems that links are generated with an Android library). I need help from a member of NewPipe's team to change the behavior beacuse I am not a developer.

Take a look here, and in particular the last few lines:
https://github.com/TeamNewPipe/NewPipe/blob/9ee7740fccbb186b7180c7084c5cbc10368e9f9f/app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java#L321-L374

> Is it ok to remove this use ?

For big HTMLs it can take a while to build the `Spannable`s, so doing that on the main thread is a bad idea.

> I want to implement #3253 in this PR after I know how to handle a long click on description and comment links (can someone help me for that?).

I don't know how this could be achieved, but maybe you can loop through all `Spannable`s and set a long click listener?

**Comment by TiA4f8R** [comment]
> > For links in video description and meta info, I don't know how to do this (it seems that links are generated with an Android library). I need help from a member of NewPipe's team to change the behavior beacuse I am not a developer.
> 
> Take a look here, and in particular the last few lines:
> https://github.com/TeamNewPipe/NewPipe/blob/9ee7740fccbb186b7180c7084c5cbc10368e9f9f/app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java#L321-L374

I already do this in my first commit :)

**Comment by TiA4f8R** [comment]
@Stypox Unformatly, I haven't a big amount of time for the moment and programming knowledges to do something on #3253. So I will not do anything on it :(.

**Comment by Stypox** [comment]
> I already do this in my first commit :)

Oh, yeah, sorry ;-)

> So I will not do anything on it

That's ok, don't worry, this PR solves many issues just by itself and a new one can still be opened by you or someone else in the future :-)

---

Could you bring back the use of reactivex disposables, so that the `Spannable`s building process is not done on the main thread? If you need any help feel free to ask, and if you have no time I can do that myself. Thank you :-D

**Comment by TiA4f8R** [comment]
@Stypox Can you do it please (note that it was only for HTML descriptions, may be it should be extended to other description types?) and also fix if you can https://github.com/TeamNewPipe/NewPipe/pull/5187#issuecomment-758188468? This crash is so annoying... Thank you in advance!

(And also thanks for your review :) )

**Comment by Stypox** [comment]
@TiA4f8R done, what do you think about my changes?

**Comment by TiA4f8R** [comment]
@Stypox Looks good (I am not developer and I don't really know Java so you should ask to a real developer :)). Did you test your changes by trying to open a video / a track while debugging the app with Steho on your computer and see if description is showing successfully or if there is a crash?

**Comment by Stypox** [comment]
> I am not developer and I don't really know Java

Let me tell you that you did a very good job given that you don't know Java ;-)

> debugging the app with Steho

Why should I do that? I have never debugged anything in Stetho, though I have tested that the app works. Anyway, debugging instead of executing normally shouldn't change anything.

**Comment by TiA4f8R** [comment]
@Stypox Oh sorry, I talk about Chrome Developer Tools (`chrome://inspect#devices`) when selecting NewPipe, to inspect network traffic (it's written `Powered by Steho` after the app name).

**Comment by TiA4f8R** [comment]
@Stypox I just tested while debugging in Chrome Developer Tools and it works, no crash and descriptions are showing! Thanks for your commit!

I have a question about the new app version update notification: currently, NewPipe uses an ACTION_VIEW intent in the notification which launches the Huawei Chooser on EMUI devices if there isn't a default browser. If I use an ACTION_CHOOSER intent and put the ACTION_VIEW intent as an extra intent and if there is a default browser, does the system will open the Android system chooser or it will open the default browser? Thanks in advance for your response.

**Comment by Stypox** [comment]
Thank you for testing. From what I understand from [here](https://stackoverflow.com/questions/7614652/intent-resolution-and-difference-between-action-chooser-and-action-pick-activity) and [here](https://developer.android.com/training/basics/intents/sending#java), it should open the Android system chooser.

**Review by Stypox — APPROVED** [review]
I rebased and tested more, both on Android 4.4, Android 10 and Android 11. Everything works as expected. Thank you!

**Comment by TobiGr** [comment]
I get this on Android TV API 27:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ActivityInfo android.content.pm.ResolveInfo.activityInfo' on a null object reference
	at org.schabi.newpipe.util.ShareUtils.getDefaultBrowserPackageName(ShareUtils.java:168)
	at org.schabi.newpipe.util.ShareUtils.openUrlInBrowser(ShareUtils.java:58)
	at org.schabi.newpipe.util.ShareUtils.openUrlInBrowser(ShareUtils.java:91)
	at org.schabi.newpipe.player.Player.onOpenInBrowserClicked(Player.java:3575)
	at org.schabi.newpipe.player.Player.onClick(Player.java:3430)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</details>
<hr>
