### PR TITLE
Fix duplicate items in queue causing endless buffering

### LINKED ISSUE #4940: Endless buffering on duplicate videos in queue
### Checklist
- [x] I am using the latest version - 0.21.1 (But this bug happens at least since the v0.20.4)
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Play a video in background that is duplicated in a playlist (the duplicate has to come right after the video) and the bug will occur when the duplicate plays.

### Actual behaviour
The video basically gets on an endless buffering and never starts playing or moves on to the next playlist video (unless you do it manually).

### Expected behavior
The video, whether duplicate or not should play normally.

### Device info

 - Android version/Custom ROM version: MIUI 11 (Android 7.0)
 - Device model: Redmi Note 4

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
This is a simple bugfix that allows having play queues with duplicate items. For some reason an `equals()` method was implemented in `PlayQueueItem` that only compared the url, and since duplicate items have the same url they were considered the exact same `PlayQueueItem`s. Using Java's default `equals()` method, that just checks if two objects are the same with `==`, solves the issue, since duplicate items were anyway created one by one and thus are never identical. Removing `equals()` should be completely fine since `PlayQueueItem`s are never `clone()`d, and therefore we never end up with two objects that should be considered the same but down in memory aren't because they were cloned.

#### Fixes the following issue(s)
- Fixes #4940

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.
I am not completely sure that this doesn't introduce regressions, so it needs some testing. @ekiniko12 @RickyM7 @sqtvrnqliq could you check if the endless buffering on duplicate videos in queue is solved?

#### Due diligence
- [ ] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by RickyM7** [comment]
I just tested it and the bug was fixed, thank you very much!

- Device: Redmi Note 4 (ArrowOS v11 - Android 11)

File: app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java [hunk 1]
```diff
@@ -64,20 +64,6 @@ private PlayQueueItem(@Nullable final String name, @Nullable final String url,
         this.recoveryPosition = RECOVERY_UNSET;
     }
 
-    @Override
-    public boolean equals(final Object o) {
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java:68]: Oh my! what a bug xD
Did you check the usages of the method? Maybe someone implemented this on purpose.

**Comment by ekiniko12** [comment]
It's finally working, thank you!

**Comment by PinkFriday** [comment]
Hey, I'm sqtvrnqliq, I was locked out of my other account so I'm now on this one! Is there any other way for me to download the debug apk because my phone isn't letting me download it when I go to artifacts :(

File: app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java (hunk 1 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java:68]: Android Studio's "Show usages" yields all of the usages of the `equals()` method on any object of any class, so that's not much useful. I tried to manually look for usages by checking out the methods in `PlayQueue` and in `Player` that use `PlayQueueItem` comparison and could not find any issue.
The only downside I can think of is that if the same video is queued multiple times in a row, the loading strategy may start to load the current and the next stream contemporarily, but since those streams point to the same url but do not compare equal, they will be loaded twice. But this only happens if two play queue items with the same url start loading contemporarily, because otherwise the caching method prevents reloading something that already was loaded. I don't think this is really a downside.

**Comment by Redirion** [comment]
"for some reason" :D you have added this yourself Stypox:
https://github.com/TeamNewPipe/NewPipe/commit/2a2c82e73bb2380c07ab848b185952ab183a5502#diff-6dcb0e241835a3f32ba00835e94c64b48b6faf84c0252769617507c1c2fd8371

**Comment by Stypox** [comment]
@Redirion 🙈🙈
I don't remember what the rationale for adding those methods was

**Comment by Stypox** [comment]
@Redirion take a look at the last 2 commits, and thank you for taking a look ;-)
I also added some tests

**Review by Redirion — APPROVED** [review]
lgtm!

**Comment by RickyM7** [comment]
@Stypox Was this included in the last update (v0.21.8)? I just tested this version but the bug still exists.

**Comment by Stypox** [comment]
@RickyM7 no, 0.21.8 was a hotfix, just read the changelog

**Comment by RickyM7** [comment]
> no, 0.21.8 was a hotfix, just read the changelog

Got it, thank you!

**Comment by randacco** [comment]
Many thanks for this so needed fix!
