### PR TITLE
check if the JSON MimeType is supported

### LINKED ISSUE #9169: Import subscription no prompt for storage permission bug
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Export subscription into a file by clicking export to>file under subscription tab
2. Clear data 
3. Try to import the subscription by clicking import from>exported file 
4. The file picker won't even let you pick the exported file

### Expected behavior

The app should import subscription

### Actual behavior

Won't even let me pick file

The issue only arises because new pipe doesn't ask for storage access permission when trying to import subscription by clicking on import from> previous export under subscription tab.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

### Additional information

Note: I figured out the reason why it's because new pipe doesn't ask for permission for storage at startup so when the import is clicked it launches android file picker but if you go to settings and try to set download location it asks for permission or just manually enable storage access in settings or app info depending upon your OS and ROM then when you try to import subscription it uses newpipe's native file picker which works fine entirely.

### PR DESCRIPTION
**Pull request by dev-victoria**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

If no JSON MIME type is available on the android(old version), use "application/octet-stream" instead, which targets json files one puts on the old device.

Another solution could be to check for `Build.VERSION.SDK_INT < Build.VERSION_CODES.Q` instead of using the webkit MimeTypes

Since a file of type application/json can still be created locally(by exporting as such), the mime type for the file picker might need to be \*/\* to support both locally exported(as "application/json") and otherwise transferred .json files("application/octet-stream").

#### Before/After Screenshots/Screen Record

<table>
  <tr>
    <th>Before</th>
    <th>API28</th>
    <th>API29</th>
  </tr>
  <tr>
    <td>Before</td>
    <td>API28</td>
    <td>API29</td>
  </tr>
</table>

#### Fixes the following issue(s)

- Fixes #9169

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt [hunk 1]
```diff
@@ -460,6 +461,14 @@ class SubscriptionFragment : BaseStateFragment<SubscriptionState>() {
...
-        const val JSON_MIME_TYPE = "application/json"
+        val JSON_MIME_TYPE = getMimeType()
+
+        private fun getMimeType(): String {
+            val mimeTypeJson = MimeTypeMap.getSingleton().getMimeTypeFromExtension("json")
+            return if (mimeTypeJson.isNullOrBlank())
+                "application/octet-stream"
+            else
+                mimeTypeJson
+        }
```
Comment (Isira-Seneviratne) [inline app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt]:
```suggestion
        val JSON_MIME_TYPE = MimeTypeMap.getSingleton().getMimeTypeFromExtension("json") ?: "application/octet-stream"
```

Comment (dev-victoria) [reply app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt]: Did it in two lines to hit the style checker.

**Review by Isira-Seneviratne — APPROVED** [review]
Looks good to me.
