### PR TITLE
Load enough initial items (into BaseListFragment and descendants)

### LINKED ISSUE #1974: Infinite loading in lists when streams aren't filling the screen
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.

Hello.

I am now getting tired of using the **List** view. I wanted to go back to **Grid** view for my tablet as it feels better. 
Whenever I search for something (e.g. *Music*), the first few videos load. Scrolling down won't work as its got 'one page' or screen you could say, of videos. Stuck there and cannot load more, I'm missing one video to have the whole page/screen filled with videos. Just need another one after that to be able to scroll down and load more if that's how it works. Using **SM-T813**. **LineageOS 15.1** latest.
Tested on my phone. There are no problems there.

**Reproduce:**
× Own a tablet.
× Use the Grid view.
× Search for anything. I searched for *Music*.
× Try to load more than 'one page'.

Works? Not for me!

### LINKED ISSUE #3368: Instead of crashing, or showing an error, can Newpipe just... not scroll?
### Version

- 0.21.9 (earlier 0.19.1)

### Steps to reproduce the bug

1. Search something.
2. Turn off internet.
3. Scroll down the list.

### Expected behavior
Since Newpipe can't load new items in the list without internet, it should just not scroll after the last already loaded one. You could mention the network error and show the retry button in the space _below_ the last list item.

### Actual behaviour
Screen clears and shows Network Error with a Retry button.

In rare cases like I just got, crash. UI error. It seems to involve the AndroidX RecyclerView.

Interestingly, with this error page, tapping back takes you to the home screen, but you can open Newpipe from its launcher and use it without any error. If you tap back from there, though, you're taken to the error page again. It's in the backstack or something.

If you turn internet back on and then open Newpipe, it removes the error page from the backstack.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en_IN
* __Service:__ none
* __Version:__ 0.19.1
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{7611833 position=20 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)} androidx.recyclerview.widget.RecyclerView{42907f0 VFED.V... ......ID 0,0-1080,1728 #7f090150 app:id/items_list}, adapter:org.schabi.newpipe.info_list.InfoListAdapter@983b169, layout:androidx.recyclerview.widget.LinearLayoutManager@d56b7ee, context:org.schabi.newpipe.MainActivity@88466a3
	at androidx.recyclerview.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:915)
	at androidx.recyclerview.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
	at androidx.recyclerview.widget.RecyclerView.addAnimatingView(RecyclerView.java:1431)
	at androidx.recyclerview.widget.RecyclerView.animateDisappearance(RecyclerView.java:4161)
	at androidx.recyclerview.widget.RecyclerView$4.processDisappeared(RecyclerView.java:612)
	at androidx.recyclerview.widget.ViewInfoStore.process(ViewInfoStore.java:240)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3994)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</p></details>
<hr>

### LINKED ISSUE #4475: Crash in lists (ViewHolder views not attached)
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Set up peertube.debian.social as the peertube instance
2. Open Trending/Local/whatever
3. Attempt to scroll beyond the last element

### Actual behaviour

Crash (see below).

### Expected behavior

I’d expect more video thumbnails to appear.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.0
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6680)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

### Device info

 - Device model: Mi Box S

### PR DESCRIPTION
**Pull request by litetex**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
* Supersedes #7638
* Fixes #1974 by loading enough initial data until the RecyclerView is scrollable or no more data/items can be loaded - improved behavior from PR #7638
* Fixes #3368 and fixes #4475 by not reusing the footer (and supplying the header dynamically)

#### Before/After Screenshots/Screen Record
- Before: See #1974
- After: 

https://user-images.githubusercontent.com/40789489/149629153-5baabecc-a24f-43d0-af16-105414fda8eb.mp4

#### Fixes the following issue(s)
- Fixes #1974
- Fixes #3368 
- Fixes #4475 

#### APK testing 
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

Tips for testing:
* The changes can be at best tested with a tablet and Grid-mode enabled

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by litetex** [comment]
Tested it again and run into #3368 more often than expected. I think #3368 (and maybe #4475) should be fixed before merging this.

**Comment by litetex** [comment]
So after extensive testing, finding out about unexpected behaviors and so on, I decided to use the original idea/behavior from #7638 and improved it, because loading via handleResults/loadMoreItems-callback causes the RecyclerView apparently to not be immediately updated in the UI when the data is set - which causes one load of data to much.

**Comment by opusforlife2** [comment]
Your commit message links to this PR instead of 7638.

File: app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java [hunk 1]
```diff
@@ -129,12 +134,12 @@ public void addInfoItemList(@Nullable final List<? extends InfoItem> data) {
         if (DEBUG) {
             Log.d(TAG, "addInfoItemList() after > offsetStart = " + offsetStart + ", "
                     + "infoItemList.size() = " + infoItemList.size() + ", "
-                    + "header = " + header + ", footer = " + footer + ", "
+                    + "header = " + hasHeader() + ", "
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:137]:
```suggestion
                    + "hasHeader = " + hasHeader() + ", "
```

File: app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java [hunk 2]
```diff
@@ -330,34 +306,28 @@ public void onBindViewHolder(@NonNull final RecyclerView.ViewHolder holder, int
...
+        if (payloads.isEmpty() || !(holder instanceof InfoItemHolder)) {
             onBindViewHolder(holder, position);
+            return;
+        }
+
+        for (final Object payload : payloads) {
+            if (payload instanceof StreamStateEntity || payload instanceof Boolean) {
+                ((InfoItemHolder) holder).updateState(
+                        infoItemList.get(hasHeader() ? position - 1 : position), recordManager);
+            }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:330]: What does this do? Why is `updateState` called multiple times if the payloads are more than one? What are payloads anyway and why are they unused?

**Review by Stypox — CHANGES_REQUESTED** [review]
Looks good, thank you for this much needed fix. :-)
I still haven't tested

File: app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java (hunk 2 above)
Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:330]: You might want to ask @nv95 because he implemented the original version of it:
https://github.com/TeamNewPipe/NewPipe/commit/93f25181596792ed35287cd12fff55d97aa6ffe0#diff-d075c1aaf95acf093a7feaa093198bfbc9c4d5b479e2b57effdaf7a9e74448d9R316

I just niceified the code a bit 😄 

I'm not sure if it is ever used in the first place because I can't find a method calling it (maybe some internal calls?).


If I have time I will try to figure out what the snippet does.

File: app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java (hunk 1 above)
Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java]: 2x Done

File: app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java (hunk 2 above)
Comment (nv95) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:328]: Usually payloads is just list of one item (or empty), but docs says:
> payloads – A non-null list of merged payloads. Can be empty list if requires full update.


And `updateState` called with differed parameters

Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:328]: @nv95 
Thank you for the quick response.

But what does the ``payload instanceof StreamStateEntity || payload instanceof Boolean``-line do/or is for?
Why not always call ``updateState`` on the holder regardless of the payload?

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:328]: According to the documentation of `onBindViewHolder(VH, int, List<Object>)`:
```java
The payloads parameter is a merge list from {@link #notifyItemChanged(int, Object)} or
{@link #notifyItemRangeChanged(int, int, Object)}.  If the payloads list is not empty,
the ViewHolder is currently bound to old data and Adapter may run an efficient partial
update using the payload info.  If the payload is empty,  Adapter must run a full bind.
Adapter should not assume that the payload passed in notify methods will be received by
onBindViewHolder().  For example when the view is not attached to the screen, the
payload in notifyItemChange() will be simply dropped.
```

So the payloads must come from one (or both) of `notifyItemChanged(int, Object)` and `notifyItemRangeChanged(int, int, Object)`. We only use `notifyItemRangeChanged` [in `FeedFragment`](https://github.com/TeamNewPipe/NewPipe/blob/402990dd9d4b58fef26bbe9aa5a6f9c587011342/app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt#L555) and a payload is actually being passed: `StreamItem.UPDATE_RELATIVE_TIME`, of type `int` and value `1`. So it would not pass the check `payload instanceof StreamStateEntity || payload instanceof Boolean` (and as expected when resuming the feed fragment the durations are not reloaded, to test this just mark an item as watched and pause&resume the app).

Another note: according to the documentation above, "If the payload is empty,  Adapter must run a full bind.", but this is not being done in our code.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:328]: > I think this is done:

Oh right, sorry ;-)

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java:328]: I think you can remove [that function](https://github.com/TeamNewPipe/NewPipe/blob/cb78433a26989691f4b7b1d30aa25f0c469e8bfb/app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java#L314-L331) completely, and let the base function always do the full update.

The payload `StreamItem.UPDATE_RELATIVE_TIME` is [actually being received](https://github.com/TeamNewPipe/NewPipe/blob/d5199eac3e9e6cf8331adbbe9b742b9b1d178f7e/app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt#L53-L63), but it would never be received by the method I told you to remove since [`FeedFragment` uses `GroupieAdapter`](https://github.com/TeamNewPipe/NewPipe/blob/402990dd9d4b58fef26bbe9aa5a6f9c587011342/app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt#L148-L151) and not `InfoListAdapter`.

Comment (litetex) [reply app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java]: Done 😄

**Review by Stypox — CHANGES_REQUESTED** [review]
Code looks good, thank you!

I tested on my phone (FP3 API 29) and everything went well. I then tested on an emulated tablet API 31 and found a small issue:

- ~create a tablet emulator with a big enough screen (e.g. Pixel C in Android Studio)~
- ~start & rotate the device to portrait (with auto rotate on, so that it actually rotates)~
- ~open Souncloud's "New and hot": the trending video list will be shown with items in the "large/long" variant~
- ~rotate the device to landscape: now the items will be shown in the "mini" variant, so they use up less space and the loading footer appears. But nothing ever starts loading and there is no way to start loading even if rotating back to portrait.~

Ignore all of the above, the issue is simpler: just open a trending or channel fragment and rotate the device. The list will stop loading new items and there is no way to trigger items loading, even when scrolling down to the bottom or even when rotating back to the original rotation.
With the search fragment it's even worse: the loading indicator doesn't even show up after rotating, even though the search results aren't finished.
The comments fragment seems to work correctly though even after rotation.

Other than this I couldn't find other issues.

**Review by Stypox — APPROVED** [review]
Can confirm it's fixed. Ready in my opinion! :-D

I found other two small issues that are **not caused by this PR and should not be fixed here**:
- when scrolling down fast and there are more items, sometimes the view suddenly stops scrolling right above the loading footer, instead of scrolling down to the bottom of the footer. Items start loading anyway, but since the scroll stopped before the loading indicator could become visible, to the user it may seem like there are no more items.
- when pressing Android's square button (to view recent apps) and rotating the device at the same time, and then going back to the app, the (search) fragment starts reloading the list from the beginning. No such problem happens when the app just `resume`s from recents (e.g. because its state was saved to disk after a RAM shortage).

**Comment by TobiGr** [comment]
> I found other two small issues that are not caused by this PR and should not be fixed here:

@Stypox Can you check whether there are open issues for this already and open new ones if necessary?

**Comment by Stypox** [comment]
@TobiGr done: #7908 #7909
