### PR TITLE
Issue #2254

### LINKED ISSUE #2254: Do not show "History" in context menu if "History & Cache" disabled in "Settings"
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

pic.1

pic.2

### PR DESCRIPTION
**Pull request by karkaminski**
Fixes #2254

Removed dot-menu where it is no longer needed and implemented disabling History button according to settings
[debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4061629/debug.zip)

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/MainActivity.java [hunk 1]
```diff
@@ -551,8 +561,6 @@ public boolean onCreateOptionsMenu(Menu menu) {
         if (!(fragment instanceof SearchFragment)) {
             findViewById(R.id.toolbar).findViewById(R.id.toolbar_search_container).setVisibility(View.GONE);
 
-            MenuInflater inflater = getMenuInflater();
-            inflater.inflate(R.menu.main_menu, menu);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/MainActivity.java]: Are we sure we want to completely remove the main menu?
I think this is ok, but since you removed the menu inflation, you should also remove the corresponding menu layout xml file.

Comment (karkaminski) [reply app/src/main/java/org/schabi/newpipe/MainActivity.java]: Yes. This menu won't be required any more in this activity. I removed main_menu.xml in b965f88e. thanks;)

**Comment by karkaminski** [comment]
> Thank you for your effort! :-D
> Here are a few suggestions:
> 
> * Add `Fixes #2254` to the pr description, so that GitHub knows to automatically close the issue when the pr is merged.
> * Provide a debug apk when opening a pr, so that your changes can be tested by reviewers. You can do this by doing `Build -> Build Bundle(s) / APK(s) -> Build APK(s)` in Android Studio and zipping the apk output.
> * Read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) if you haven't already, as stated in the pr description.

I completed the missing things according to your suggestions :) appreciate your help!
All's good now?

**Comment by karkaminski** [comment]
@Stypox could you please let me know if it's everything good with this PR so far? 
I am a bit nervous about my first steps in OS :scream:

**Comment by karkaminski** [comment]
No problem! 
I just clicked some buttons in GitHub and got confused. Thought that I broke something ;)
My doubt was about a0ee1b1. Should I did this? To be honest - I'm not sure how I done it... 🙀

**Comment by Stypox** [comment]
Yeah, since in the meantime some commits were pushed to this NewPipe repository, your repository became outdated, so GitHub prompted you to write the new changes to your repo to make it up-to-date (using a merge commit).

**Comment by TobiGr** [comment]
@Stypox Feel free to merge once you've reviewed a PR. I trust your judgement. I cannot double and triple check everything. There's simply no time for that,

**Comment by Stypox** [comment]
@TobiGr done. Is it ok how I merged and created the draft version?
@karkaminski thanks again! :-D

**Comment by TobiGr** [comment]
@Stypox Yes. I only changed the target branch from dev to master

File: app/src/main/java/org/schabi/newpipe/MainActivity.java [hunk 2]
```diff
@@ -449,6 +449,16 @@ protected void onResume() {
             sharedPreferences.edit().putBoolean(Constants.KEY_MAIN_PAGE_CHANGE, false).apply();
             NavigationHelper.openMainActivity(this);
         }
+
+        if (sharedPreferences.getBoolean(Constants.KEY_ENABLE_WATCH_HISTORY, true)) {
```
Comment (mauriciocolli) [inline app/src/main/java/org/schabi/newpipe/MainActivity.java]: This should not introduce a new field in the Constants file, instead you should get the key with `getString(R.string.enable_watch_history_key)`.

It comes from this file, where all the setting key are stored (this is done to avoid bugs so we don't need to hard code every time):

https://github.com/TeamNewPipe/NewPipe/blob/0447e4e6645504d24a7752e2f266aa8b2364d4b0/app/src/main/res/values/settings_keys.xml#L174

File: app/src/main/java/org/schabi/newpipe/MainActivity.java [hunk 3]
```diff
@@ -449,6 +449,16 @@ protected void onResume() {
...
+            if (DEBUG) Log.d(TAG, "do not show History-menu as its disabled in settings");
+            drawerItems.getMenu().findItem(ITEM_ID_HISTORY).setVisible(true);
+        }
+
+        if (!sharedPreferences.getBoolean(Constants.KEY_ENABLE_WATCH_HISTORY, true)) {
```
Comment (mauriciocolli) [inline app/src/main/java/org/schabi/newpipe/MainActivity.java]: This check is just a duplicate from above, a variable here would make much more sense:

```java
final boolean isHistoryEnabled = sharedPreferences.getBoolean(
        getString(R.string.enable_watch_history_key), true);
drawerItems.getMenu().findItem(ITEM_ID_HISTORY).setVisible(isHistoryEnabled);
```
