### PR TITLE
checkpoint db before export

### LINKED ISSUE #2508: Backup zip does not restore "remote_playlist" table in newpipe.db file when it was existing in app databases folder
- [ x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
Iam using newpipe version 0.17.0 
I have a playlist(pre existing one) not i created in bookmarked playlist section ,when I do backup of content in export database then later I wipe data and import the database I don't see the playlist(pre made by someone or channel itself) that i have added but the playlist i made can be visible.
So I open the databse to figure  out ,
I found that the table remote_playlist is empty in exported zip ,but it is healthy in /databases/newpipe.db
I am new user of github if I have done any mistake forgive me,and I hope I have brought this to developer notice.
Thank you for such  a amazing app :-)

### LINKED ISSUE #2699: Export
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Exported database does not export subs and playlists. @yausername submitted an apk that worked perfectly, please look into what files that apk is backing up.

### PR DESCRIPTION
**Pull request by yausername**
I have tested on android P. Please test on other android versions before merging.
Related [stackoverflow answer](https://stackoverflow.com/questions/54051322/database-import-and-export-not-working-in-android-pie/54056779#54056779)
Closes #2508, closes #2699

- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java [hunk 1]
```diff
@@ -39,4 +41,14 @@ public static AppDatabase getInstance(@NonNull Context context) {
 
         return result;
     }
+
+    public static void checkpoint() {
+        if(null == databaseInstance){
```
Comment (B0pol) [inline app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java]:
```suggestion
        if (databaseInstance == null) {
```

File: app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java [hunk 2]
```diff
@@ -39,4 +41,14 @@ public static AppDatabase getInstance(@NonNull Context context) {
...
+            throw new IllegalStateException("database is not initialized");
+        }
+        Cursor c = databaseInstance.query("pragma wal_checkpoint(full)", null);
+        if(c.moveToFirst() && c.getInt(0) == 1) {
```
Comment (B0pol) [inline app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java]:
```suggestion
        if (c.moveToFirst() && c.getInt(0) == 1) {
```

**Comment by Stypox** [comment]
Is it possible that this also fixed #3147 ?
