### PR TITLE
Fixed issues #2838 #2797 #2773

### LINKED ISSUE #2773: application17.4 freezes when downloading audio
sorry to report that i have foremost issue with the new update : the application now freezes when downloading audio (with the share feature).
How to reproduce :
Share a link and select Newpipe.
The download dialog appears and i select audio (i leave the default options for the encoding).
Newpipe then starts downloading but freezes. (previous 17.3 works fine with the same link).

Had to rollback to 17.3 for the time being.

- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [ ] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

### LINKED ISSUE #2797: Downloading Audio Naming Problem When Shared from YouTube
- [✔] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [✔] I checked if the issue/feature exists in the latest version.
- [✔] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

on version 0.17.4 when sharing a video from youtube to newpipe to download as audio... on the first try the file name that shows up is the file name from the previously downloaded audio... upon the second try to download it then gets it correct name... happen for all downloads... if i remember correctly i think the first time using this version when dwnloading using my method the first file name came up empty..

### LINKED ISSUE #2838: Bad behavior when downloading videos through native YouTube app share function
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
It does
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
It isn't a crash.

I will post a video since I think it is self explanatory, but I'll summary the few issues.

https://streamable.com/4jyw7

- After selecting a video for download, NewPipe stays opened, frozen, with the youtube screen you had opened (00:23). You have to manually switch from NewPipe to YouTube again.

- After downloading a video, when choosing another one, it brings again the latest video you already downloaded instead the one you are fetching. (00:37). You have to repeat the steps in order to get the actual video you want to download.
Ironically when you cancel, the floating window disappears correctly (so NewPipe doesn't stay open, frozen) and you can continue to browse YouTube.

This behavior wasn't present in past versions. I've been using this feature for as long as I can remember using the app.
I'm using the latest stable version from Github.
Samsung Galaxy J7 2018 (j737a) with android 8.0

### PR DESCRIPTION
**Pull request by Nico-late**
- [✓] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.

I found a way to solve issue #2838  together with issue #2773 and issue #2797 . Youtube seems to freeze as the NewPipe activity is not correctly closed. I added an if statement in DownloadDialog to close the activity when ok is clicked if the activity does not come from the app itself:

As it finishes the activity, when downloading a second video, the name is reset so it also fixes issue #2797 

Fixes #2838
Fixes #2773
Fixes #2797

### CODE REVIEW

**Comment by Stypox** [comment]
Is this related to #2858 ? @Nico-late @pchebel

**Comment by Nico-late** [comment]
We are working together and after we made #2858 , we decided to tackle #2838 . We found a way to solve it and it appears this new solution also solves the issue #2797  (previsously solved by #2858 ).

**Comment by Stypox** [comment]
OK, good :-)

File: app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java [hunk 1]
```diff
@@ -368,6 +369,9 @@ private void initToolbar(Toolbar toolbar) {
         toolbar.setOnMenuItemClickListener(item -> {
             if (item.getItemId() == R.id.okay) {
                 prepareSelectedDownload();
+                if (getActivity() instanceof RouterActivity){
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java]:
```suggestion
                if (getActivity() instanceof RouterActivity) {
```
