### PR TITLE
Fix inconsistency between user interaction and database commit order when re-adding videos to the playlist

### LINKED ISSUE #7402: Cannot readd video to playlist
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a Playlist
2. Reproduce a video inside it in foreground
3. While still reproducing, remove it from the playlist, even without waiting
4. Without exiting the playlist, try readding it to the same playlist.
5. It should not work, until you close and reopen the playlist and readd it again.

### Actual behavior

The video cannot be readded to the same playlist it was just removed from without closing and reopening the playlist first.

### Expected behavior

I'd expect to readd it without having to close and reopen the playlist.

### Device info

 - Android version/Custom ROM version: Lineage OS 18.1 for microG
 - Device model: Oneplus 5

### PR DESCRIPTION
**Pull request by dtcxzyw**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

The reason for this issue is an inconsistency between user interaction and database commit order.

###### Expected behavior
delete - commit (delete) - add - commit (add)
###### Actual behavior
delete - add - commit (add, commit immediately) - commit (delete, commit after ~10s due to the debouncedSaveSignal)
###### Best Solution
Removes all debounced commit strategies. Sequential consistency is guaranteed by database transactions.

But I don't know why the delete operation uses the deferred commit strategy. BTW, I realize PR #8221 could have many conflicts with this solution. So I took a conservative approach to fix it.
###### Current Solution
Concurrent operations on the playlist database occur if and only if the user opens both LocalPlaylistFragment and VideoDetailFragment as described in the related issue. So I force all delete operations to be committed to the database before adding.

#### Before/After Screenshots/Screen Record

- Before:

https://user-images.githubusercontent.com/15650457/163764963-2ef2b4ee-7e0f-426d-9967-7e1d1381e943.mp4

- After:

https://user-images.githubusercontent.com/15650457/163764983-3438a231-a65e-4b3e-965a-8aedad61fafe.mp4

From main page tab:

https://user-images.githubusercontent.com/15650457/166681029-af08dfa5-6c94-4afa-b72b-0679cbef122e.mp4

#### Fixes the following issue(s)

- Fixes #7402

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 1]
```diff
@@ -445,6 +447,14 @@ public void onClick(final View v) {
                 break;
             case R.id.detail_controls_playlist_append:
                 if (getFM() != null && currentInfo != null) {
+                    final Fragment fragment = getParentFragmentManager().
+                            findFragmentById(R.id.fragment_holder);
+
+                    // commit previous pending changes to database
+                    if (fragment instanceof LocalPlaylistFragment) {
+                        ((LocalPlaylistFragment) fragment).commitChanges();
+                    }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:456]: What about the cases when the local playlist fragment is a main page tab?

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you!

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (dtcxzyw) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:456]: This case can also be handled by these lines.
I tested this case on my device. It works fine.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:456]: Mmmh, I don't understand why those lines would handle it. If the fragment is a main page tab, then it is not the parent of the VideoDetailFragment anymore

Comment (dtcxzyw) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:456]: I have added a supplementary video for this case. Did I understand you correctly?

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java]: Fixed in 2de828289f91ef28ad0960fc784f102fc52bde5b

**Comment by TobiGr** [comment]
- Rebased
- Fixed the behaviour when LocalPlaylistFragment is used as frontpage tab

| Before | After |
|---|---|
| [MainTab_LocalPlaylist_Before.webm](https://github.com/TeamNewPipe/NewPipe/assets/17365767/20c7b98f-47b4-4bcb-a173-fafb48d1b920) | [MainTab_LocalPlaylist_After.webm](https://github.com/TeamNewPipe/NewPipe/assets/17365767/6983d147-b886-4aac-844e-31e062768183) |

**Review by TobiGr — APPROVED** [review]
Sorry for the delay and thank you for submitting the fix!

**Review by Stypox — APPROVED** [review]
