### PR TITLE
Fix some random NullPointerExceptions

### LINKED ISSUE #5587: UI Crash (minor bug) : Simultaneously open menus in Settings
### Checklist

- [x] I am using the latest version - 0.20.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Settings.
2. Simultaneously open two or more menus. Back out to the main Settings menu.
3. Repeat until you get a crash.

### Actual behaviour

UI crash.

### Expected behavior

No UI crash.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ CH
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.20.9
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at org.schabi.newpipe.settings.custom.NotificationActionsPreference.saveChanges(NotificationActionsPreference.java:89)
	at org.schabi.newpipe.settings.custom.NotificationActionsPreference.onDetached(NotificationActionsPreference.java:60)
	at androidx.preference.PreferenceGroup.onDetached(PreferenceGroup.java:467)
	at androidx.preference.PreferenceGroup.onDetached(PreferenceGroup.java:467)
	at androidx.preference.PreferenceFragmentCompat.unbindPreferences(PreferenceFragmentCompat.java:493)
	at androidx.preference.PreferenceFragmentCompat.onDestroyView(PreferenceFragmentCompat.java:301)
	at org.schabi.newpipe.settings.NotificationSettingsFragment.onDestroyView(Unknown Source:0)
	at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2908)
	at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1344)
	at androidx.fragment.app.FragmentManager.removeCancellationSignal(FragmentManager.java:730)
	at androidx.fragment.app.FragmentManager$2.onComplete(FragmentManager.java:370)
	at androidx.fragment.app.FragmentAnim$3.onAnimationEnd(FragmentAnim.java:198)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

### LINKED ISSUE #5812: Crash when opening very quickly the search window after NewPipe launch
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open NewPipe and very quickly click on the search icon as soon as it appears

### Actual behaviour

NewPipe crashes.

### Expected behavior

No crash and possibility to search !

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView org.schabi.newpipe.databinding.PlaylistHeaderBinding.playlistTitleView' on a null object reference
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.setTitle(PlaylistFragment.java:449)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.handleResult(BaseListInfoFragment.java:205)
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:273)
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:67)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:135)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(Unknown Source:0)
at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$Gn1fP3-8OJnktT5gkmUmbW-egTg.accept(Unknown Source:4)
at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10 / LineageOS 17.1
 - Device model: Samasung Galaxy S5 (klte)

### PR DESCRIPTION
**Pull request by Stypox**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
I got a random NullPointerException when clicking fast on the search button, this PR should prevent it, even though it should never happen. 
While I was at it I also fixed two other random NPEs.
```
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at org.schabi.newpipe.fragments.list.search.SearchFragment.onOptionsItemSelected(SearchFragment.java:460)
        at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2830)
        ...
```

#### Fixes the following issue(s)

- Fixes #5587
- Fixes #5812

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java [hunk 1]
```diff
@@ -34,6 +34,7 @@
 import androidx.recyclerview.widget.ItemTouchHelper;
 import androidx.recyclerview.widget.RecyclerView;
 
+import org.jetbrains.annotations.NotNull;
```
Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:37]: use the `javax` one

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java [hunk 2]
```diff
@@ -139,7 +140,7 @@
     @State
     boolean wasSearchFocused = false;
 
-    private Map<Integer, String> menuItemToFilterName;
+    @Nullable private Map<Integer, String> menuItemToFilterName = null;
```
Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:143]: Can't this be initialized to an empty map, in order to avoid the null check below?

File: app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java [hunk 3]
```diff
@@ -85,19 +85,22 @@ private void setupActions(@NonNull final View view) {
     ////////////////////////////////////////////////////////////////////////////
 
     private void saveChanges() {
-        final SharedPreferences.Editor editor = getSharedPreferences().edit();
+        if (compactSlots != null && notificationSlots != null) {
```
Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java:88]: Can you add the `@Nullable` to the member fields like you did for `menuItemToFilterName`

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java (hunk 1 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:37]: Oh right

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java (hunk 2 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:143]: No, it can't, since `.get()` is used on it and that would return a valid value only if it has been initialized.

**Comment by Stypox** [comment]
@XiangRongLin done

**Review by XiangRongLin — APPROVED** [review]
