### PR TITLE
Ugly fix for broken text colors in dark mode

### LINKED ISSUE #12016: UI bug - theme - dark mode - broken text colors (Black)
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.6

### Steps to reproduce the bug

Set Dark mode (not black. Dark mode) 
Refresh subscription
Enter video
Restart app
Refresh subscription
Enter video details or comments

### Expected behavior

Text should be white/gray, not black.

### Actual behavior

See the screenshot. This happens on video, comments, subscribed video list.

Image

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

_No response_

### Affected device model

_No response_

### Additional information

Issue noticed around 0.27.4? Don't remember exactly.

### PR DESCRIPTION
**Pull request by Thompson3142**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
An ugly fix for the issue that the text color is black in dark/black mode. WebView is unfortunately messing with the theme with no real way to prevent it (at least from my observation). 
For some further reference: https://issuetracker.google.com/issues/37124582. 
I am not entirely sure why this exactly helps but it seems like the first WebView instantiated sets the theme/context and following ones don't change it again? 
If there is some other change that directly prevents this bug from occurring it should definitely be preferred.

#### Fixes the following issue(s)
- Fixes #12016

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Stypox** [comment]
Thank you for investigating! Maybe add a comment in the code

File: app/src/main/java/org/schabi/newpipe/MainActivity.java [hunk 1]
```diff
@@ -140,6 +141,11 @@ protected void onCreate(final Bundle savedInstanceState) {
         ThemeHelper.setDayNightMode(this);
         ThemeHelper.setTheme(this, ServiceHelper.getSelectedServiceId(this));
 
+        // Fixes text color turning black in dark/black mode:
+        // https://github.com/TeamNewPipe/NewPipe/issues/12016
+        // For further reference see: https://issuetracker.google.com/issues/37124582
+        new WebView(this);
```
Comment (AudricV) [inline app/src/main/java/org/schabi/newpipe/MainActivity.java:147]: Please ensure there is a WebView provider available with [`DeviceUtils.supportsWebView`](https://github.com/TeamNewPipe/NewPipe/blob/c6e17218843e59f264f39d9cd719c1173a95abfd/app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java#L344), otherwise users without a WebView wouldn't be able to use the app, as it would crash due to no WebView installed or enabled (already happening for licenses' WebViews)

**Review by AudricV — DISMISSED** [review]

File: app/src/main/java/org/schabi/newpipe/MainActivity.java (hunk 1 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/MainActivity.java:147]: Oh, right, nice catch. You could also add a try-catch around it, just to make sure.

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/MainActivity.java:147]: Oh yes I forgot. Then no need for an additional try-catch, *nice catch* ;-)

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/MainActivity.java:147]: Actually I meant to add a try-catch around the webview instantiation, which might still fail for unknown reasons

**Review by Stypox — APPROVED** [review]

File: app/src/main/java/org/schabi/newpipe/MainActivity.java [hunk 2]
```diff
@@ -140,6 +141,19 @@ protected void onCreate(final Bundle savedInstanceState) {
         ThemeHelper.setDayNightMode(this);
         ThemeHelper.setTheme(this, ServiceHelper.getSelectedServiceId(this));
 
+        // Fixes text color turning black in dark/black mode:
+        // https://github.com/TeamNewPipe/NewPipe/issues/12016
+        // For further reference see: https://issuetracker.google.com/issues/37124582
+        if (DeviceUtils.supportsWebView()) {
+            try {
+                new WebView(this);
+            } catch (final Exception e) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/MainActivity.java:150]:
```suggestion
            } catch (final Throwable e) {
```
