### PR TITLE
Fixes hashtags that use non-English characters.

### LINKED ISSUE #7441: Hashtags with accented characters not properly recognised
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

- Search Youtube for "déconspirateurs 05"
- In the results, open "Les Déconspirateurs - l'émission 05"

### Actual behavior

See the description, whenever a hashtag contains an accented character, Newpipe generates a link which stops before the first accented character. For example, #extrêmisme is rendered as a #extr instead, while the rest is displayed as regular text.

### Expected behavior

Newpipe should consider accented characters as regular letters.

### Screenshots/Screen recordings

Screenshot_2021-11-24-21-47-39-571_org schabi newpipe

### Device info

 - Android 11 / MIUI 12.5.6
 - Device model: Redmi Note 10 Pro

### PR DESCRIPTION
**Pull request by Jaspann**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
Fixes hashtags that use non-English characters. Hashtags would now include any character above Unicode value U+007F . This solves problems of hashtags with accented characters as well as hashtags in other languages.

#### Before/After Screenshots/Screen Record

- Before:
143439151-6fceee5a-3b7b-4e90-ac75-5955ace623b1 Screenshot_20211219-205219

- After:
fixedHashtags fixedHashtagsCh

#### Fixes the following issue(s)

- Fixes #7441 

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java [hunk 1]
```diff
@@ -33,7 +33,8 @@
 public final class TextLinkifier {
     public static final String TAG = TextLinkifier.class.getSimpleName();
 
-    private static final Pattern HASHTAGS_PATTERN = Pattern.compile("(#[A-Za-z0-9_]+)");
+    private static final Pattern HASHTAGS_PATTERN =
+            Pattern.compile("(#[A-Za-z0-9_\\u0080-\\uFFFF]+)");
```
Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java:37]: Could you add an comment on what `\\u0080-\\uFFFF` is? From the looks of it, it is all unicode characters except the first 80

Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java:37]: How does it handle a text with multiple hashtags in it like `#tag#noSpaceAnotherTag`

Comment (XiangRongLin) [inline app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java:37]: How does it handle URLs with an hashtag anchor like https://teamnewpipe.github.io/documentation/00_Prepare_everything/#content-that-is-not-permitted
If it didn't work beforehand then don't bother with it

**Review by TobiGr — COMMENTED** [review]
Do we have tests for this regex? If not, we should create a few.

**Comment by XiangRongLin** [comment]
> Do we have tests for this regex? If not, we should create a few.

@TobiGr I thought about it at first too because we don't currently have them and this seems easily testable. But the code combines recognizing the hashtags (or links) and applying the onClickListeners to the UI making it very hard to add tests.

I would not put the burden on a first timer

---
The failed pipeline is not related to this change

File: app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java (hunk 1 above)
Comment (Jaspann) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java:37]: It will treat it as two seperate hashtags #tag and #noSpaceAnotherTag. This is how it worked before and is how it is treated by Youtube.

**Comment by TobiGr** [comment]
@XiangRongLin I thought more of basic unit tests to ensure the regex is working as expected. Not more. But if you think this should be done in a separate PR, that's not a problem at all.
@Jaspann It's up to you to decide whether you want to create unit tests or not :P

**Comment by Jaspann** [comment]
@TobiGr I don't know really anything about unit testing so I would prefer not to.

File: app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java (hunk 1 above)
Comment (Jaspann) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java:37]: URLs with hashtag anchors work correctly. This does not change anything with this part of the code, and it was working before this commit. For this commit I tested this type of case and there was no change.

**Comment by Jaspann** [comment]
I'm sorry, I found some problems with this solution and want to commit a solution that is much more accurate to how hashtags work. Should I commit here or close this PR and open a new one? Once again I am sorry, as this is my first time committing to a public repo and I don't really know how it works.

**Comment by Jaspann** [comment]
@XiangRongLin I'm sorry, I found some problems with this solution and want to commit a solution that is much more accurate to how hashtags work. Should I commit here or close this PR and open a new one? Once again I am sorry, as this is my first time committing to a public repo and I don't really know how it works.

**Comment by TiA4f8R** [comment]
> Should I commit here or close this PR and open a new one?

No, commit here and force-push if needed. If needed, we will squash your commits if we merge this PR.

> I found some problems with this solution and want to commit a solution that is much more accurate to how hashtags work

According to your comment, I am converting this PR to draft.

File: app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java (hunk 1 above)
Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java]: Outdated

Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java]: Outdated

Comment (TiA4f8R) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java]: Outdated

**Review by XiangRongLin — APPROVED** [review]
LGTM 

https://www.regular-expressions.info/unicode.html
