### PR TITLE
Fixed a bug that caused erroneous updates of the playlist thumbnails

### LINKED ISSUE #9458: Playlist thumbnail doesn't get updated after the "Remove Watched" dialog is used
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Create a new playlist with two videos
2. Go to playlist overview
3. Go to the newly created playlist
4. Click "Background"
5. Listen for a couple of seconds
6. Click "Removed Watched"
7. Click "Yes, and partially watched videos"
8. Go to Playlist Overview

### Expected behavior

The thumbnail of the playlist should have changed to the only item in the playlist. 

### Actual behavior

The thumbnail doesn't get updated.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/26669009/203877279-809cfc90-4c17-4635-b995-1dde58416bce.mp4

### Logs

_No response_

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 5

### Additional information

I am a developer and plan to work on this problem myself.

### PR DESCRIPTION
**Pull request by Jared234**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

This is an attempt to fix the bug mentioned in #9458.
Currently, NewPipe stores the `thumbnailUrl` in the database. I deleted this field and replaced it with the `thumbnailStreamId` field, which stores the stream ID of the stream the thumbnail is from.
Since the `thumbnailUrl` is deeply rooted in the program, I had to make significant changes and perform a database migration to fix this problem. 

#### Fixes the following issue(s)

- Fixes #9458 

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/database/Migrations.java [hunk 1]
```diff
@@ -197,6 +198,47 @@ public void migrate(@NonNull final SupportSQLiteDatabase database) {
...
+            database.execSQL("CREATE TEMPORARY TABLE temporary_table AS"
+                    + " SELECT p.uid AS playlist_uid, s.uid AS stream_uid"
+                    + " FROM playlists p"
+                    + " LEFT JOIN playlist_stream_join ps ON p.uid = ps.playlist_id"
+                    + " LEFT JOIN streams s ON s.uid = ps.stream_id"
+                    + " WHERE s.thumbnail_url = p.thumbnail_url");
+
+            database.execSQL("UPDATE playlists SET thumbnail_stream_id = ("
+                    + "SELECT CASE WHEN COUNT(*) != 0 then stream_uid ELSE -1 END "
+                    + "FROM temporary_table "
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/database/Migrations.java:218]: Why is the temporary table needed? Can't you replace `temporary_table` here with `(SELECT p.uid AS ...) AS temporary_table`?

File: app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java [hunk 2]
```diff
@@ -87,21 +89,36 @@ default Flowable<List<PlaylistStreamEntity>> listByService(final int serviceId)
...
+    @Query("SELECT " + PLAYLIST_ID + ", " + PLAYLIST_NAME + ","
+
+            + " CASE WHEN " + PLAYLIST_THUMBNAIL_STREAM_ID + " = -1"
+            + " THEN " + "'" + DEFAULT_THUMBNAIL + "'"
+            + " ELSE (SELECT " + STREAM_THUMBNAIL_URL
+            + " FROM " + STREAM_TABLE
+            + " WHERE " + STREAM_TABLE + "." + STREAM_ID + " = " + PLAYLIST_THUMBNAIL_STREAM_ID
+            + " ) END AS " + PLAYLIST_THUMBNAIL_URL + ", "
 
+            + PLAYLIST_NAME + ", "
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java:101]: I think you are including the playlist name twice

File: app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java [hunk 3]
```diff
@@ -87,21 +89,36 @@ default Flowable<List<PlaylistStreamEntity>> listByService(final int serviceId)
...
-            + "COALESCE(COUNT(" + JOIN_PLAYLIST_ID + "), 0) AS " + PLAYLIST_STREAM_COUNT + ", "
+
+            + " CASE WHEN " + PLAYLIST_THUMBNAIL_STREAM_ID + " = -1"
+            + " THEN " + "'" + DEFAULT_THUMBNAIL + "'"
+            + " ELSE (SELECT " + STREAM_THUMBNAIL_URL
+            + " FROM " + STREAM_TABLE
+            + " WHERE " + STREAM_TABLE + "." + STREAM_ID + " = " + PLAYLIST_THUMBNAIL_STREAM_ID
+            + " ) END AS " + PLAYLIST_THUMBNAIL_URL
+
+            + ", COALESCE(COUNT(" + JOIN_PLAYLIST_ID + "), 0) AS " + PLAYLIST_STREAM_COUNT + ", "
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java:121]: Just for consistency
```suggestion
            + " ) END AS " + PLAYLIST_THUMBNAIL_URL + ", "

            + "COALESCE(COUNT(" + JOIN_PLAYLIST_ID + "), 0) AS " + PLAYLIST_STREAM_COUNT + ", "
```

File: app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java [hunk 4]
```diff
@@ -57,14 +59,14 @@ default Flowable<List<PlaylistStreamEntity>> listByService(final int serviceId)
...
-    @Query("SELECT CASE WHEN COUNT(*) != 0 then " + STREAM_THUMBNAIL_URL + " ELSE :defaultUrl END"
+    @Query("SELECT CASE WHEN COUNT(*) != 0 then " + STREAM_ID + " ELSE -1 END"
             + " FROM " + STREAM_TABLE
             + " LEFT JOIN " + PLAYLIST_STREAM_JOIN_TABLE
             + " ON " + STREAM_ID + " = " + JOIN_STREAM_ID
             + " WHERE " + JOIN_PLAYLIST_ID + " = :playlistId "
             + " LIMIT 1"
     )
-    Flowable<String> getAutomaticThumbnailUrl(long playlistId, String defaultUrl);
+    Flowable<Long> getAutomaticThumbnailUrl(long playlistId);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java:69]:
```suggestion
    Flowable<Long> getAutomaticThumbnailStreamId(long playlistId);
```

File: app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java [hunk 5]
```diff
@@ -154,17 +155,19 @@ private void onPlaylistSelected(@NonNull final LocalPlaylistManager manager,
...
+                .subscribe(ignored -> {
+                    successToast.show();
+
+                    if (playlist.thumbnailUrl.equals(PlaylistEntity.DEFAULT_THUMBNAIL)) {
+                        playlistDisposables.add(manager
+                                .changePlaylistThumbnail(playlist.uid, streams.get(0).getUid(),
+                                        false)
+                                .observeOn(AndroidSchedulers.mainThread())
+                                .subscribe(ignore -> successToast.show()));
+                    }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java:169]: Why was this moved here?

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java [hunk 6]
```diff
@@ -70,6 +70,8 @@
 import io.reactivex.rxjava3.subjects.PublishSubject;
 
 public class LocalPlaylistFragment extends BaseLocalListFragment<List<PlaylistStreamEntry>, Void> {
+    public static final long DEFAULT_THUMBNAIL_ID = -1;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java:73]: Move this to `PlaylistEntity` and also use it in the `PlaylistStreamDAO` queries

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java [hunk 7]
```diff
@@ -70,6 +70,8 @@
...
+    public static final long NO_THUMBNAIL_ID = -2;
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java:74]: Since this value is only used internally in `LocalPlaylistManager`, remove it from here and move it there. I would also call it `THUMBNAIL_ID_LEAVE_UNCHANGED`.

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java [hunk 8]
```diff
@@ -43,28 +42,34 @@ public Maybe<List<Long>> createPlaylist(final String name, final List<StreamEnti
...
         final PlaylistEntity newPlaylist =
-                new PlaylistEntity(name, defaultStream.getThumbnailUrl(), false);
+                new PlaylistEntity(name, false, defaultStream.getUid());
 
-        return Maybe.fromCallable(() -> database.runInTransaction(() ->
-                upsertStreams(playlistTable.insert(newPlaylist), streams, 0))
-        ).subscribeOn(Schedulers.io());
+        return Maybe.fromCallable(() -> database.runInTransaction(() -> {
+                    final List<Long> streamIds = streamTable.upsertAll(streams);
+                    newPlaylist.setThumbnailStreamId(streamIds.get(0));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java:49]: I don't think you need to call `setThumbnailStreamId` again, haven't you already called `defaultStream.getUid()` above? Upsert shouldn't change ids afaik. (this would mean that changes to `insertJoinEntities` could be reverted)

**Review by Stypox — CHANGES_REQUESTED** [review]
Also nice change. Thanks!

File: app/src/main/java/org/schabi/newpipe/database/Migrations.java (hunk 1 above)
Comment (Jared234) [reply app/src/main/java/org/schabi/newpipe/database/Migrations.java:218]: Yes, I used a temporary table because it is more readable. But I understand why you would want to replace it, so I changed it.

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java (hunk 8 above)
Comment (Jared234) [reply app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java:51]: Unfortunately, you have to set it again after upserting the stream.
Streams have a default `uid` value of `0`, so `0` is always returned in the first `defaultStream.getUid()` method. Only after the stream has been upserted it is given a unique ID. Therefore, you must first upsert it and then set the `streamId` of the `PlaylistEntity`.

File: app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java (hunk 5 above)
Comment (Jared234) [reply app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java:169]: The reason for this change is addressed in [this comment](https://github.com/TeamNewPipe/NewPipe/pull/9755#discussion_r1102103768).

**Comment by Jared234** [comment]
Thanks for the review.

**Comment by Jared234** [comment]
@Stypox Could you perhaps take another look at this? I'm working on NewPipe as part of a project at my university and only contributions pushed by March 1st can count towards my grade. So I would very much appreciate another review.
However, if you don't have time in the next few days, that shouldn't be a problem for NewPipe, since I will finish work on any outstanding issues either way.

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java (hunk 8 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java:51]: Then can't `newPlaylist` be created here, directly with the correct `streamId`?

File: app/src/main/java/org/schabi/newpipe/database/Migrations.java [hunk 9]
```diff
@@ -197,6 +198,43 @@ public void migrate(@NonNull final SupportSQLiteDatabase database) {
...
+                    + " LEFT JOIN streams s ON s.uid = ps.stream_id"
+                    + " WHERE s.thumbnail_url = p.thumbnail_url) AS temporary_table"
+                    + " WHERE playlist_uid = playlists.uid)");
+
+            // Remove the thumbnail_url field in the playlist table
+            database.execSQL("CREATE TABLE IF NOT EXISTS `playlists_new`"
+                    + "(uid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
+                    + "name TEXT, "
+                    + "is_thumbnail_permanent INTEGER NOT NULL, "
+                    + "thumbnail_stream_id INTEGER NOT NULL)");
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/database/Migrations.java:224]: Shouldn't `thumbnail_stream_id` be a foreign key to the streams table?

**Review by Stypox — CHANGES_REQUESTED** [review]
Thanks for the ping. This is almost ready :-)

File: app/src/main/java/org/schabi/newpipe/database/Migrations.java (hunk 9 above)
Comment (Jared234) [reply app/src/main/java/org/schabi/newpipe/database/Migrations.java:224]: The `thumbnail_stream_id` can be `-1` to indicate a default thumbnail and not always reference a stream. Therefore, IMO it isn't necessary to use it as a foreign key to the streams table.

**Comment by Jared234** [comment]
Thanks for the review.

**Review by Stypox — APPROVED** [review]
Looks good to me, thank you! I tested by creating some playlists and playing with thumbnails, and then by importing my database. Good luck with the university course ;-)

**Comment by Jared234** [comment]
Thanks for all the help and support during my course. Working with NewPipe was awesome, and I learned a lot. I had a lot of fun, and I'm definitely planning on continuing to work on it after my exams are over. Keep up the great work!
