### PR TITLE
Migrate to Android DayNight Theme, fix Light Theme, minor UI improvements

### LINKED ISSUE #3042: Polish white theme: make app bar text and icons white
This is how the white theme looks like:

As you can see text and icons in the title bar are black, even though they are on the exact same red background as in the dark theme. Black on red looks strange, so text and icons should be white, as in the Retry button

### PR DESCRIPTION
**Pull request by krlvm**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Fixed Dark Text & Dark Icons in Light Theme
- Fixed Light Navigation Bar Icons in Light Theme
- Navigation Bar in Splash Screen is red like it's background now
- All styles relies on Android's DayNight Theme now
- Light Theme is now looks properly, so I changed default theme from Dark to Automatic
- All `_white` and `_black` assets have been separated in `drawable` and `drawable-night`, `ThemeHelper.resolveResourceIdFromAttr` is no longer used - it should improve the overall performance, but I did not run benchmarks
- Styles, attributes XML code cleanup
- Slightly reduced installed app size (installed v0.21.0-release: 17MB -> 14,68MB debug version)

#### Fixes the following issue(s)

- Fixes #3042

#### APK testing 

On the website the APK can be found by going to the "Checks" tab below the title and then on "artifacts" on the right.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by krlvm** [comment]
I just finished checking everything down to the smallest detail on all topics, so I think I'm done.

<details>
<summary>Some screenshots compared to v0.21.0</summary>
</img>
</img>
</img>
</img>
</img>
</img>
</details>

**Comment by krlvm** [comment]
I just finished checking everything down to the smallest detail on all topics, so I think I'm done.

<details>
<summary>Some screenshots compared to v0.21.0</summary>
</img>
</img>
</img>
</img>
</img>
</img>
</details>

**Comment by Stypox** [comment]
@krlvm thank you for this huge improvement! It does have many benefits. Could you better explain how this new theming strategy works? Since there are ~300 changed files I don't understand which ones contain the important changes.

**Comment by krlvm** [comment]
> @krlvm thank you for this huge improvement! It does have many benefits. :-D
> Could you better explain how this new theming strategy works? Since there are ~300 changed files I don't understand which ones contain the important changes.
> Also, did you test on API 19?
> 
> @TobiGr I'd give priority to this PR, is would be painful to rebase 300 files ;-)

In fact, this number is not scary, I just renamed all files like `ic_x_white_24dp` to `ic_x`, as well as all references to it. Likewise with dark versions moved to `drawable-night`. That's where the 300 changes come from, though 
image
The theming strategy has not been changed much for that. To make the resource source automatically change from `drawable` to` drawable-night`, we use `AppCompatDelegate.setDefaultNightMode()`, which is available by using `DayNight` as the base theme.
To force invert the colors of the drawables (for example, the control buttons in the player are always white), we give the layout the WhiteTint theme.

File: app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedImportExportItem.kt [hunk 1]
```diff
@@ -115,7 +115,7 @@ class FeedImportExportItem(
     private fun setupExportToItems(listHolder: ViewGroup) {
         val previousBackupItem = addItemView(
             listHolder.context.getString(R.string.file),
-            ThemeHelper.resolveResourceIdFromAttr(listHolder.context, R.attr.ic_save),
+            R.drawable.ic_save,
             listHolder
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedImportExportItem.kt:119]: Consistency with above
```suggestion
            R.drawable.ic_save, listHolder
```

File: app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java [hunk 2]
```diff
@@ -288,4 +290,21 @@ public static boolean isDeviceDarkThemeEnabled(final Context context) {
...
+        if (selectedThemeKey.equals(res.getString(R.string.light_theme_key))) {
+            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
+        } else if (selectedThemeKey.equals(res.getString(R.string.dark_theme_key))
+                || selectedThemeKey.equals(res.getString(R.string.black_theme_key))) {
+            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
+        } else {
+            AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM);
+        }
+    }
 }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java:310]: Check if `resolveResourceIdFromAttr` can be removed, and remove it if that's the case

File: app/src/main/res/layout-large-land/fragment_video_detail.xml [hunk 3]
```diff
@@ -605,6 +605,7 @@
                 android:layout_width="match_parent"
                 android:layout_height="wrap_content"
                 android:layout_gravity="bottom|center"
+                app:tabIndicatorGravity="top"
```
Comment (Stypox) [inline app/src/main/res/layout-large-land/fragment_video_detail.xml:608]: I like this :-)

File: app/src/main/res/values/settings_keys.xml [hunk 4]
```diff
@@ -181,7 +181,7 @@
     <string name="dark_theme_key" translatable="false">dark_theme</string>
     <string name="black_theme_key" translatable="false">black_theme</string>
     <string name="auto_device_theme_key" translatable="false">auto_device_theme</string>
-    <string name="default_theme_value" translatable="false">@string/dark_theme_key</string>
+    <string name="default_theme_value" translatable="false">@string/auto_device_theme_key</string>
```
Comment (Stypox) [inline app/src/main/res/values/settings_keys.xml:184]: Also this looks reasonable

File: app/src/main/res/values/styles.xml [hunk 5]
```diff
@@ -9,7 +13,13 @@
     </style>
 
     <!-- Base themes -->
-    <style name="Base.LightTheme" parent="Theme.AppCompat.Light.NoActionBar" />
+    <style name="Base.V7" parent="Theme.AppCompat.DayNight.NoActionBar"/>
```
Comment (Stypox) [inline app/src/main/res/values/styles.xml:16]: Maybe add a comment here to explain that all of this is done in order to allow overriding the styles on newer versions of android with `values-vXX/styles.xml`

File: app/src/main/res/values/styles.xml [hunk 6]
```diff
@@ -337,4 +179,20 @@
         <item name="android:windowAnimationStyle">@null</item>
     </style>
 
+    <style name="ToolbarTheme" parent="ThemeOverlay.AppCompat.Dark.ActionBar">
+        <item name="android:textColorPrimary">@android:color/white</item>
+        <item name="android:textColorSecondary">@android:color/white</item>
+        <item name="popupTheme">@style/ThemeOverlay.AppCompat.DayNight.ActionBar</item>
+        <item name="tint">@color/white</item>
+        <item name="iconTint">@color/white</item>
+        <item name="android:textCursorDrawable">@drawable/white_edit_text_cursor</item>
```
Comment (Stypox) [inline app/src/main/res/values/styles.xml:188]: Question: ain't there a way to change the color of the cursor without introducing a new variable?

**Review by Stypox — CHANGES_REQUESTED** [review]
Looks mostly good to me, I also tested a little bit and everything seems fine. Thank you! :-D

File: app/src/main/res/layout-large-land/fragment_video_detail.xml (hunk 3 above)
Comment (krlvm) [reply app/src/main/res/layout-large-land/fragment_video_detail.xml:608]: Forgot to mention this in changelist

File: app/src/main/res/values/styles.xml (hunk 6 above)
Comment (krlvm) [reply app/src/main/res/values/styles.xml:188]: I remember it depends on accent color, I will try changing it for the container

File: app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java (hunk 2 above)
Comment (krlvm) [reply app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java:310]: It can be removed

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java:310]: Remove it ;-)

File: app/src/main/res/values/styles.xml (hunk 5 above)
Comment (krlvm) [reply app/src/main/res/values/styles.xml:16]: This architecture was already present in the code ([i think it was done using this answer](https://stackoverflow.com/a/40841611)) V7 stands for API version 7. `LightTheme` inherits `Base.LightTheme,` which inherits `Base.V7.LightTheme` by default (I mean if API version < 21), but if API version is 21, `Base.LightTheme` inherits `Base.V21.LightTheme`, which inherits `Base.V7.LightTheme`; if API version is 29, for example, if API version is 29, `Base.LightTheme` inherits `Base.V29.LightTheme`, which inherits `Base.V27.LightTheme`, which inherits `Base.V21.LightTheme`, which inherits `Base.V7.LightTheme` - so we don't need to repeat all the code in values, `values-v21`, `values-v27`, `values-v29`, etc.

And I think V7 can be renamed to V19, because the min API is 19, but but this will not affect the functionality.

**Comment by krlvm** [comment]
> Also, did you test on API 19?

I remember DayNight theme works correctly on KitKat, but I think it needs additional testing.

**Comment by Stypox** [comment]
@krlvm
Under white theme:
- the icons in "Settings -> Content -> Peertube instances" and "Settings -> Content -> Content of main page" are black.
- the file chooser has a black title (e.g. try to import database)
- the error activity has white text on white background (to test this click "Settings -> Debug -> Crash the app" twice)
- the search button when adding subscriptions to a subscription group is white, and the "v" overlay above selected subscriptions is black-on-black
- the in-player queue and the in-player chapter list has white-on-white text (to test this enable auto enqueue and search for a video with chapters, e.g. the first result for "youtube chapters")
- the in-player "Captions" and "Quality" selectors are dark even on white theme (maybe this is ok, open to discussion). This is the case for the selectors in the popup player
- the queue accessible via a background/popup notification has an app bar with black icons and a strange shade at the bottom

**Comment by krlvm** [comment]
Under white theme:

- [ ] the icons in "Settings -> Content -> Peertube instances" and "Settings -> Content -> Content of main page" are black.
- [ ] the file chooser has a black title (e.g. try to import database)
- [ ] the error activity has white text on white background (to test this click "Settings -> Debug -> Crash the app" twice)
- [ ] the search button when adding subscriptions to a subscription group is white, and the "v" overlay above selected subscriptions is black-on-black
- [ ] the in-player queue and the in-player chapter list has white-on-white text (to test this enable auto enqueue and search for a video with chapters, e.g. the first result for "youtube chapters")
- [ ] the in-player "Captions" and "Quality" selectors are dark even on white theme (maybe this is ok, open to discussion). This is the case for the selectors in the popup player
- [ ] the queue accessible via a background/popup notification has an app bar with black icons and a strange shade at the bottom

**Comment by Stypox** [comment]
<details>
<summary>@krlvm This is the play queue on Android 10</summary>

</details>

**Comment by krlvm** [comment]
I can see the shadow in v0.20.0, it is from `player_controls_background`, remove it?

**Comment by Stypox** [comment]
@krlvm yes please

**Comment by krlvm** [comment]
@Stypox

I've resolved the issues above and [left some notes in italics](https://github.com/TeamNewPipe/NewPipe/pull/5927#issuecomment-808902160).
I also disabled colored navigation bar in API < 27 to avoid this:

**Comment by Stypox** [comment]
> I think it would be more consistent and comfortable if chapters/queue overlays would be dark in Light theme too (because the Controls overlay is Dark), so I made the popups always Dark too

Ok, looks good

Will test and check everything again later

File: app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java [hunk 7]
```diff
@@ -145,10 +148,13 @@ public void onCreateOptionsMenu(final Menu menu, final MenuInflater inflater) {
...
         restoreItem.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
-
-        final int restoreIcon = ThemeHelper
-                .resolveResourceIdFromAttr(requireContext(), R.attr.ic_restore_defaults);
-        restoreItem.setIcon(AppCompatResources.getDrawable(requireContext(), restoreIcon));
+        final Drawable icon = AppCompatResources.getDrawable(requireContext(),
+                R.drawable.ic_settings_backup_restore);
+        if (icon != null) {
+            icon.mutate();
+            icon.setColorFilter(Color.WHITE, PorterDuff.Mode.SRC_ATOP);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java:155]: Shouldn't you add another icon for this case, too? Or am I missing something?

File: app/src/main/res/drawable/splash_background.xml [hunk 8]
```diff
@@ -1,6 +1,12 @@
...
+    <item
+        android:drawable="@color/light_youtube_primary_color"/>
 
-</layer-list>
+    <item>
+        <bitmap
+            android:src="@drawable/ic_newpipe_triangle_white"
+            android:gravity="center_vertical|center_horizontal" />
+    </item>
+</layer-list>
```
Comment (Stypox) [inline app/src/main/res/drawable/splash_background.xml:12]: Could you explain the changes in this file?

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java [hunk 9]
```diff
@@ -486,6 +486,9 @@ private void showSearchOnStart() {
                     + lastSearchedString);
         }
         searchEditText.setText(searchString);
+        if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.LOLLIPOP) {
+            searchEditText.setHintTextColor(searchEditText.getTextColors().withAlpha(128));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:490]: What's up with these `.withAlpha()` calls?

**Review by Stypox — CHANGES_REQUESTED** [review]

**Comment by Stypox** [comment]
Under white theme:
- the icons in "Settings -> Content -> Content of main page" are still black
- the error activity has white text on white background (still there, see screenshot below)
- the three-dot button on downloads is black (see screenshot)

<details></details>

File: app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java (hunk 7 above)
Comment (krlvm) [reply app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java:155]: SettingsActivity uses AppBar when other components use Toolbar, which accepts `iconTint` theme attribute - it can't be applied to AppBar. I can add a white drawable or delete the black one and replace it with white because it is not used in other places.

File: app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java (hunk 9 above)
Comment (krlvm) [reply app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java:490]: Material Design guidelines say that hint color should be 50% lighter than text color, on Android Lollipop and higher the color you pass to `setHintTextColor` automatically brightens by 50%, but not on KitKat.
`ColorStateList.withAlpha` accepts `int` in range of 0-255, 255 is for 100% and 0 is for 0% opacity.

File: app/src/main/res/drawable/splash_background.xml (hunk 8 above)
Comment (krlvm) [reply app/src/main/res/drawable/splash_background.xml:12]: The app has two splashes: this one and splash for API >= 23.
Before this change this splash was completely black because the one for new APIs doesn't work correctly here - API < 23 doesn't support setting layer-list's item size.
So when I launched the app on my slow Lollipop phone I thought that the phone froze, but it turned out to be a black NewPipe's Splash Screen.
I changed the background to red (that used in the newer splash screen) and logo `item` to `bitmap`, which shows correctly.

**Comment by krlvm** [comment]
@Stypox I resolved the issues above, also I removed the red line under "Pending"/"Finished" (it seems it is from Android 4.x Holo Theme).
Still can't reproduce Crash Activity bug (Android 10):
<details>

</details>

**Comment by Stypox** [comment]
@krlvm oh, strange. I was able to get the correct colors once. Another time, with the same APK and the same actions, I got the white text. What could be happening here? Could it be that the Android context has some problems? Maybe try to crash the app multiple times and see if it happens to you, too

**Comment by krlvm** [comment]
> @krlvm oh, strange. I was able to get the correct colors once. Another time, with the same APK and the same actions, I got the white text. What could be happening here? Could it be that the Android context has some problems? Maybe try to crash the app multiple times and see if it happens to you, too

I assume it is because the Base theme has not applied at the moment it draws the layout, so it is stuck on OpeningTheme.

**Comment by krlvm** [comment]
@Stypox it should be fixed now, try again, please

**Comment by krlvm** [comment]
Hello, anything new?
I'm afraid it will get harder to merge over time

**Comment by Stypox** [comment]
The icons of the items in "Settings -> Content -> Content of main page -> + -> Kiosk page" are white under white theme, even though they should be black. This is not caused by your PR, but if it's not an issue please fix it while you are at it ;-)

**Comment by krlvm** [comment]
Should be fixed now

**Comment by Stypox** [comment]
- This happens on API 19 and API 30, but not on my phone with API 29:


- This happens only on API 19:


- Some icons in the notification on API 19 are invisible (I noticed the buffering icon and the close icon in particular, but maybe even others, idk if this was caused by this PR)

**Comment by krlvm** [comment]
Can't reproduce the last issue, two others were fixed

**Review by Stypox — CHANGES_REQUESTED** [review]
The player issue is still not fixed on API 19 (emulator):

**Comment by TacoTheDank** [comment]
I'm actually really excited for this PR (DayNight usage something I've wanted for quite a while, plus no more themed drawables). Hoping as many bugs as possible will be ironed out before merge-time :)

**Comment by Redirion** [comment]
actually it appears this is already ironed out alot? Why not merge it and let it test with the RC for the next release?

**Comment by krlvm** [comment]
I cannot find any more problems on the last two versions of Android, which I use, at least in the most used activities, but additional flaws in API 19 may be revealed. Anyway, thanks for taking the time to find those problems that I could not  discover before opening PR.

**Comment by TobiGr** [comment]
Did anyone test this on a TV?

**Comment by Stypox** [comment]
@TobiGr I didn't think of that, I'm going to test now on an emulator

**Comment by Stypox** [comment]
I tested again, even on an emulated TV (API 29), and couldn't find anything wrong, both in white and dark/black theme. I think this can be merged, since potential problems would anyway only be color problems, not usability issues.

**Review by Stypox — APPROVED** [review]

**Comment by undeadfox** [comment]
Release build failed:
`app/src/release/res/xml/main_settings.xml:43: AAPT: error: resource drawable/ic_cloud_download_black (aka org.schabi.newpipe:drawable/ic_cloud_download_black) not found.`

**Comment by krlvm** [comment]
> Release build failed:
> `app/src/release/res/xml/main_settings.xml:43: AAPT: error: resource drawable/ic_cloud_download_black (aka org.schabi.newpipe:drawable/ic_cloud_download_black) not found.`

Try replacing [`ic_cloud_download_black`](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/release/res/xml/main_settings.xml#L45) with `ic_cloud_download`
