### PR TITLE
Commit all the playlist changes to db immediately

### LINKED ISSUE #11138: "Remove watched" with "Remove duplicates" without closing and re-opening the playlist does not work correctly
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Create a new playlist with two contents, one watched, and one not watched. Also add a duplicate for each content. You should have two copies of the watched content, and two copies of the non-watched content.
2. Open that playlist
3. `...` -> "Remove watched" -> "OK"; the two copies of the watched content should have been removed, and only the two copies of the non-watched content should remain
4. Without exiting, `...` -> "Remove duplicates" -> "OK"

### Expected behavior

What should happen is that one of the two copies of the content that is left in the playlist should be removed, leaving only one copy of the non-watched content in the playlist.

### Actual behavior

What actually happens is that the contents that were previously deleted by "Remove watched" are added back, and then, from the original state of the playlist (2x watched + 2x non-watched) duplicates are removed, so you are left with one copy of the watched content, and one copy of the non-watched content.

The `Remove watched`/`Remove duplicates` change is only "commited" after you exit the playlist page.
You have to: `...` -> "Remove watched" -> "OK" -> `←` -> re-open playlist -> `...` -> "Remove duplicates" -> "OK"
to remove both watched and duplicates.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

Android 13 / One UI Core 5.1

### Affected device model

Samsung Galaxy A22 5G

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ghost**
#### What is it?
- [x] Bugfix (user facing)
- [x] Codebase improvement (dev facing)

#### Description of the changes in your PR

- Commit all the playlist changes to db immediately
- \+ some additional minor code cleanup in the file

#### Fixes the following issue(s)

- Fixes #11138

#### Relies on the following changes

- As was suggested by @opusforlife2 in #11138 all the changes are commited immediately

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] The proposed changes follow the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md#ai-policy).
- [x] I tested the changes using an emulator or a physical device.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java [hunk 1]
```diff
@@ -767,6 +768,7 @@ public boolean onMove(@NonNull final RecyclerView recyclerView,
                 final boolean isSwapped = itemListAdapter.swapItems(sourceIndex, targetIndex);
                 if (isSwapped) {
                     debounceSaver.setHasChangesToSave();
+                    saveImmediate();
                 }
```
Comment (ghost) [inline app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java:772]: Causes #13040 but without it you can observe reordering if swap items in playlist before deleting duplicates...
