### PR TITLE
Make UI behavior for playback information display more consistent

### LINKED ISSUE #4053: History settings toggles have misconfigured functionality
### Version

- 0.19.8 (and dev branch)

### Steps to reproduce the bug

1. Enable Watch history. Ensure Resume playback and Positions in lists are disabled (in 0.19.8 Positions in lists is automatically greyed out).
2. Play a few videos from the same list.
3. Reopen that list.

### Expected behavior

You don't see playback positions in the list.
### Actual behaviour

You can see playback positions in the list

This is clearly a bug because Watch history has the Positions in lists functionality built in somehow. Moreover, as @avently says, in 0.19.8, Positions in lists is just a dummy toggle that doesn't do anything. In the dev branch it currently has a single function that is specific to the unified player backstack.

So these two toggles currently mislead users. At least Resume playback does what it says.

The solution for this bug is that the Positions in lists toggle should regain its original function, and Watch history should lose the (same) extra function.

### LINKED ISSUE #8176: Instant inconsistent display for playback information in VideoDetailFragment
### Checklist

- [] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

dev, lastest commit till opening this issue

### Steps to reproduce the bug

1. enable `Resume playback` option in `History and cache`.
2. open a video A and watch for a while (or seek to somewhere in the video).
3. open a video B and watch for a while (or seek to somewhere in the video).
4. press system back button, it displays the detailed thumbnail for A, while it displays the playback information (relevant views are `position_view` and `detailed_position_view`) for B for a instance, then display for A.

### Expected behavior

keeps displaying playback information for A.

### Actual behavior

at first displays playback information for B for a while.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/36195713/162781886-446c08c2-7a36-405c-9736-3a0653a4a016.mp4

### Logs

_No response_

### Affected Android/Custom ROM version

Android 10 / Minu 12

### Affected device model

Redmi k30i

### Additional information

I would fix this together with #4053, where I'm to make sure the display of `position_view` and `detailed_position_view` are controlled by relevant user setting, trivial though, not fixing this also makes the setting function kinda inconsistent. Please reply if this shouldn't be considered as bug.

0.22.1 (via github)(latest version) has no this problem, it has different behavior that it displays thumbnail for B instead of A when press system back button.

### PR DESCRIPTION
**Pull request by Trust04zh**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Make `Resume playback` the dependency of `Positions in lists`.
- Regain the function to control if playback information for videos in lists should display for option `Positions in lists`.
- Use `Resume playback` to control if playback information in `VideoDetailFragment` should display (`positionView` and `detailPositionView`, for UI), and remove this function for `Positions in lists`.
- Animate without delay in case that `positionView` and `detailPositionView` should disappear.

#### Before/After Screenshots/Screen Record

- Before:

https://user-images.githubusercontent.com/36195713/162966408-72defb1b-c1d4-4719-badf-a7eebecd8fe3.mp4

- After:

https://user-images.githubusercontent.com/36195713/162966432-8d248fc0-3044-4f7e-9f2d-41fc155505b8.mp4

#### Fixes the following issue(s)

- Fixes #4053 
- Fixes #8176

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 1]
```diff
@@ -1705,68 +1705,56 @@ public void openDownloadDialog() {
...
+            positionSubscriber = recordManager.loadStreamState(info)
+                    .subscribeOn(Schedulers.io())
+                    .onErrorComplete()
+                    .observeOn(AndroidSchedulers.mainThread())
+                    .subscribe(state -> {
+                        updatePlaybackProgress(
+                                state.getProgressMillis(), info.getDuration() * 1000);
+                    }, e -> {
+                        if (DEBUG) {
+                            e.printStackTrace();
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1736]: Please use the logger here

File: app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java [hunk 2]
```diff
@@ -26,6 +30,23 @@ public AnimatedProgressBar(final Context context, final AttributeSet attrs,
...
+        final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
+
+        return prefs.getBoolean(context.getString(
+                        R.string.enable_watch_history_key), true)
+                && prefs.getBoolean(context.getString(
+                        R.string.enable_playback_resume_key), true)
+                && prefs.getBoolean(context.getString(
+                        R.string.enable_playback_state_lists_key), true);
+    }
+
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java:49]: Please remove this from the ProgressBar.
A progressbar is unrelated to the settings...

File: app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java [hunk 3]
```diff
@@ -26,6 +30,23 @@ public AnimatedProgressBar(final Context context, final AttributeSet attrs,
         super(context, attrs, defStyleAttr);
     }
 
+    /**
+     * For video items in lists, progress bar for playback information should only display when
+     * option `Positions in lists` is enabled.
+     * @return whether `Positions in lists` is enabled
+     */
+    public Boolean getPositionsInListsEnabled() {
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java:38]: This can be a primitive ``boolean``

**Review by litetex — COMMENTED** [review]
Thank you for the PR.

Had a quick review:

* Please add some documentation/comments that explain (e.g. on complex if blocks) why stuff is happening
* Some code snippets look like they are copy-pasted. Consider using abstraction.
* Please don't use settings-logic inside a UI class (#Layering)

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java (hunk 1 above)
Comment (Trust04zh) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1736]: Thanks! Gonna improve that, here I use the original code.

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 4]
```diff
@@ -1705,68 +1705,56 @@ public void openDownloadDialog() {
...
+                        }
+                    }, () -> {
+                        binding.positionView.setVisibility(View.GONE);
+                        binding.detailPositionView.setVisibility(View.GONE);
+                    });
+        }
```
[the remark this answers is not in the document]
Comment (Trust04zh) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1742]: This is the logic to decide if `positionView` and `detailPositionView` should display, Some conditions are from previous code, I will try to add more comments here,

File: app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java (hunk 2 above)
Comment (Trust04zh) [reply app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java:49]: The settings are needed to fix #4053, to solve this issue, option `Positions in lists` should control the display of progress bar in video lists

File: app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java (hunk 3 above)
Comment (Trust04zh) [reply app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java:38]: currently in some situations where progress bar information better refresh (for user experience) it won't refresh, I think there may be further improvement, like use listener to update. Previously I just calculate the boolean once but finally write the code that calculate it dynamically, as I think there's better be an approach to update its value. I'm noob in real-world programming and would be appreciated if you describe more about the benefit that just use a `boolean`.

**Comment by Trust04zh** [comment]
The updates
- add a util class `dependentPreferenceHelper` to retrive option value (enabled or not) with complex dependencies.
- add just one comment, I think the code is clear to read now.
- use primitive `boolean` instead of `Boolean` for added methods. 
- removed the debug log info since it can not be reached.

**Comment by Trust04zh** [comment]
Just a remind that this pr has been shelved for some time, it may be better if someone would like to review this if the issues related to this pr should be solved and my solution being considered to be acceptable, or I may forget about my codes XD. Anyway I hope my pr not to bother you, so you can also just take this pr as a reference (if helpful) when solving related issues in the future.

**Review by Stypox — CHANGES_REQUESTED** [review]
Thank you for the PR! I agree with litetex, the code in the various stream item holders should be deduplicated. Maybe you could add a common method that takes as parameter the `itemProgressView`, and the data needed to take decisions and update the UI.
Since this and other requested changes require knowledge about the codebase, if you need help or want me to do this, just ask ;-)

**Comment by opusforlife2** [comment]
@Trust04zh Hey, will you be incorporating the review at some point?

**Comment by Trust04zh** [comment]
@opusforlife2 yes, I will check the review and update the code in the recent two or three days.

**Comment by Trust04zh** [comment]
Thank you for the reviews @Stypox! I agree with them and updated the code accordingly. There is no functinoal change in the new commits. 

As some code changes are removed in new commits, the duplication in item holder classes reduces but still exists.

> Maybe you could add a common method that takes as parameter the itemProgressView, and the data needed to take decisions and update the UI.

I'm not sure about how to make such code abstraction, since the three classes are not simply extended from the same superclass and the `updateState` methods have different signature. I would be appreciate if you could do this.

**Review by Stypox — CHANGES_REQUESTED** [review]
Sorry for the long time passed... I hope you still remember something ;-)

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 5]
```diff
@@ -1723,67 +1724,48 @@ public void openDownloadDialog() {
...
-                // Show saved position from backStack if user allows it
-                showPlaybackProgress(playQueue.getItem().getRecoveryPosition(),
-                        playQueue.getItem().getDuration() * 1000);
-                animate(binding.positionView, true, 500);
-                animate(binding.detailPositionView, true, 500);
-            }
+
+        if (!getResumePlaybackEnabled(activity)
+                || playQueue == null || playQueue.getStreams().isEmpty()
+                || playQueue.getItem().getRecoveryPosition() == RECOVERY_UNSET) {
```
[the remark this answers is not in the document]
Comment (Trust04zh) [reply app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1734]: I checked the behavior and agree that your idea is correct, would fix this

File: app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java [hunk 6]
```diff
@@ -81,6 +83,10 @@ public void updateFromItem(final InfoItem infoItem,
             itemProgressView.setVisibility(View.GONE);
         }
 
+        if (!getPositionsInListsEnabled(itemProgressView.getContext())) {
+            itemProgressView.setVisibility(View.GONE);
```
[the remark this answers is not in the document]
Comment (Trust04zh) [reply app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java:89]: Only this holder retrieves `state` as your description, the other two holder works differently, so I just updated this holder.

**Comment by Trust04zh** [comment]
@Stypox Thanks for your reviewing and sorry that I just found the email reminding me for your reply, the code is updated.

File: app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java [hunk 7]
```diff
@@ -1723,67 +1723,43 @@ public void openDownloadDialog() {
...
-                    }
+                    // impossible since the onErrorComplete()
                 }, () -> {
                     binding.positionView.setVisibility(View.GONE);
                     binding.detailPositionView.setVisibility(View.GONE);
                 });
+        if (!getResumePlaybackEnabled(activity)) {
+            binding.positionView.setVisibility(View.GONE);
+            binding.detailPositionView.setVisibility(View.GONE);
+        }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java:1748]: Mmmh, shouldn't this be on line 1730, and with a `return` inside? When the `loadStreamState` completes it will either call the `onComplete` lambda, which contains the same two lines, or the `updatePlaybackProgress` that if resume playback is disabled will do nothing at all. So there is no need to `loadStreamState` at all if `getResumePlaybackEnabled()` is false.

File: app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java [hunk 8]
```diff
@@ -81,6 +86,10 @@ public void updateFromItem(final InfoItem infoItem,
             itemProgressView.setVisibility(View.GONE);
         }
 
+        if (!DependentPreferenceHelper.getPositionsInListsEnabled(itemProgressView.getContext())) {
+            itemProgressView.setVisibility(View.GONE);
+        }
+
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java:92]: I don't think you need these lines. If you look above, every branch of the `if`s sets the `itemProgressView`'s visibility.

File: app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java [hunk 9]
```diff
@@ -111,19 +120,28 @@ public void updateState(final InfoItem infoItem,
...
+                    .blockingGet()[0];
+        }
         if (state != null && item.getDuration() > 0
                 && !StreamTypeUtil.isLiveStream(item.getStreamType())) {
             itemProgressView.setMax((int) item.getDuration());
-            if (itemProgressView.getVisibility() == View.VISIBLE) {
-                itemProgressView.setProgressAnimated((int) TimeUnit.MILLISECONDS
-                        .toSeconds(state.getProgressMillis()));
+            if (DependentPreferenceHelper
+                    .getPositionsInListsEnabled(itemProgressView.getContext())) {
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java:133]: This `if` condition is not needed, you can just run the code below directly. `state != null` is a condition of the `if` on line 129, and the state can be non-null only if positions in lists are enabled because of the `if` on line 124.

File: app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java [hunk 10]
```diff
@@ -80,6 +81,10 @@ public void updateFromItem(final LocalItem localItem,
             itemDurationView.setVisibility(View.GONE);
         }
 
+        if (!DependentPreferenceHelper.getPositionsInListsEnabled(itemProgressView.getContext())) {
+            itemProgressView.setVisibility(View.GONE);
+        }
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java:86]: I think you should add `itemProgressView.setVisibility(View.GONE)` below line 81 (don't know why it wasn't there before), and add the `getPositionsInListsEnabled` condition to the `if` on line 72.

File: app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java [hunk 11]
```diff
@@ -111,13 +116,19 @@ public void updateState(final LocalItem localItem,
...
+                    itemProgressView.setProgressAnimated((int) TimeUnit.MILLISECONDS
+                            .toSeconds(item.getProgressMillis()));
+                } else {
+                    itemProgressView.setProgress((int) TimeUnit.MILLISECONDS
+                            .toSeconds(item.getProgressMillis()));
+                    ViewUtils.animate(itemProgressView, true, 500);
+                }
             } else {
                 itemProgressView.setProgress((int) TimeUnit.MILLISECONDS
                         .toSeconds(item.getProgressMillis()));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java:131]: Uhm, why are you showing progress even if positions in lists are disabled?

Also, I think you should move the `getPositionsInListsEnabled` condition to the `if` on line 117

File: app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java [hunk 12]
```diff
@@ -110,6 +111,10 @@ public void updateFromItem(final LocalItem localItem,
             itemProgressView.setVisibility(View.GONE);
         }
 
+        if (!DependentPreferenceHelper.getPositionsInListsEnabled(itemProgressView.getContext())) {
+            itemProgressView.setVisibility(View.GONE);
+        }
+
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java:117]: Remove this and just add the `getPositionsInListsEnabled` condition to the `if` on line 101, for the same reason as above

File: app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java [hunk 13]
```diff
@@ -143,13 +148,19 @@ public void updateState(final LocalItem localItem,
...
+                    itemProgressView.setProgressAnimated((int) TimeUnit.MILLISECONDS
+                            .toSeconds(item.getProgressMillis()));
+                } else {
+                    itemProgressView.setProgress((int) TimeUnit.MILLISECONDS
+                            .toSeconds(item.getProgressMillis()));
+                    ViewUtils.animate(itemProgressView, true, 500);
+                }
             } else {
                 itemProgressView.setProgress((int) TimeUnit.MILLISECONDS
                         .toSeconds(item.getProgressMillis()));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java:163]: Same as above. I don't get why this is here, and the `getPositionsInListsEnabled` condition should be moved to the `if` on line 149

File: app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java (hunk 3 above)
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/views/AnimatedProgressBar.java:38]: I think you left this here by accident. Please remove it.

**Review by Stypox — CHANGES_REQUESTED** [review]

**Comment by Trust04zh** [comment]
@Stypox Thanks for your reviewing! The code mentioned are updated.

**Comment by Stypox** [comment]
@Trust04zh there are some unresolved points. You can use the "Resolve conversation" button to mark off things you have already done, in order not to forget anything. https://github.com/TeamNewPipe/NewPipe/pull/8180#discussion_r920106595 https://github.com/TeamNewPipe/NewPipe/pull/8180#discussion_r1059652682

**Comment by Trust04zh** [comment]
@Stypox Now they are marked as resolved (after being confirmed to be so). Sorry I took a few days to reply, I just took a vacation.

**Comment by Stypox** [comment]
Mmmh, you didn't push any new commit though, so I guess you misunderstood me: the things I did not mark as done myself were the ones that still needed to be done ;-)

**Comment by Trust04zh** [comment]
@Stypox updated now, thank you for the reminder, I did forget to deal with them 😟

**Comment by Trust04zh** [comment]
@Stypox yes, they are good to me.

> Now positions in lists only depends on watch history. Was there a specific reason for them to depend on "Resume playback"? One might want to see progress on items without resuming playback.

In my understanding, displaying progress just tells playback information vaguely, and if users do not want to resume playback, it does not quite make sense. There was no clear discussion for this point in the previous issue, and the change is fine to me.

**Comment by Trust04zh** [comment]
@opusforlife2 

I have updated the description of this pr based on the final changes, including:

- Indicating that `Resume playback` did not become a dependency of `Positions in lists`.
- Adding an explanation of what changes are reflected in the two videos.

I think that the description now clarifies things, and I'm willing to update if there are still unclear points for you.

**Comment by Trust04zh** [comment]
Change 4 is for fixing https://github.com/TeamNewPipe/NewPipe/issues/8176. In the "before" video, around 38 to 39 second, you can see the inconsistent behavior that the playback information becomes wrong for an instant.
