### PR TITLE
Fix downloads of streams with missing MediaFormat

### LINKED ISSUE #10153: SoundCloud Download "Unknown Quality" audio cannot be played
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Go to NewPipe
2. Go to the SoundCloud option
3. Find a song that allows you to download in bitrate higher than 125kbps.  Normally it says "Unknown Quality" with a filesize significantly bigger than the default mp3 128kbps.
4. Download it
5. Try to play it with AIMP
6. Go to terminal of your phone and do `file $DOWNLOADED_FILE` it says file type is just "data".

### Expected behavior

I should be able to play this file.

### Actual behavior

Music players cannot play the downloaded file.
Linux does not detect the extension.

### Screenshots/Screen recordings

screenshot

### Logs

No crash logs.

### Affected Android/Custom ROM version

Android 13, OxygenOS

### Affected device model

OnePlus 8 Pro

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Rertrieve `MediaFormat`s for streams in case the extractor was not able to get them. Sometimes the MediaFormat can be retrieved from the HTTP response header that is fetched when getting the stream size. 

- The dialog now also displays "Unknown Quality" if the quality is unknown. Previously, the media format name was displayed as title and as quality info.

- Some code improvements simplifying castings by directly casting in if-conditions using `instanceof`

#### Before/After Screenshots/Screen Record

<table>
    <thead>
        <tr>
            <th>Before</th>
            <th>After</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> 

 </td>
            <td>  </td>
        </tr>
    </tbody>
</table>

#### Fixes the following issue(s)
- Fixes #10153 

#### Relies on the following changes
TeamNewPipe/NewPipeExtractor#1074

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java [hunk 1]
```diff
@@ -271,13 +289,147 @@ public static <X extends Stream> Single<Boolean> fetchSizeForWrapper(
...
+                            final Charset charset = Charset.forName(encoding);
+                            // decode info with the given encoding
+                            if (charset == null) {
+                                continue;
+                            }
+                            if (charset.equals(Charset.defaultCharset())) {
+                                fileName = part;
+                            } else {
+                                fileName = new String(part.getBytes(charset),
+                                        StandardCharsets.UTF_8);
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java:374]: I am not sure whether this code does the right thing. If the data is already in a String then it has already been decoded in the default format, so the only way to re-decode it in a different charset would be to reverse the initial decoding (with `encode(default charset)`) and then decode it with the different charset.

**Review by Stypox — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java (hunk 1 above)
Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java:374]: Hm, you are right. In that case, we cannot do much about it. And the encoding should not matter because we only want to get the file extension which should always be in from the Latin alphabet. Shall I remove the encoding part?

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java:376]: Yes in my opinion

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java]: Done

**Comment by TobiGr** [comment]
- Rebased
- Removed encoding stuff as discussed in the review above
- Added a few more comments & docs

File: app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java [hunk 2]
```diff
@@ -271,13 +288,145 @@ public static <X extends Stream> Single<Boolean> fetchSizeForWrapper(
...
+
+        @VisibleForTesting
+        public static <X extends Stream> boolean retrieveMediaFormatFromContentTypeHeader(
+                @NonNull final X stream,
+                @NonNull final StreamInfoWrapper<X> streamsWrapper,
+                @NonNull final Response response) {
+            // try to get the format by content type
+            // some mime types are not unique for every format, those are omitted
+            final List<MediaFormat> formats = MediaFormat.getAllFromMimeType(
+                    response.getHeader("Content-Type"));
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java:404]: `response.getHeader("Content-Type")` will return null if there are no such headers, but fortunately that's not a problem since `getAllFromMimeType` works normally with null strings.
