### PR TITLE
Fix handling exception in `playOnPopup` and toggle description tab

### LINKED ISSUE #6873: When comments & description are both disabled, enabling description only temporarily enables comments only
### Checklist

- [x] I am using the latest version - 0.21.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Turn off 'Show comments' & 'Show description' in Settings
2. Use the app for a bit
3. Navigate to settings and enable 'Show description'
4. Only comments will be enabled at first, but the bug corrects itself without further action

### Actual behavior

Enabling description temporarily enables comments.

### Expected behavior

Enabling description should only enable description and leave comments alone

### Logs

NewPipe gui comments-info-display bug1_2021-08-02_07-42-35

NewPipe gui comments-info-display bug2_2021-08-02_07-43-03

### Device info

 - Android version/Custom ROM version: 8.0
 - Device model: Samsung Galaxy S7 Edge

### LINKED ISSUE #6976: Startup errors opening videos
### Checklist

- [x] I am using the latest version - 0.21.9
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to search icon , trending menu,what's new, history menu,
2. Press on any video and don't wait thumbnails of videos
3. The crash appears

### Actual behavior

The app crash 10-15 per day, it is really painful to wait 5-7 sec every time when I opened NewPipe !

### Expected behavior

The normal situation that I can use the NewPipe from the first 0 seconds of opening the app

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TN
* __Content Language:__ fr
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux samsung/a50dd/a50:11/RP1A.200720.012/A505FDDU8CUE5:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference
	at org.schabi.newpipe.fragments.list.search.SearchFragment.handleSuggestions(SearchFragment.java:971)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$15(SearchFragment.java:817)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$15$SearchFragment(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.search.-$$Lambda$SearchFragment$q2wTJo-kDxgd91qkgYweNQgQ484.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 10 more

```
</details>
<hr>

### Device info

 - Android version: 11
 - Device model: Samsung A50 SM-A505F

### LINKED ISSUE #6979: PrivateContentException not caught in description links
### Checklist

- [x] I am using the latest version - 0.21.9 (and latest directly from git) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open this video: https://www.youtube.com/watch?v=aI45Vdyth8g
2. Click the first link in the description (Starts with `Extra footage video:`)
3. Crash!

### Actual behavior

Crash!

### Expected behavior

Show `VIDEO NOT AVAILABLE` page.

### My Analysis

The error happens in the `Single` returned from `ErrorHelper.java:116` `public static Single<StreamInfo> getStreamInfo(final int serviceId, final String url, final boolean forceLoad)`. That `Single` is subscribed on by `InternalUrlsHandler.java:147`. That `subscribe` call doesn't have an error handler so the crash happens.

Here's a diff that prevents the crash and shows a `Toast`:

```diff
diff --git a/app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java b/app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
index 39ec51ce4..a48dc3c4e 100644
--- a/app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
+++ b/app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
@@ -1,6 +1,7 @@
 package org.schabi.newpipe.util.external_communication;
 
 import android.content.Context;
+import android.widget.Toast;
 
 import androidx.annotation.NonNull;
 
@@ -148,6 +149,8 @@ public final class InternalUrlsHandler {
                     final PlayQueue playQueue
                             = new SinglePlayQueue(info, seconds * 1000);
                     NavigationHelper.playOnPopupPlayer(context, playQueue, false);
+                }, throwable -> {
+                    Toast.makeText(context, "BOO! 👎😡", Toast.LENGTH_SHORT).show();
                 }));
         return true;
     }
```

I would like to try and fix this, but I don't know how to show the `VIDEO NOT AVAILABLE` page.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | org.schabi.newpipe.extractor.exceptions.PrivateContentException: This video is private.
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: org.schabi.newpipe.extractor.exceptions.PrivateContentException: This video is private.
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:788)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:748)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [x] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Fixed updating the wrong tabs when changing settings while running the minimized player in VideoDetailFragment. The comments tab was updated although the settings for the description tab were changed.
- Fixed `OnErrorNotImplementedException` in `InternalUrlsHandler.playOnPopup` by implementing error handling. A popup is shown with a little info on the error:
  
- Fixed  `OnErrorNotImplementedException` in `SearchFragment.initSuggestionObserver()`. Errors are reported in the snackbar now. Not sure if I also managed to fix the cause of the original error. This needs to be investigated.
- Fixed a few warnings by SonarLint

### Fixes issues
- Fixes #6873
- Fixes #6979
- Fixes #6976

#### APK testing 

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR.

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by litetex — COMMENTED** [review]
Code looks good to me

How can I test these changes? E.g. the popup error?

I'm pretty sure this PR fixes also multiple issues. 
Could please link them in the description of the PR?

**Comment by TobiGr** [comment]
You can follow the steps provided in our Matrix channel.
1. Open https://www.youtube.com/watch?v=fSM_SO0GIBc&t=1
2. Go to the description and click on the second link (http://youtu.be/rLje-qEraOE)

> I'm pretty sure this PR fixes also multiple issues.  Could please link them in the description of the PR?

Only found one, I guess the others were closed as duplicates. The other `OnErrorNotImplementedException` in #6976 is not related to this and should be investigated separately.

**Comment by TobiGr** [comment]
Fixed the `OnErrorNotImplementedException` from #6976

File: app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java [hunk 1]
```diff
@@ -146,9 +154,15 @@ public static boolean playOnPopup(final Context context,
                 .observeOn(AndroidSchedulers.mainThread())
                 .subscribe(info -> {
                     final PlayQueue playQueue
-                            = new SinglePlayQueue(info, seconds * 1000);
+                            = new SinglePlayQueue(info, seconds * 1000L);
                     NavigationHelper.playOnPopupPlayer(context, playQueue, false);
-                }));
+                }, throwable -> new AlertDialog.Builder(context)
```
Comment (litetex) [inline app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java:159]: Idea: Maybe also log the error here so that we have more information in case of debugging

**Comment by litetex** [comment]
Test looks good, works like a charm :)

File: app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java (hunk 1 above)
Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java]: Done

File: app/src/main/java/org/schabi/newpipe/BaseFragment.java [hunk 2]
```diff
@@ -16,7 +16,7 @@
 
 public abstract class BaseFragment extends Fragment {
     protected final String TAG = getClass().getSimpleName() + "@" + Integer.toHexString(hashCode());
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/BaseFragment.java:18]: Shouldn't this also be `static`?

**Review by Stypox — CHANGES_REQUESTED** [review]
Looks good to me

File: app/src/main/java/org/schabi/newpipe/BaseFragment.java (hunk 2 above)
Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/BaseFragment.java:18]: Wait no, just realized it uses `hashCode()`, so no, it shouldn't

**Review by Stypox — APPROVED** [review]

**Comment by opusforlife2** [comment]
No idea. Anyway, that issue is still not solved, apparently, so it needs to stay open.
