### PR TITLE
Notifications are no longer requested again after rotating the phone

### LINKED ISSUE #12194: "allow NewPipe to send you notification" message appears again when changing from portait to landscape view
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.6

### Steps to reproduce the bug

1. Uninstall the app if it is already on the phone.
2. Re/install the app.
3. Start with portait view.
4. Click on "don't allow" when the message appears.
5. Directly switch to landscape view.

### Expected behavior

The notification message should not appear a second time.

### Actual behavior

It does.

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung Galaxy A53 5G

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Isaac-75**
#### What is it?
- [X] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR
- Added boolean "notificationsAccepted" field in the App class
- Added getNotificationsAccepted() method, which returns the field
- Added setNotificationsAccepted() method, which sets the field to true
- Incorporated methods in the checkPostNotificationsPermission() method within the PermissionHelper class

#### Fixes the following issue(s)
- Fixes #12194 

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [ X] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/App.java [hunk 1]
```diff
@@ -66,12 +66,21 @@ public class App extends Application {
 
     private boolean isFirstRun = false;
     private static App app;
+    private boolean notificationsRequested = false;
```
Comment (TobiGr) [inline app/src/main/java/org/schabi/newpipe/App.java:68]: can you move this one line up so that the variables are in a logical order please?

Comment (Isaac-75) [reply app/src/main/java/org/schabi/newpipe/App.java:68]: Yes, just committed this change.
