### PR TITLE
Fix crash deleting video refreshing

### LINKED ISSUE #4874: Crash while deleting a video from a list
### Checklist

- [x] I am using the latest version - 0.20.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

I'm not sure it can be reproduced.  It happened when deleting a video from a list.  After restarting NewPipe I've been able to delete this video and others.

### Actual behaviour

The app creashed

### Expected behavior

The video should be deleted from the list.

## Exception
* User Action: ui error
* Request: App crash, UI failure
* Content Country: GB
* Content Language: en
* App Language: en_US
* Service: none
* Version: 0.20.2
* OS: Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

java.lang.ArrayIndexOutOfBoundsException: length=115; index=-1
 at java.util.ArrayList.remove(ArrayList.java:506)
 at org.schabi.newpipe.local.LocalItemListAdapter.removeItem(LocalItemListAdapter.java:128)
 at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.deleteItem(LocalPlaylistFragment.java:620)
 at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$19$LocalPlaylistFragment(LocalPlaylistFragment.java:790)
 at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$90syoQLDH9fDdmrHKGkSeGndyvo.onClick(Unknown Source:4)
 at org.schabi.newpipe.util.StreamDialogEntry.clickOn(StreamDialogEntry.java:105)
 at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$20$LocalPlaylistFragment(LocalPlaylistFragment.java:793)
 at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$XkVgE8RSZjjT9Ft0r7B-0GYSTrk.onClick(Unknown Source:4)
 at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1169)
 at android.widget.AdapterView.performItemClick(AdapterView.java:318)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
 at android.widget.AbsListView$3.run(AbsListView.java:4052)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6718)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

</details>
<hr>

### Device info

 - Android version/Custom ROM version: LineageOS 9
 - Device model: X00TD

### PR DESCRIPTION
**Pull request by hlloreda**
#### What is it?
- [x] Bugfix (user facing)
- [ ] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of the changes in your PR

- Method equals has been overridden in the PlaylistStreamEntry class so that the index (in the method 'removeItem' in the Class LocalItemListAdapter) does not return '-1' if the memory address is not the same. In this method, I compare all the different attributes to make sure it's the same object. The hashCode method was generated by Android Studio.

#### Fixes the following issue(s)

-  fixes #4874

#### APK testing 

app-deleting-video-refreshing-crashfix.zip

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt [hunk 1]
```diff
@@ -36,4 +36,20 @@ class PlaylistStreamEntry(
...
         return LocalItem.LocalItemType.PLAYLIST_STREAM_ITEM
     }
+
+    override fun equals(other: Any?): Boolean {
+        if (other == null || other !is PlaylistStreamEntry || streamEntity != other.streamEntity ||
+                progressTime != other.progressTime || streamId != other.streamId || joinIndex != other.joinIndex
+        ) return false
+
+        return true
+    }
```
Comment (mhmdanas) [inline app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt:46]:
```suggestion
    override fun equals(other: Any?): Boolean =
      !(other == null || other !is PlaylistStreamEntry || streamEntity != other.streamEntity ||
        progressTime != other.progressTime || streamId != other.streamId || joinIndex != other.joinIndex)
```

**Review by mhmdanas — COMMENTED** [review]
Looks good to me. Just one minor nit.

**Review by XiangRongLin — COMMENTED** [review]
Can't a `data class` be used? You mention that you just compare all fields, which the default generated method from Android Studio should also do, which in turn is implicitly generated in data classes

**Comment by mhmdanas** [comment]
@XiangRongLin I missed that. 

@hlloreda ignore my suggestion and try @XiangRongLin's one.

**Comment by XiangRongLin** [comment]
> or you mean to simply define the 'PlaylistStreamEntry' class as a 'data class' ?

@hlloreda This.

**Review by mhmdanas — APPROVED** [review]
LGTM

**Review by Stypox — APPROVED** [review]

**Comment by Stypox** [comment]
Thank you for the contribution :-D
