### PR TITLE
Fix removing unwatched streams from playlist when using "remove watched"

### LINKED ISSUE #12917: "Remove watched" removes unwatched videos
### Checklist

- [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.28.0

### Steps to reproduce the bug

1. Add a video to one of your local playlists.
2. Open the video.
3. Pause and dismiss the video **before a full second of it is played**.
4. In the playlist, tap the 3 dots on the upper right corner and select "Remove watched" and tap "OK" in the warning popup.

### Expected behavior

This video shouldn't be removed from the playlist.

### Actual behavior

This video is removed from the playlist.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/7b26a2aa-6aac-42e6-88f1-a1cedc154bc5

### Logs

_No response_

### Affected Android/Custom ROM version

Android 15 (MagicOS 9.0)

### Affected device model

Honor 90 (REA-NX9)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TobiGr**
#### What is it?
- [x] Bugfix (user facing)

#### Bug fix
The bug is caused by a wanted but forgotten inconsistency in the database. A stream can be listed in the watch history (StreamHistoryEntity) while having no corresponding playback state (StreamStateEntity) containing the matching playback position. This is caused by the fact that NewPipe does not consider a watch time of less than five seconds to be worthy to be put into the StreamStateEntity because the video was most likely played by error. Those videos are, however, counted and stored in the watch history.

I think we need to discuss whether we should add the stream to the watch history at all.

#### UI/UX improvements
The dialog with three options was changed to a yes and cancel button and a checkbox. The strings were changed to respect that a playlist can also contain audio streams. "streams" is now used in favour of "video".

#### Before/After Screenshots/Screen Record
A screen record with the old version is in #12917. The following recording shows the new behaviour and dialog.

[Screen_recording_20251221_212542.webm](https://github.com/user-attachments/assets/98172664-1888-4cc6-bb86-9ca22b0e5a83)

#### Fixes the following issue(s)
- Fixes #12917 

#### APK testing
The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

This backup can be used to easily test different scenarios: [NewPipe-Data-Playlist-stream-states.zip](https://github.com/user-attachments/files/24281135/NewPipe-Data-Playlist-stream-states.zip)

The test playlist contains five streams:
- not watched
- watched, but playback position < 5 sec
- watched (playback position in the middle of the video)
- watched more than 3/4, but not completely
- watched until the end

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java [hunk 1]
```diff
@@ -447,39 +443,28 @@ public void removeWatchedStreams(final boolean removePartiallyWatched) {
...
-                            if (indexInHistory < 0 || (streamStateEntity != null
-                                    && !streamStateEntity.isFinished(duration))) {
-                                itemsToKeep.add(playlistItem);
-                            } else if (!isThumbnailPermanent && !thumbnailVideoRemoved
-                                    && playlistManager.getPlaylistThumbnailStreamId(playlistId)
-                                    == playlistItem.getStreamEntity().getUid()) {
-                                thumbnailVideoRemoved = true;
-                            }
+                    final var streamStates = recordManager
+                            .loadLocalStreamStateBatch(playlist).blockingGet();
```
Comment (Stypox) [inline app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java:446]: Now streamStates is fetched even when not needed, i.e. when `removePartiallyWatched` is `false`

Comment (Stypox) [reply app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java:446]: Nevermind I was wrong :-)
