### PR TITLE
Fix crash on screen rotation while entering SoundCloud import URL

### LINKED ISSUE #11914: UI error crash when rotating screen while typing url to import soundcloud file
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.4(latest build)

### Steps to reproduce the bug

1.click "Navigation Drawer"/"Hamburger Menu"
2.click "Subscriptions" button
3.click "more options" and click "import from"
4.select "soundcloud" button
5.type anything in edit view and click "import" button
6.when the confirm dialog appears, rotating the device and app crash.

### Expected behavior

keep same state before rotating

### Actual behavior

crash

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/b7a7018f-0600-4e33-809e-c8fb5aaa4fc8

### Logs

<details><summary>crash log</summary>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe.debug/org.schabi.newpipe.MainActivity}: java.lang.IllegalStateException: Result intent is null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5456)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5362)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Result intent is null
        at org.schabi.newpipe.local.subscription.ImportConfirmationDialog.onCreate(ImportConfirmationDialog.java:57)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
        at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:142)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        ... 13 more

```

</details>

### Affected Android/Custom ROM version

android11

### Affected device model

google nexus4

### Additional information

may be similar with #7825 ?

### PR DESCRIPTION
**Pull request by siddhesh-06**
#### What is it?
- [x] Bugfix (user facing)

#### Description of the changes in your PR
- Fixed the below IllegalStateException
Screenshot 2026-01-04 003632

- Preserved the service Intent across configuration changes (e.g. screen rotation)
- Ensured the dialog safely restores its state after recreation
- Prevented null access when the dialog is recreated by the system

#### Before/After Screenshots/Screen Record

- Before:

https://github.com/user-attachments/assets/d599c85f-f630-4904-ba9e-eab240ab5ccb

- After:

https://github.com/user-attachments/assets/ca7fe38d-5c04-43c5-b19d-dc8c86035029

#### Fixes the following issue(s)

- Fixes #11914

#### APK testing

The APK can be found by going to the "Checks" tab below the title. On the left pane, click on "CI", scroll down to "artifacts" and click "app" to download the zip file which contains the debug APK of this PR. You can find more info and a video demonstration [on this wiki page](https://github.com/TeamNewPipe/NewPipe/wiki/Download-APK-for-PR).

#### Due diligence
- [x] I read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md).
- [x] The proposed changes follow the [AI policy](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md#ai-policy).
- [x] I tested the changes using an emulator or a physical device.

### CODE REVIEW

File: app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java [hunk 1]
```diff
@@ -50,6 +49,10 @@ public Dialog onCreateDialog(@Nullable final Bundle savedInstanceState) {
     public void onCreate(@Nullable final Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
 
+        if (getArguments() != null) {
+            resultServiceIntent = getArguments().getParcelable(EXTRA_RESULT_SERVICE_INTENT);
+        }
```
Comment (ghost) [inline app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java]: Maybe better using `requireArguments()`? You won't need to check for null then

Comment (siddhesh-06) [reply app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java]: Yehh we can use that 👍🏻

Comment (ghost) [reply app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java]: 1. `requireArguments` gives you not null bundle but just formally it doesn't mean that you won't get null from `getParcelable` itself

2. Just formally `getArguments` is correct too if we assume that in `show()` you provided first result by your own

3. Probably lifting exeception is correct because `show` ensured...

4. Newpipe uses `@State` annotation in pair with `Bridge` for automatic state saving (look at override fun `onSaveInstanceState` in the same file)

End. I am stupid. Everything said above can be truth but it is my interpretation of things which is usually at least 50% wrong

**Comment by TobiGr** [comment]
LGTM, are we able to remove the state now? At least I do not see areason to keep it now.
[remove-state.patch](https://github.com/user-attachments/files/24474462/remove-state.patch)

```patch
diff --git a/app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java b/app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
index b586ad3..0054bd2 100644
--- a/app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
+++ b/app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
@@ -10,13 +10,11 @@ import androidx.appcompat.app.AlertDialog;
 import androidx.fragment.app.DialogFragment;
 import androidx.fragment.app.Fragment;
 
-import com.evernote.android.state.State;
 import com.livefront.bridge.Bridge;
 
 import org.schabi.newpipe.R;
 
 public class ImportConfirmationDialog extends DialogFragment {
-    @State
     protected Intent resultServiceIntent;
     private static final String EXTRA_RESULT_SERVICE_INTENT = "extra_result_service_intent";
 
@@ -48,10 +46,7 @@ public class ImportConfirmationDialog extends DialogFragment {
     @Override
     public void onCreate(@Nullable final Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
-
         resultServiceIntent = requireArguments().getParcelable(EXTRA_RESULT_SERVICE_INTENT);
-
-        Bridge.restoreInstanceState(this, savedInstanceState);
     }
 
     @Override

```

File: app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
Comment (ghost) [inline app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java]: @TobiGr in case of this PR merge again the same question. Is the check necessary? Probably it would need to be deleted too?

Comment (siddhesh-06) [reply app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java]: @TobiGr Just wanted to confirm shall I remove if condition and use requireContext() ?

Comment (TobiGr) [reply app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java]: yes, I'd just use requireContext()

**Review by TobiGr — APPROVED** [review]
thank you!
